(()=>{'use strict';
const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true,isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);document.documentElement.classList.toggle('standalone-app',standalone);
function installHelp(){document.querySelector('.installModal')?.remove();const modal=document.createElement('div');modal.className='installModal';modal.innerHTML=`<div><small>INSTALL BUNKR</small><h2>PLAY LIKE A REAL APP</h2><p>1. Tap the <b>Share</b> button in Safari.</p><p>2. Choose <b>Add to Home Screen</b>.</p><p>3. Open <b>Bunkr</b> from your Home Screen.</p><p class="hint">Safari bars disappear and the game launches in standalone app mode.</p><button>CLOSE</button></div>`;document.body.append(modal);modal.querySelector('button').onclick=()=>modal.remove()}
function enterFullscreen(){const root=document.documentElement,request=root.requestFullscreen||root.webkitRequestFullscreen;if(!request)return Promise.resolve(false);return Promise.resolve(request.call(root)).then(()=>true).catch(()=>false)}
function openAppMode(){return isiOS?installHelp():enterFullscreen()}
function banner(){if(standalone||document.getElementById('appModeBanner'))return;const element=document.createElement('div');element.id='appModeBanner';element.innerHTML=isiOS?`<div><b>BUNKR APP MODE</b><span>Open fullscreen without Safari controls.</span></div><button id="appModeBtn">HOW TO INSTALL</button><button id="appModeX">×</button>`:`<div><b>BUNKR FULLSCREEN</b><span>Hide browser controls and play like an app.</span></div><button id="appModeBtn">ENTER FULLSCREEN</button><button id="appModeX">×</button>`;document.body.append(element);document.getElementById('appModeX').onclick=()=>element.remove();document.getElementById('appModeBtn').onclick=openAppMode}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(banner,700));else setTimeout(banner,700);
window.BunkrPlatform={standalone,isiOS,openAppMode,enterFullscreen,installHelp};
})();
