(()=>{'use strict';
const CFG=window.AfterlightConfig;if(!CFG)throw new Error('AfterlightConfig must load before economy.js');
const ROOMS=CFG.ROOMS,RULES=CFG.ROOM_ECONOMY||{};
const EARLY_GROWTH=Math.max(1.000001,Number(RULES.costGrowth)||1.62),LATE_GROWTH=Math.max(1.000001,Number(RULES.lateCostGrowth)||Number(RULES.rateGrowth)||1.18),LATE_THRESHOLD=Math.max(1,Number(RULES.lateCostThreshold)||1e15),MAX_VALUE=Math.min(Number.MAX_VALUE,Math.max(1e100,Number(RULES.maximumValue)||1e300)),MAX_ROOM_LEVEL=Math.max(1,Math.floor(Number(RULES.maximumRoomLevel)||3500));
const LOG_MAX=Math.log(MAX_VALUE),LOG_EARLY=Math.log(EARLY_GROWTH),LOG_LATE=Math.log(LATE_GROWTH);
function sanitizeResource(value){const number=Number(value);if(Number.isNaN(number)||number<=0)return 0;if(!Number.isFinite(number)||number>=MAX_VALUE)return MAX_VALUE;return number}
function sanitizeRoomLevel(value){const number=Number(value);return Number.isFinite(number)&&number>0?Math.min(MAX_ROOM_LEVEL,Math.floor(number)):0}
function safeAdd(current,amount){const balance=sanitizeResource(current),gain=Number(amount);if(Number.isNaN(gain)||gain===0)return balance;if(gain===Infinity)return MAX_VALUE;if(gain===-Infinity)return 0;if(gain<0)return Math.max(0,balance+gain);return gain>=MAX_VALUE-balance?MAX_VALUE:balance+gain}
function transitionLevel(room){return Math.max(0,Math.floor(Math.log(LATE_THRESHOLD/Math.max(1,room.base))/LOG_EARLY))}
function roomCostAt(id,currentLevel,costMultiplier=1){const room=ROOMS[id],level=sanitizeRoomLevel(currentLevel),discount=Number(costMultiplier);if(!room||level>=MAX_ROOM_LEVEL||!Number.isFinite(discount)||discount<=0)return Infinity;const transition=transitionLevel(room),earlyLevels=Math.min(level,transition),lateLevels=Math.max(0,level-transition),logCost=Math.log(Math.max(1,room.base))+earlyLevels*LOG_EARLY+lateLevels*LOG_LATE+Math.log(discount);if(!Number.isFinite(logCost)||logCost>LOG_MAX)return Infinity;const cost=Math.exp(logCost);return Number.isFinite(cost)&&cost>0?Math.max(1,Math.floor(cost)):Infinity}
function roomUpgradeQuote(id,count,startLevel=0,costMultiplier=1){const from=sanitizeRoomLevel(startLevel),requested=Math.max(0,Math.floor(Number(count)||0)),available=Math.max(0,MAX_ROOM_LEVEL-from),levels=Math.min(requested,available);if(!ROOMS[id]||levels<1)return{count:0,cost:0,from,to:from};let total=0;for(let index=0;index<levels;index++){const next=roomCostAt(id,from+index,costMultiplier);if(!Number.isFinite(next)||next<=0||next>MAX_VALUE-total)return{count:0,cost:Infinity,from,to:from};total+=next}return{count:levels,cost:total,from,to:from+levels}}
function affordableRoomLevels(id,coins,startLevel=0,costMultiplier=1,limit=RULES.maximumBulk||500){const balance=sanitizeResource(coins),from=sanitizeRoomLevel(startLevel),maximum=Math.min(Math.max(0,Math.floor(Number(limit)||0)),Math.max(0,MAX_ROOM_LEVEL-from));let count=0,total=0;while(count<maximum){const next=roomCostAt(id,from+count,costMultiplier);if(!Number.isFinite(next)||next<=0||next>balance-total)break;total+=next;count++}return{count,cost:total,from,to:from+count}}
function validPurchase(quote,coins,currentLevel=quote?.from){const balance=sanitizeResource(coins),level=sanitizeRoomLevel(currentLevel),count=Number(quote?.count),cost=Number(quote?.cost);return Number.isInteger(count)&&count>0&&level===quote.from&&quote.to===level+count&&Number.isFinite(cost)&&cost>0&&cost<=balance&&Number.isFinite(balance-cost)&&balance-cost>=0}
function subtractPurchase(coins,cost){const balance=sanitizeResource(coins),price=Number(cost);return Number.isFinite(price)&&price>0&&price<=balance?balance-price:balance}
window.AfterlightEconomy=Object.freeze({MAX_VALUE,MAX_ROOM_LEVEL,sanitizeResource,sanitizeRoomLevel,safeAdd,transitionLevel,roomCostAt,roomUpgradeQuote,affordableRoomLevels,validPurchase,subtractPurchase});
})();
