(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState;if(!CFG||!ST)throw new Error('Afterlight core dependencies missing');
const $=id=>document.getElementById(id),S=ST.get(),ROOMS=CFG.ROOMS,RESEARCH=CFG.RESEARCH;
let enemy=null,lastTick=performance.now();
const fmt=n=>n<1000?Math.floor(n)+'':n<1e6?(n/1e3).toFixed(1)+'K':(n/1e6).toFixed(1)+'M';
const resourceBonus=q=>({coins:'coinMult',power:'powerMult',scrap:'scrapMult',food:'foodMult',water:'waterMult',science:'scienceMult'}[q]);
function productionMultiplier(q){let v=(1+Number(S.research.solar||0)*.12)*ST.bonus('prodMult');const key=resourceBonus(q);if(key)v*=ST.bonus(key);if(q==='food')v*=1+Number(S.research.hydro||0)*.2;if(q==='water')v*=1+Number(S.research.filters||0)*.2;return v}
function roomCost(k){return Math.max(1,Math.floor(ROOMS[k].base*Math.pow(1.62,S.rooms[k]||0)*ST.bonus('costMult')))}
function roomRate(k,q){const lv=S.rooms[k]||0;if(!lv)return 0;const raw=(ROOMS[k].prod[q]||0)*lv*Math.pow(1.18,Math.max(0,lv-1));return raw*productionMultiplier(q)}
function rates(){const out={coins:.1,food:0,water:0,power:0,scrap:0,science:0};for(const k in ROOMS)for(const q in out)out[q]+=roomRate(k,q);const special=window.AfterlightSpecialRooms?.rates?.()||{};for(const [q,v] of Object.entries(special))if(q in out)out[q]+=v*productionMultiplier(q);out.coins=(out.coins-.1)+(.1*productionMultiplier('coins'));return out}
function tapDamage(){const base=1+Math.floor(S.kills/7),tools=1+Number(S.research.tools||0)*.3;return Math.max(1,Math.floor(base*tools*ST.bonus('damageMult')))}
const isBoss=()=>S.kills>0&&S.kills%10===9;
function enemyMaxHp(){return Math.floor(9*Math.pow(1.17,S.kills)*(isBoss()?4:1))}
function enemyReward(){const base=(6+S.kills*1.4)*Math.pow(1.075,S.kills)*(isBoss()?7:1),walls=1+Number(S.research.walls||0)*.15;return Math.max(1,Math.floor(base*walls*ST.bonus('zombieMult')))}
function addCoins(amount,applyCoinBonus=true){const gain=amount*(applyCoinBonus?ST.bonus('coinMult'):1);S.coins+=gain;S.total=(S.total||0)+gain;return gain}
function spawn(){const hp=enemyMaxHp();enemy={hp,max:hp,reward:enemyReward(),boss:isBoss(),name:isBoss()?'BRUTE':'WALKER',dead:false};window.dispatchEvent(new CustomEvent('afterlight:enemy',{detail:{...enemy,kills:S.kills}}));hud()}
function toast(text){const e=$('toast');if(!e)return;e.textContent=text;e.style.opacity=1;clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.opacity=0,900)}
function attack(){if(!enemy||enemy.dead)return;const damage=tapDamage();S.stats.clicks=(S.stats.clicks||0)+1;addCoins(damage*.35);enemy.hp-=damage;window.dispatchEvent(new CustomEvent('afterlight:shot',{detail:{damage,enemy:{...enemy}}}));if(enemy.hp<=0){enemy.dead=true;S.kills++;if(enemy.boss)S.stats.bosses=(S.stats.bosses||0)+1;addCoins(enemy.reward);S.scrap+=Math.max(1,Math.floor(enemy.reward*.05));ST.save();ST.notify('combat');setTimeout(spawn,350)}hud()}
function recalc(){S.bunker=1+Math.floor(Object.values(S.rooms).reduce((a,b)=>a+(Number(b)||0),0)/4);return S.bunker}
window.buyRoom=k=>{const room=ROOMS[k];if(!room)return;recalc();if(S.bunker<room.unlock)return toast('BUNKER LEVEL '+room.unlock+' REQUIRED');const cost=roomCost(k);if(S.coins<cost)return toast('NEED '+fmt(cost)+' COINS');ST.update('room',s=>{s.coins-=cost;s.rooms[k]=(s.rooms[k]||0)+1});recalc();renderRooms();renderDrawer();hud()};
window.research=()=>{};
function roomInfo(k){const out=[];for(const q of ['coins','power','food','water','scrap','science']){const v=roomRate(k,q);if(v>0)out.push('+'+v.toFixed(v<10?1:0)+'/s '+q)}return out.join(' · ')}
function renderRooms(){const root=$('rooms');if(!root)return;root.innerHTML=Object.entries(ROOMS).map(([k,r])=>{const lv=S.rooms[k]||0,locked=S.bunker<r.unlock;return `<article class="room ${locked?'locked':''}"><div class="roomHead"><b>${r.name}</b><span>LV ${lv}</span></div><div class="roomArt ${k}"></div><div class="roomFoot"><span>${locked?'BUNKER '+r.unlock:(lv?roomInfo(k):'EMPTY')}</span><button ${locked?'disabled':''} onclick="buyRoom('${k}')">${lv?'UP '+fmt(roomCost(k)):'BUILD '+fmt(roomCost(k))}</button></div></article>`}).join('');setTimeout(()=>window.AfterlightSpecialRooms?.renderMain?.(),0)}
function renderDrawer(){const active=document.querySelector('#tabs .active'),tab=active?.dataset.tab||'base',body=$('drawerBody');if(!body)return;$('drawerTitle').textContent=tab.toUpperCase();if(tab==='expeditions'){if(window.AfterlightExpeditions?.render)window.AfterlightExpeditions.render(body);else body.innerHTML='<div class="shopCard"><i>☣</i><div><b>LOADING EXPEDITIONS</b></div></div>';return}if(tab==='build'){body.innerHTML=Object.entries(ROOMS).map(([k,r])=>`<div class="shopCard"><i>${r.icon}</i><div><b>${r.name} LV ${S.rooms[k]}</b><small>${r.desc}</small></div><button onclick="buyRoom('${k}')">${fmt(roomCost(k))} ◉</button></div>`).join('');setTimeout(()=>window.AfterlightSpecialRooms?.renderBuild?.(),0)}else if(tab==='research')body.innerHTML=RESEARCH.map(r=>`<div class="shopCard"><i>${r.icon}</i><div><b>${r.name}</b><small>${r.desc}</small></div></div>`).join('');else if(tab==='stats')body.innerHTML=`<div class="shopCard"><i>☠</i><div><b>${S.kills} INFECTED KILLED</b><small>${S.stats.bosses||0} BRUTES · ${S.stats.clicks||0} SHOTS</small></div></div>`;else body.innerHTML='<div class="shopCard"><i>☢</i><div><b>AFTERLIGHT PROTOCOL</b></div></div>'}
function hud(){if(!enemy)return;const r=rates(),set=(id,v)=>{const e=$(id);if(e)e.textContent=v};set('coins',fmt(S.coins));set('cps','+'+r.coins.toFixed(1)+'/s');set('food',fmt(S.food));set('foodps','+'+r.food.toFixed(1)+'/s');set('water',fmt(S.water));set('waterps','+'+r.water.toFixed(1)+'/s');set('power',fmt(S.power));set('powerps','+'+r.power.toFixed(1)+'/s');set('scrap',fmt(S.scrap));set('science',fmt(S.science));set('scienceps','+'+r.science.toFixed(1)+'/s');set('bunkerLevel','LEVEL '+S.bunker);set('enemyType',enemy.name);set('enemyLevel',enemy.boss?'BRUTE MUTATION':'MUTATION '+(1+Math.floor(S.kills/10)));set('enemyReward','REWARD '+fmt(enemy.reward));const hp=$('enemyHp');if(hp)hp.style.width=Math.max(0,enemy.hp/enemy.max*100)+'%';set('clickValue','+'+fmt(tapDamage())+' DAMAGE')}
function economyTick(now=performance.now()){const dt=Math.min(.25,Math.max(0,(now-lastTick)/1000));lastTick=now;const r=rates();for(const q of ['coins','food','water','power','scrap','science'])S[q]+=r[q]*dt;S.total=(S.total||0)+r.coins*dt;hud()}
const tapButton=$('clickCore'),scene=$('scene');tapButton?.addEventListener('pointerdown',e=>{e.preventDefault();attack()});scene?.addEventListener('pointerdown',e=>{if(e.target.closest?.('#clickCore,#enemyCard'))return;attack()});
document.querySelectorAll('#tabs button').forEach(button=>button.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.getElementById('missionBox')?.classList.remove('open');if(button.dataset.tab==='base')$('drawer').classList.add('hidden');else if(button.dataset.tab){$('drawer').classList.remove('hidden');renderDrawer()}});$('closeDrawer').onclick=()=>$('drawer').classList.add('hidden');
recalc();spawn();renderRooms();hud();setInterval(()=>economyTick(),100);
window.renderGameDrawer=renderDrawer;window.AfterlightGame={renderRooms,renderDrawer,rates,recalc,hud,attack,enemy:()=>enemy?{...enemy}:null};
})();