(()=>{'use strict';
const $=id=>document.getElementById(id),C=$('combatCanvas'),G=C.getContext('2d');G.imageSmoothingEnabled=false;
const ROOMS={generator:{name:'POWER GENERATOR',icon:'⚡',base:55,unlock:1,prod:{power:1.2,coins:.45},desc:'A patched diesel generator keeps the lights warm.'},workshop:{name:'WORKSHOP',icon:'🔧',base:85,unlock:1,prod:{scrap:.3,coins:1.4},desc:'Turns salvage into useful parts and trade goods.'},greenhouse:{name:'GREENHOUSE',icon:'🌱',base:175,unlock:2,prod:{food:1.1,coins:2.6},desc:'Hydroponics, grow lights and actual green life.'},purifier:{name:'WATER PURIFIER',icon:'💧',base:340,unlock:3,prod:{water:1.2,coins:4.2},desc:'Filters wasteland water into something drinkable.'},lab:{name:'RESEARCH LAB',icon:'⚗',base:690,unlock:4,prod:{science:.13},desc:'Recovered tech becomes permanent research.'},living:{name:'LIVING QUARTERS',icon:'🛏',base:1100,unlock:5,prod:{coins:9.5},desc:'Cozy beds attract more scavengers and workers.'},storage:{name:'STORAGE',icon:'📦',base:1800,unlock:6,prod:{scrap:.7,coins:13},desc:'Organized stockpiles improve your economy.'},turret:{name:'AUTO TURRET',icon:'⌖',base:2900,unlock:7,prod:{coins:18},desc:'Automates combat and claims zombie bounties.'}};
const RESEARCH=[['tools','🔧','BETTER TOOLS','+35% manual damage per level',4],['solar','☀','MICROGRID','+12% all room output per level',6],['hydro','🌿','HYDROPONICS','+25% food output per level',7],['filters','💧','DEEP FILTRATION','+25% water output per level',8],['automation','🤖','TARGETING AI','Turrets fire faster and harder',10],['botany','🌾','SEED BANK','+30% crop harvest per level',11],['walls','🧱','BOUNTY NETWORK','+15% zombie bounty per level',13]];
const CROPS=[{id:'potato',name:'POTATOES',icon:'🥔',time:25,yield:30,unlock:2},{id:'tomato',name:'TOMATOES',icon:'🍅',time:55,yield:80,unlock:3},{id:'corn',name:'CORN',icon:'🌽',time:110,yield:210,unlock:5},{id:'herb',name:'HERBS',icon:'🌿',time:220,yield:600,unlock:7}];
const ZOMBIES=[['WALKER','#65704b','#3f4936'],['RUNNER','#747342','#45452d'],['BLOATER','#6f7050','#4b4b3c'],['BRUTE','#78604d','#49382f'],['ABOMINATION','#785343','#4d302b'],['COLOSSUS','#6b4a42','#3b2928']];
const DEF=()=>({version:2,coins:0,total:0,food:0,water:0,power:0,scrap:0,science:0,kills:0,level:1,xp:0,nextXp:22,bunker:1,rooms:{generator:1,workshop:0,greenhouse:0,purifier:0,lab:0,living:0,storage:0,turret:0},research:{tools:0,solar:0,hydro:0,filters:0,automation:0,botany:0,walls:0},plots:[null,null,null],stats:{clicks:0,bosses:0,harvests:0},last:Date.now(),muted:false});
let S=DEF();try{const old=JSON.parse(localStorage.afterlight_v2clean||localStorage.afterlight_v3||'null');if(old)S={...S,...old,rooms:{...S.rooms,...old.rooms},research:{...S.research,...old.research},plots:old.plots||S.plots,stats:{...S.stats,...old.stats}}}catch{}
let E=null,last=performance.now(),autoTimer=0,audio=null,muzzle=0,screenShake=0,hitKick=0,walk=0,particles=[],floaters=[],uiTimer=0;
const fmt=n=>n<1000?Math.floor(n)+'':n<1e6?(n/1e3).toFixed(n<1e4?1:0)+'K':n<1e9?(n/1e6).toFixed(1)+'M':n<1e12?(n/1e9).toFixed(1)+'B':(n/1e12).toFixed(1)+'T';
const levelMult=()=>1+(S.level-1)*.028;
const globalMult=()=>1+S.research.solar*.12+Math.max(0,S.bunker-1)*.025;
const rate=(k,r)=>{let lv=S.rooms[k]||0,v=(ROOMS[k].prod[r]||0)*lv*Math.pow(1.19,Math.max(0,lv-1))*globalMult();if(r==='food')v*=1+S.research.hydro*.25;if(r==='water')v*=1+S.research.filters*.25;return v};
const rates=()=>{let o={coins:.1,food:0,water:0,power:0,scrap:0,science:0};Object.keys(ROOMS).forEach(k=>Object.keys(o).forEach(r=>o[r]+=rate(k,r)));return o};
const tier=()=>Math.min(5,Math.floor(S.kills/12));
const isBoss=()=>S.kills>0&&S.kills%12===11;
const manualDamage=()=>Math.max(1,(1+Math.floor(S.kills/7))*(1+S.research.tools*.35)*levelMult());
const enemyHp=()=>Math.floor(7*Math.pow(1.145,S.kills)*(1+tier()*.24)*(isBoss()?4.3:1));
const enemyReward=()=>Math.floor((7+S.kills*1.25)*Math.pow(1.068,S.kills)*(1+S.research.walls*.15)*(isBoss()?6:1));
const enemyScale=()=>Math.min(2.35,.82+tier()*.17+(isBoss()?.32:0));
const roomCost=k=>Math.floor(ROOMS[k].base*Math.pow(1.66,S.rooms[k]||0));
function initAudio(){if(audio||S.muted)return;try{audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}catch{}}
function tone(f,d=.045,v=.025,type='square',delay=0){if(!audio||S.muted)return;let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+d+.02)}
function sfx(k){if(k==='tap'){tone(180,.035,.025);tone(92,.05,.012,'sawtooth',.008)}if(k==='kill'){tone(620,.05,.025);tone(900,.06,.018,'square',.035)}if(k==='build'){[360,510,690].forEach((n,i)=>tone(n,.07,.022,'square',i*.04))}if(k==='boss'){[180,135,95].forEach((n,i)=>tone(n,.1,.03,'sawtooth',i*.055))}}
function toast(t){let q=$('toast');q.textContent=t;q.style.opacity=1;clearTimeout(toast.t);toast.t=setTimeout(()=>q.style.opacity=0,900)}
function pop(t,x,y,c='#fff',size=11){floaters.push({t,x,y,c,size,life:.72,max:.72})}
function burst(x,y,c,n=7){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*160,vy:-Math.random()*115-15,life:.5+Math.random()*.25,max:.75,c,size:2+Math.random()*3})}
function addCoins(v){S.coins+=v;S.total+=v}
function gainXp(v){S.xp+=v;while(S.xp>=S.nextXp){S.xp-=S.nextXp;S.level++;S.nextXp=Math.floor(S.nextXp*1.28+8);if(S.level%4===0)S.science++;toast('SURVIVOR LEVEL '+S.level);sfx('build')}}
function spawn(){let hp=enemyHp();E={hp,max:hp,reward:enemyReward(),tier:tier(),boss:isBoss(),flash:0,dead:false,scale:enemyScale(),x:492,y:380};syncCombat()}
spawn();
function attack(auto=false){if(!E||E.dead)return;initAudio();let d=auto?Math.max(1,S.rooms.turret*(1.45+S.research.automation*.42)):manualDamage();if(!auto){S.stats.clicks++;const instant=Math.max(.4,d*.35);addCoins(instant);pop('+'+fmt(instant)+' ◉',190,390,'#f4c65a',10);const b=$('tapButton');b.classList.remove('pressed');void b.offsetWidth;b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),110);if(navigator.vibrate)navigator.vibrate(8)}E.hp-=d;E.flash=.09;muzzle=.08;hitKick=.11;screenShake=auto?1.5:4;pop('-'+fmt(d),E.x,E.y-100,auto?'#ffd063':'#fff',auto?9:12);burst(E.x-12,E.y-45,E.tier>=3?'#7c322b':'#a84a39',auto?4:8);sfx('tap');if(E.hp<=0)kill();syncCombat()}
function kill(){E.dead=true;let reward=E.reward;addCoins(reward);S.scrap+=Math.max(1,Math.floor(reward*.05));S.kills++;gainXp(4+Math.floor(S.kills/6));pop('+'+fmt(reward)+' BOUNTY',E.x,E.y-125,'#f0c04d',12);burst(E.x,E.y-30,'#d8ad38',14);if(E.boss){S.stats.bosses++;S.science+=2+tier();toast('MUTATION BOSS DOWN');sfx('boss')}else sfx('kill');setTimeout(spawn,E.boss?950:420)}
function recalcBunker(){S.bunker=1+Math.floor(Object.values(S.rooms).reduce((a,b)=>a+b,0)/4)}
window.buyRoom=k=>{const r=ROOMS[k],cost=roomCost(k);if(S.bunker<r.unlock)return toast('BUNKER LV '+r.unlock+' REQUIRED');if(S.coins<cost)return toast('NEED '+fmt(cost)+' COINS');S.coins-=cost;S.rooms[k]++;recalcBunker();sfx('build');toast(r.name+' LV '+S.rooms[k]);renderRooms();renderDrawer();syncUI()};
window.research=k=>{const d=RESEARCH.find(a=>a[0]===k),cost=d[4]+S.research[k]*Math.ceil(d[4]*.75);if(S.science<cost)return toast('NEED '+cost+' SCIENCE');S.science-=cost;S.research[k]++;sfx('build');toast(d[2]+' LV '+S.research[k]);renderDrawer();syncUI()};
window.plant=(slot,id)=>{const c=CROPS.find(q=>q.id===id);if(S.bunker<c.unlock)return toast('BUNKER LV '+c.unlock+' REQUIRED');if(S.plots[slot])return;S.plots[slot]={id,start:Date.now(),end:Date.now()+c.time*1000};renderDrawer()};
window.harvest=i=>{let p=S.plots[i];if(!p||Date.now()<p.end)return;let c=CROPS.find(q=>q.id===p.id),v=c.yield*(1+S.research.botany*.3);S.food+=v;S.stats.harvests++;S.plots[i]=null;sfx('kill');toast('HARVEST +'+fmt(v)+' FOOD');renderDrawer();syncUI()};
function renderRooms(){let out='';Object.entries(ROOMS).forEach(([k,r])=>{let lv=S.rooms[k],locked=S.bunker<r.unlock,parts=[];Object.keys(r.prod).forEach(q=>{let v=rate(k,q);if(v>0)parts.push('+'+fmt(v)+'/s '+q)});out+=`<article class="room ${locked?'locked':''}"><div class=roomHead><b>${r.name}</b><span>LV ${lv}</span></div><div class="roomArt ${k}"></div><div class=roomFoot><span>${locked?'BUNKER '+r.unlock:lv?parts.join(' · '):'EMPTY'}</span><button ${locked?'disabled':''} onclick="buyRoom('${k}')">${lv?'UP '+fmt(roomCost(k)):'BUILD '+fmt(roomCost(k))}</button></div></article>`});$('roomGrid').innerHTML=out}
function gardenHtml(){let p=S.plots.map((v,i)=>{if(!v)return `<div class=plot><b>EMPTY GROW BED ${i+1}</b><small>Choose a crop below.</small></div>`;let c=CROPS.find(q=>q.id===v.id),left=Math.max(0,Math.ceil((v.end-Date.now())/1000)),pc=Math.min(100,100*(Date.now()-v.start)/(v.end-v.start));return `<div class=plot><b>${c.icon} ${c.name}</b><small>${left?left+'s remaining':'READY TO HARVEST'}</small><div class=growbar><i style="width:${pc}%"></i></div><button ${left?'disabled':''} onclick="harvest(${i})">${left?'GROWING':'HARVEST'}</button></div>`}).join('');let empty=S.plots.findIndex(v=>!v);return p+CROPS.map(c=>`<div class=shopCard><i>${c.icon}</i><div><b>${c.name}</b><small>${c.time}s grow • +${c.yield} food • bunker ${c.unlock}</small></div><button ${empty<0||S.bunker<c.unlock?'disabled':''} onclick="plant(${Math.max(0,empty)},'${c.id}')">PLANT</button></div>`).join('')}
function renderDrawer(){let tab=document.querySelector('#tabs .active')?.dataset.tab||'base',b=$('drawerBody');$('drawerTitle').textContent=tab.toUpperCase();if(tab==='build')b.innerHTML=Object.entries(ROOMS).map(([k,r])=>`<div class=shopCard><i>${r.icon}</i><div><b>${r.name} LV ${S.rooms[k]}</b><small>${r.desc}<br>${S.bunker<r.unlock?'Requires bunker '+r.unlock:'Next '+fmt(roomCost(k))+' coins'}</small></div><button ${S.bunker<r.unlock||S.coins<roomCost(k)?'disabled':''} onclick="buyRoom('${k}')">${fmt(roomCost(k))}</button></div>`).join('');else if(tab==='research')b.innerHTML=RESEARCH.map(([k,ic,n,d,p])=>{let cost=p+S.research[k]*Math.ceil(p*.75);return `<div class=shopCard><i>${ic}</i><div><b>${n} LV ${S.research[k]}</b><small>${d}</small></div><button ${S.science<cost?'disabled':''} onclick="research('${k}')">${cost} ✦</button></div>`}).join('');else if(tab==='garden')b.innerHTML=gardenHtml();else if(tab==='stats'){let r=rates();b.innerHTML=`<div class=shopCard><i>☠</i><div><b>${S.kills} INFECTED KILLED</b><small>${S.stats.bosses} mutation bosses • ${fmt(S.total)} lifetime coins</small></div></div><div class=shopCard><i>⌂</i><div><b>BUNKER LEVEL ${S.bunker}</b><small>${fmt(r.coins)}/s coins • ${fmt(r.food)}/s food • ${fmt(r.water)}/s water</small></div></div><div class=shopCard><i>👆</i><div><b>${S.stats.clicks} MANUAL TAPS</b><small>${S.stats.harvests} harvests • survivor level ${S.level}</small></div></div>`}else b.innerHTML=''}
function syncCombat(){if(!E)return;let z=ZOMBIES[E.tier];$('enemyType').textContent=(E.boss?'BOSS ':'')+z[0];$('enemyTier').textContent='MUTATION '+(E.tier+1)+(E.boss?' • ELITE':'');$('enemyReward').textContent='BOUNTY '+fmt(E.reward)+' ◉';$('enemyHpText').textContent=fmt(Math.max(0,E.hp))+' / '+fmt(E.max)+' HP';$('enemyHp').style.width=Math.max(0,E.hp/E.max*100)+'%';$('tapValue').textContent='+'+fmt(manualDamage())}
function syncUI(){let r=rates();$('coins').textContent=fmt(S.coins);$('cps').textContent='+'+fmt(r.coins)+'/s';$('food').textContent=fmt(S.food);$('foodps').textContent='+'+fmt(r.food)+'/s';$('water').textContent=fmt(S.water);$('waterps').textContent='+'+fmt(r.water)+'/s';$('power').textContent=fmt(S.power);$('powerps').textContent='+'+fmt(r.power)+'/s';$('scrap').textContent=fmt(S.scrap);$('science').textContent=fmt(S.science);$('scienceps').textContent='+'+fmt(r.science)+'/s';$('bunkerLevel').textContent='BUNKER '+S.bunker;$('survivorLevel').textContent='SURVIVOR '+S.level;$('killCount').textContent=S.kills+' CLEARED';syncCombat()}
function px(a,b,w,h,c){G.fillStyle=c;G.fillRect(Math.round(a),Math.round(b),Math.round(w),Math.round(h))}
function city(){G.fillStyle='#1b1c19';for(let i=0;i<16;i++){let w=20+(i%4)*7,h=38+(i%6)*18,xx=i*47-25;px(xx,225-h,w,h,'#1c1d1a');for(let y=232-h;y<215;y+=14)if((i+y)%3)px(xx+6,y,3,4,'#7b4b2a')}G.fillStyle='#27271f';G.beginPath();G.moveTo(0,260);for(let i=0;i<10;i++){G.lineTo(i*70,195+(i%3)*20);G.lineTo(i*70+55,260)}G.lineTo(640,260);G.fill()}
function drawSurvivor(t){let x=118,y=390+Math.sin(t*8)*1.5,step=Math.floor(t*7)%2;px(x-12,y-50,22,29,'#293027');px(x-8,y-69,18,20,'#c49874');px(x-12,y-75,25,9,'#34271f');px(x-18,y-46,8,25,'#526343');px(x-10,y-20,7,21-step*3,'#242925');px(x+5,y-20+step*2,7,21-step*2,'#242925');px(x-17,y-34,11,7,'#3c4d3c');px(x+8,y-44,12,7,'#b98663');G.save();G.translate(x+14,y-39);G.rotate(muzzle>0?-.1:.015);px(0,-4,41,8,'#343a35');px(30,-2,27,4,'#74796d');px(8,4,8,8,'#553d29');G.restore();if(muzzle>0){G.fillStyle='#ffd36b';G.beginPath();G.moveTo(x+72,y-42);G.lineTo(x+88,y-48);G.lineTo(x+82,y-40);G.lineTo(x+91,y-35);G.lineTo(x+73,y-38);G.fill()}}
function drawZombie(t){if(!E||E.dead)return;let z=ZOMBIES[E.tier],s=E.scale*(1+Math.sin(t*3.2)*.007),x=E.x+(hitKick>0?8:0),y=E.y;G.save();G.translate(x,y);G.scale(s,s);let skin=E.flash>0?'#e7dfc5':z[1],cloth=z[2];px(-14,-61,28,28,skin);px(-18,-34,36,40,cloth);px(-11,5,9,31,'#31352d');px(4,5,9,31,'#2c302a');px(-23,-29,8,36,skin);px(16,-27,8,39,skin);px(-8,-52,5,5,'#e45d43');px(5,-52,5,5,'#e45d43');px(-7,-42,15,4,'#2c241e');px(-11,-65,9,7,'#393a2d');if(E.tier>=1){px(-22,-38,10,8,'#55372e');px(14,-43,10,8,'#5b392f')}if(E.tier>=2){px(-27,-20,9,16,'#785039');px(18,-18,10,17,'#724b36');px(-8,-10,16,10,'#6b6f45')}if(E.tier>=3){px(-25,-52,10,14,'#704438');px(16,-57,10,16,'#704438');px(-20,-70,10,9,'#574033')}if(E.tier>=4){px(-29,-72,11,11,'#8b4d37');px(19,-75,12,11,'#8b4d37');px(-7,-76,14,9,'#614231')}if(E.boss){G.strokeStyle='#e9683e';G.lineWidth=3;G.strokeRect(-34,-84,68,123)}G.restore()}
function drawScene(t){let sx=screenShake>0?(Math.random()-.5)*screenShake:0,sy=screenShake>0?(Math.random()-.5)*screenShake:0;G.save();G.translate(sx,sy);let grad=G.createLinearGradient(0,0,0,430);grad.addColorStop(0,'#9d4d31');grad.addColorStop(.38,'#5e382a');grad.addColorStop(1,'#26261f');G.fillStyle=grad;G.fillRect(0,0,640,500);G.fillStyle='#d88547';G.beginPath();G.arc(510,112,47,0,7);G.fill();city();px(0,342,640,10,'#544832');px(0,352,640,148,'#24251e');for(let i=0;i<28;i++)px((i*31+(t*3)%31)-20,361+(i%4)*6,18,3,'#34362c');px(38,286,63,58,'#352c22');px(46,271,46,18,'#443327');px(67,249,5,25,'#27231e');px(55,305,16,10,'#b25e2f');drawSurvivor(t);drawZombie(t);for(let p of particles){G.globalAlpha=Math.max(0,p.life/p.max);px(p.x,p.y,p.size,p.size,p.c)}G.globalAlpha=1;G.textAlign='center';for(let f of floaters){G.globalAlpha=Math.max(0,f.life/f.max);G.fillStyle=f.c;G.font='900 '+f.size+'px monospace';G.fillText(f.t,f.x,f.y)}G.globalAlpha=1;G.textAlign='left';G.restore()}
function save(){S.last=Date.now();try{localStorage.afterlight_v2clean=JSON.stringify(S)}catch{}}
$('tapButton').addEventListener('pointerdown',e=>{e.preventDefault();attack(false)});C.addEventListener('pointerdown',e=>{e.preventDefault();let r=C.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width*640,my=(e.clientY-r.top)/r.height*500;if(mx>330&&my>210)attack(false)});$('closeDrawer').onclick=()=>$('drawer').classList.add('hidden');document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(q=>q.classList.remove('active'));b.classList.add('active');if(b.dataset.tab==='base')$('drawer').classList.add('hidden');else{$('drawer').classList.remove('hidden');renderDrawer()}});document.addEventListener('pointerdown',initAudio,{once:true});
let away=Math.min(8*3600,Math.max(0,(Date.now()-(S.last||Date.now()))/1000));if(away>45){let r=rates(),gain=r.coins*away*.7;addCoins(gain);S.food+=r.food*away*.7;S.water+=r.water*away*.7;S.power+=r.power*away*.7;S.scrap+=r.scrap*away*.7;S.science+=r.science*away*.7;$('offlineText').textContent='Your bunker worked for '+Math.floor(away/60)+' minutes.';$('offlineGain').textContent='+'+fmt(gain)+' COINS';$('offline').classList.remove('hidden')}$('offlineCollect').onclick=()=>{$('offline').classList.add('hidden');sfx('kill')};
setInterval(save,4000);addEventListener('pagehide',save);
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now,walk+=dt;let r=rates();addCoins(r.coins*dt);S.food+=r.food*dt;S.water+=r.water*dt;S.power+=r.power*dt;S.scrap+=r.scrap*dt;S.science+=r.science*dt;muzzle=Math.max(0,muzzle-dt);hitKick=Math.max(0,hitKick-dt);screenShake=Math.max(0,screenShake-dt*28);if(E&&E.flash>0)E.flash-=dt;autoTimer-=dt;if(S.rooms.turret>0&&E&&!E.dead&&autoTimer<=0){attack(true);autoTimer=Math.max(.2,1.15/(1+S.rooms.turret*.08+S.research.automation*.12))}for(let p of particles){p.life-=dt;p.vy+=220*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}particles=particles.filter(p=>p.life>0);for(let f of floaters){f.life-=dt;f.y-=28*dt}floaters=floaters.filter(f=>f.life>0);drawScene(now/1000);uiTimer-=dt;if(uiTimer<=0){syncUI();uiTimer=.12}requestAnimationFrame(loop)}
renderRooms();syncUI();requestAnimationFrame(loop);
})();