(()=>{'use strict';
const $=id=>document.getElementById(id),C=$('game'),G=C.getContext('2d');G.imageSmoothingEnabled=false;
const ROOMS={generator:{name:'POWER GENERATOR',icon:'⚡',base:35,unlock:1,prod:{power:1.5,coins:.4},desc:'Keeps the bunker alive and sells spare charge.'},workshop:{name:'WORKSHOP',icon:'⚙',base:85,unlock:1,prod:{scrap:.32,coins:1.8},desc:'Turns salvage into parts and trade goods.'},greenhouse:{name:'GREENHOUSE',icon:'🌱',base:190,unlock:2,prod:{food:1.2,coins:2.8},desc:'Fresh food, herbs and comfort underground.'},purifier:{name:'WATER PURIFIER',icon:'💧',base:420,unlock:3,prod:{water:1.35,coins:4.2},desc:'Produces clean water automatically.'},lab:{name:'RESEARCH LAB',icon:'⚗',base:850,unlock:4,prod:{science:.14,coins:5},desc:'Generates science for permanent upgrades.'},living:{name:'LIVING QUARTERS',icon:'🛏',base:1350,unlock:5,prod:{coins:11},desc:'More survivors means more scavenging crews.'},storage:{name:'STORAGE',icon:'📦',base:2200,unlock:6,prod:{coins:17,scrap:.5},desc:'Organized stockpiles increase output.'},turret:{name:'AUTO TURRET',icon:'⌖',base:3600,unlock:7,prod:{coins:12},desc:'Automatically damages infected at the gate.'}};
const RESEARCH=[['tools','🔧','BETTER TOOLS','+30% manual damage',4],['solar','☀','MICROGRID','+12% room production',6],['hydro','🌿','HYDROPONICS','+20% food production',7],['filters','💧','FILTRATION','+20% water production',8],['automation','🤖','AUTOMATION AI','Improves turret damage',10],['walls','🧱','REINFORCED WALLS','+15% zombie bounty',13]];
const DEF=()=>({coins:0,total:0,food:0,water:0,power:0,scrap:0,science:0,kills:0,level:1,bunker:1,rooms:{generator:1,workshop:0,greenhouse:0,purifier:0,lab:0,living:0,storage:0,turret:0},research:{tools:0,solar:0,hydro:0,filters:0,automation:0,walls:0},stats:{clicks:0,bosses:0},last:Date.now()});
let S=DEF();try{const o=JSON.parse(localStorage.afterlight_v4||localStorage.afterlight_v3||'null');if(o)S={...S,...o,rooms:{...S.rooms,...o.rooms},research:{...S.research,...o.research},stats:{...S.stats,...o.stats}}}catch{}
let E=null,last=performance.now(),turretT=0,flash=0,muzzle=0,floaters=[],particles=[];
const fmt=n=>n<1000?Math.floor(n)+'':n<1e6?(n/1e3).toFixed(1)+'K':n<1e9?(n/1e6).toFixed(1)+'M':(n/1e9).toFixed(1)+'B';
const roomCost=k=>Math.floor(ROOMS[k].base*Math.pow(1.62,S.rooms[k]||0));
const mult=()=>1+S.research.solar*.12;
const rate=(k,r)=>{let lv=S.rooms[k]||0,v=(ROOMS[k].prod[r]||0)*lv*Math.pow(1.18,Math.max(0,lv-1))*mult();if(r==='food')v*=1+S.research.hydro*.2;if(r==='water')v*=1+S.research.filters*.2;return v};
const rates=()=>{let r={coins:.1,food:0,water:0,power:0,scrap:0,science:0};for(const k in ROOMS)for(const q in r)r[q]+=rate(k,q);return r};
const tap=()=>Math.max(1,(1+Math.floor(S.kills/7))*(1+S.research.tools*.3));
const boss=()=>S.kills>0&&S.kills%10===9;
const enemyHp=()=>Math.floor(9*Math.pow(1.17,S.kills)*(boss()?4:1));
const enemyReward=()=>Math.floor((6+S.kills*1.4)*Math.pow(1.075,S.kills)*(boss()?7:1)*(1+S.research.walls*.15));
function spawn(){E={hp:enemyHp(),max:enemyHp(),reward:enemyReward(),boss:boss(),name:boss()?'BRUTE':'WALKER',dead:false};hud()};spawn();
function save(){S.last=Date.now();localStorage.afterlight_v4=JSON.stringify(S)}setInterval(save,4000);
function toast(t){const e=$('toast');e.textContent=t;e.style.opacity=1;clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.opacity=0,800)}
function addFloat(t,x,y,c='#fff'){floaters.push({t,x,y,c,l:.8})}
function kill(){if(E.dead)return;E.dead=true;S.kills++;if(E.boss){S.stats.bosses++;S.science+=2;toast('BRUTE DOWN +2 SCIENCE')}S.coins+=E.reward;S.total+=E.reward;S.scrap+=Math.max(1,Math.floor(E.reward*.05));addFloat('+'+fmt(E.reward)+' COINS',360,205,'#f1c24f');for(let i=0;i<15;i++)particles.push({x:365,y:240,vx:(Math.random()-.5)*130,vy:-Math.random()*120,l:.65,c:i%3?'#943d32':'#e2b548'});setTimeout(spawn,E.boss?700:300)}
function attack(auto=false){if(!E||E.dead)return;let d=auto?Math.max(1,S.rooms.turret*(1.6+S.research.automation*.5)):tap();if(!auto){S.stats.clicks++;S.coins+=Math.max(.25,d*.35);S.total+=Math.max(.25,d*.35)}E.hp-=d;flash=.12;muzzle=.1;addFloat('-'+fmt(d),360+(Math.random()-.5)*12,190,'#fff');for(let i=0;i<5;i++)particles.push({x:360,y:225,vx:(Math.random()-.5)*90,vy:(Math.random()-.5)*70,l:.3,c:'#b04a39'});if(E.hp<=0)kill();hud()}
function recalc(){S.bunker=1+Math.floor(Object.values(S.rooms).reduce((a,b)=>a+b,0)/4)}
window.buyRoom=k=>{const c=roomCost(k),r=ROOMS[k];if(S.bunker<r.unlock)return toast('BUNKER LV '+r.unlock+' REQUIRED');if(S.coins<c)return toast('NEED '+fmt(c)+' COINS');S.coins-=c;S.rooms[k]++;recalc();toast(r.name+' LV '+S.rooms[k]);renderRooms();renderDrawer();hud()};
window.research=k=>{const d=RESEARCH.find(x=>x[0]===k),c=d[4]+S.research[k]*d[4];if(S.science<c)return toast('NEED '+c+' SCIENCE');S.science-=c;S.research[k]++;toast(d[2]+' LV '+S.research[k]);renderDrawer();hud()};
function roomInfo(k){const out=[];for(const q of ['coins','power','food','water','scrap','science']){const v=rate(k,q);if(v>0)out.push('+'+v.toFixed(v<10?1:0)+'/s '+q)}return out.join(' · ')}
function renderRooms(){$('rooms').innerHTML=Object.entries(ROOMS).map(([k,r])=>{const lv=S.rooms[k],locked=S.bunker<r.unlock;return `<article class="room ${locked?'locked':''}"><div class=roomHead><b>${r.name}</b><span>LV ${lv}</span></div><div class="roomArt ${k}"></div><div class=roomFoot><span>${locked?'BUNKER '+r.unlock:(lv?roomInfo(k):'EMPTY')}</span><button ${locked?'disabled':''} onclick="buyRoom('${k}')">${lv?'UP '+fmt(roomCost(k)):'BUILD '+fmt(roomCost(k))}</button></div></article>`}).join('')}
function renderDrawer(){const tab=document.querySelector('#tabs .active')?.dataset.tab||'base',b=$('drawerBody');$('drawerTitle').textContent=tab.toUpperCase();if(tab==='build')b.innerHTML=Object.entries(ROOMS).map(([k,r])=>`<div class=shopCard><i>${r.icon}</i><div><b>${r.name} LV ${S.rooms[k]}</b><small>${r.desc}<br>${roomInfo(k)||'No output yet'}</small></div><button onclick="buyRoom('${k}')">${fmt(roomCost(k))} ◉</button></div>`).join('');else if(tab==='research')b.innerHTML=RESEARCH.map(d=>{const c=d[4]+S.research[d[0]]*d[4];return `<div class=shopCard><i>${d[1]}</i><div><b>${d[2]} LV ${S.research[d[0]]}</b><small>${d[3]}</small></div><button onclick="research('${d[0]}')">${c} ✦</button></div>`}).join('');else if(tab==='stats'){const r=rates();b.innerHTML=`<div class=shopCard><i>☠</i><div><b>${S.kills} INFECTED KILLED</b><small>${S.stats.bosses} brutes · ${fmt(S.total)} lifetime coins</small></div></div><div class=shopCard><i>⚙</i><div><b>AUTOMATION</b><small>${r.coins.toFixed(1)} coins/s · ${r.power.toFixed(1)} power/s · ${r.food.toFixed(1)} food/s · ${r.water.toFixed(1)} water/s</small></div></div>`}else if(tab==='garden')b.innerHTML='<div class=shopCard><i>🌱</i><div><b>GARDEN EXPANSION</b><small>Crop plots return in Phase 2 after the core economy is stable.</small></div></div>';else b.innerHTML='<div class=shopCard><i>☢</i><div><b>AFTERLIGHT PROTOCOL</b><small>Tap the infected. Build rooms. Every room produces resources automatically every second.</small></div></div>'}
function hud(){const r=rates();$('coins').textContent=fmt(S.coins);$('cps').textContent='+'+r.coins.toFixed(1)+'/s';$('food').textContent=fmt(S.food);$('foodps').textContent='+'+r.food.toFixed(1)+'/s';$('water').textContent=fmt(S.water);$('waterps').textContent='+'+r.water.toFixed(1)+'/s';$('power').textContent=fmt(S.power);$('powerps').textContent='+'+r.power.toFixed(1)+'/s';$('scrap').textContent=fmt(S.scrap);$('science').textContent=fmt(S.science);$('scienceps').textContent='+'+r.science.toFixed(1)+'/s';$('bunkerLevel').textContent='LEVEL '+S.bunker;$('enemyType').textContent=E?.name||'WALKER';$('enemyLevel').textContent=E?.boss?'BRUTE MUTATION':'MUTATION '+(1+Math.floor(S.kills/10));$('enemyReward').textContent='REWARD '+fmt(E?.reward||0);$('enemyHp').style.width=(E?Math.max(0,E.hp/E.max*100):0)+'%';$('clickValue').textContent='+'+fmt(tap())+' DAMAGE'}
function px(x,y,w,h,c){G.fillStyle=c;G.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function drawSurvivor(t){const bob=Math.sin(t*6)*2,x=95,y=335+bob;px(x-10,y-55,20,18,'#d4a06f');px(x-12,y-65,22,11,'#423128');px(x-12,y-37,25,27,'#344d43');px(x-17,y-33,8,20,'#253b34');px(x+9,y-32,22,6,'#a37b53');px(x+27,y-31,38,4,'#777d73');px(x-10,y-10,8,20,'#27302f');px(x+4,y-10,8,20,'#27302f');if(muzzle>0){px(x+64,y-35,13,10,'#ffd25b');px(x+74,y-32,9,4,'#ff8a2b')}}
function drawZombie(t){if(!E||E.dead)return;const sc=E.boss?1.45:1,x=360,y=350+Math.sin(t*4)*3;G.save();G.translate(x,y);G.scale(sc,sc);const skin=flash>0?'#fff':'#61734d';px(-18,-62,36,28,skin);px(-14,-72,28,15,skin);px(-11,-67,5,4,'#dd4838');px(6,-67,5,4,'#dd4838');px(-22,-42,44,35,'#4e5b45');px(-25,-38,9,28,skin);px(16,-38,9,28,skin);px(-15,-8,11,24,'#343c32');px(5,-8,11,24,'#343c32');if(E.boss){px(-27,-49,54,8,'#6a3b31');px(-23,-82,46,8,'#4b302b')}G.restore()}
function draw(t){const sky=G.createLinearGradient(0,0,0,520);sky.addColorStop(0,'#313323');sky.addColorStop(.55,'#6b5141');sky.addColorStop(1,'#2c211b');G.fillStyle=sky;G.fillRect(0,0,480,520);G.fillStyle='#171d19';for(let i=0;i<11;i++){const h=50+(i%4)*28;G.fillRect(i*48-8,250-h,38,h)}px(0,350,480,170,'#171815');px(0,346,480,7,'#66523a');for(let x=0;x<480;x+=42){px(x,365+(x%3)*4,20,5,'#2c2922');px(x+12,380+(x%5)*3,14,4,'#24251f')}drawSurvivor(t);drawZombie(t);for(const p of particles){G.globalAlpha=Math.max(0,p.l/.65);px(p.x,p.y,4,4,p.c)}G.globalAlpha=1;G.textAlign='center';G.font='bold 15px monospace';for(const f of floaters){G.globalAlpha=Math.max(0,f.l/.8);G.fillStyle=f.c;G.fillText(f.t,f.x,f.y)}G.globalAlpha=1;G.textAlign='left'}
function tick(now){const dt=Math.min(.05,(now-last)/1000);last=now;const r=rates();S.coins+=r.coins*dt;S.total+=r.coins*dt;S.food+=r.food*dt;S.water+=r.water*dt;S.power+=r.power*dt;S.scrap+=r.scrap*dt;S.science+=r.science*dt;turretT-=dt;if(S.rooms.turret>0&&turretT<=0){attack(true);turretT=Math.max(.25,1.1-S.rooms.turret*.06)}flash=Math.max(0,flash-dt);muzzle=Math.max(0,muzzle-dt);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.l-=dt;p.vy+=120*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.l<=0)particles.splice(i,1)}for(let i=floaters.length-1;i>=0;i--){const f=floaters[i];f.l-=dt;f.y-=28*dt;if(f.l<=0)floaters.splice(i,1)}draw(now/1000);hud();requestAnimationFrame(tick)}
const tapBtn=$('clickCore');const doTap=e=>{if(e?.cancelable)e.preventDefault();attack(false)};tapBtn.addEventListener('pointerdown',doTap);tapBtn.addEventListener('touchstart',doTap,{passive:false});C.addEventListener('pointerdown',doTap);document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.tab==='base')$('drawer').classList.add('hidden');else{$('drawer').classList.remove('hidden');renderDrawer()}});$('closeDrawer').onclick=()=>$('drawer').classList.add('hidden');
const away=Math.min(8*3600,Math.max(0,(Date.now()-(S.last||Date.now()))/1000));if(away>60){const r=rates(),eff=.5;S.coins+=r.coins*away*eff;S.total+=r.coins*away*eff;S.food+=r.food*away*eff;S.water+=r.water*away*eff;S.power+=r.power*away*eff;$('offlineText').textContent='The bunker ran for '+Math.floor(away/60)+' minutes.';$('offlineGain').textContent='+'+fmt(r.coins*away*eff)+' coins';$('offline').classList.remove('hidden')}$('offlineCollect').onclick=()=>$('offline').classList.add('hidden');
renderRooms();renderDrawer();hud();requestAnimationFrame(tick);
})();