(()=>{'use strict';
const $=id=>document.getElementById(id),C=$('game'),G=C.getContext('2d');G.imageSmoothingEnabled=false;
const combat=new Image();combat.src='assets/afterlight_sprites.png?v=3';
const ROOMS={
 generator:{name:'POWER GENERATOR',icon:'⚡',base:35,unlock:1,art:'generator',prod:{power:1.8,coins:.6},desc:'Diesel, batteries and a patched microgrid.'},
 workshop:{name:'WORKSHOP',icon:'⚙',base:85,unlock:1,art:'workshop',prod:{scrap:.45,coins:2.8},desc:'Makes parts and trades salvage.'},
 greenhouse:{name:'GREENHOUSE',icon:'🌱',base:190,unlock:2,art:'greenhouse',prod:{food:1.4,coins:4.5},desc:'Warm grow lamps make the bunker feel alive.'},
 purifier:{name:'WATER PURIFIER',icon:'💧',base:420,unlock:3,art:'purifier',prod:{water:1.6,coins:7},desc:'Clean water is worth more than gold outside.'},
 lab:{name:'RESEARCH LAB',icon:'⚗',base:850,unlock:4,art:'lab',prod:{science:.18},desc:'Turns recovered tech into permanent upgrades.'},
 living:{name:'LIVING QUARTERS',icon:'🛏',base:1350,unlock:5,art:'living',prod:{coins:18},desc:'More survivors means more scavenging crews.'},
 storage:{name:'STORAGE',icon:'📦',base:2200,unlock:6,art:'storage',prod:{coins:28,scrap:.8},desc:'Organized stockpiles improve every run.'},
 turret:{name:'AUTO TURRET',icon:'⌖',base:3600,unlock:7,art:'turret',prod:{coins:36},desc:'Automatically shoots infected at the gate.'}
};
const RESEARCH=[['tools','🔧','BETTER TOOLS','+30% tap power per level',4],['solar','☀','SOLAR MICROGRID','+12% all room production per level',6],['hydro','🌿','HYDROPONICS','+20% food production per level',7],['filters','💧','DEEP FILTRATION','+20% water production per level',8],['automation','🤖','AUTOMATION AI','Turrets fire faster and harder',10],['botany','🌾','SEED BANK','+25% crop harvest per level',11],['walls','🧱','REINFORCED WALLS','+15% zombie bounty per level',13]];
const CROPS=[{id:'potato',name:'POTATOES',icon:'🥔',time:35,yield:35,unlock:2},{id:'tomato',name:'TOMATOES',icon:'🍅',time:75,yield:95,unlock:3},{id:'corn',name:'CORN',icon:'🌽',time:150,yield:260,unlock:5},{id:'herb',name:'MEDICINAL HERBS',icon:'🌿',time:300,yield:720,unlock:7}];
const NAMES=['WALKER','RUNNER','BLOATER','BRUTE','ABOMINATION','COLOSSUS'];
const DEF=()=>({coins:0,total:0,food:0,water:0,power:0,scrap:0,science:0,kills:0,level:1,xp:0,nextXp:24,bunker:1,rooms:{generator:1,workshop:0,greenhouse:0,purifier:0,lab:0,living:0,storage:0,turret:0},research:{tools:0,solar:0,hydro:0,filters:0,automation:0,botany:0,walls:0},plots:[null,null,null],stats:{clicks:0,bosses:0,harvests:0},last:Date.now(),muted:false});
let S=DEF();try{let o=JSON.parse(localStorage.afterlight_v3||localStorage.afterlight_v2||'null');if(o)S={...S,...o,rooms:{...S.rooms,...o.rooms},research:{...S.research,...o.research},plots:o.plots||S.plots,stats:{...S.stats,...o.stats}}}catch{}
let E=null,P=[],F=[],last=performance.now(),autoT=0,shot=0,audio=null,dirty=true,gardenT=0,hitPulse=0;
const fmt=n=>n<1e3?Math.floor(n)+'':n<1e6?(n/1e3).toFixed(n<1e4?1:0)+'K':n<1e9?(n/1e6).toFixed(1)+'M':n<1e12?(n/1e9).toFixed(1)+'B':(n/1e12).toFixed(1)+'T';
const roomCost=k=>Math.floor(ROOMS[k].base*Math.pow(1.68,S.rooms[k]||0));
const globalMult=()=>1+S.research.solar*.12+S.bunker*.035;
const roomRate=(k,res)=>{let lv=S.rooms[k]||0,v=(ROOMS[k].prod[res]||0)*lv*Math.pow(1.21,Math.max(0,lv-1))*globalMult();if(res==='food')v*=1+S.research.hydro*.2;if(res==='water')v*=1+S.research.filters*.2;return v};
const rates=()=>{let r={coins:.15,food:0,water:0,power:0,scrap:0,science:0};Object.keys(ROOMS).forEach(k=>Object.keys(r).forEach(q=>r[q]+=roomRate(k,q)));return r};
const tap=()=>Math.max(1,(1+Math.floor(S.kills/6))*(1+S.research.tools*.3));const tier=()=>Math.min(5,Math.floor(S.kills/10));const boss=()=>S.kills>0&&S.kills%10===9;
const eHp=()=>Math.floor(11*Math.pow(1.195,S.kills)*(1+tier()*.2)*(boss()?4.5:1));const eReward=()=>Math.floor((6+S.kills*1.6)*Math.pow(1.082,S.kills)*(boss()?7:1)*(1+S.research.walls*.15));const eScale=()=>Math.min(2.5,.72+tier()*.2+(boss()?.35:0));
function initAudio(){if(audio||S.muted)return;try{audio=new(window.AudioContext||window.webkitAudioContext)()}catch{}}function tone(f,d=.05,v=.025,type='square'){if(!audio||S.muted)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.value=v;g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d+.02)}function sfx(k){if(k==='hit'){tone(190,.035,.03);tone(95,.045,.015,'sawtooth')}if(k==='coin'){tone(660,.05,.02);setTimeout(()=>tone(920,.05,.015),35)}if(k==='up'){[420,620,830].forEach((n,i)=>setTimeout(()=>tone(n,.06,.025),i*40))}if(k==='boss'){[180,140,100].forEach((n,i)=>setTimeout(()=>tone(n,.12,.035,'sawtooth'),i*70))}}
function toast(t){let q=$('toast');q.textContent=t;q.style.opacity=1;clearTimeout(toast.t);toast.t=setTimeout(()=>q.style.opacity=0,900)}function addCoins(n){S.coins+=n;S.total+=n}function gainXp(n){S.xp+=n;while(S.xp>=S.nextXp){S.xp-=S.nextXp;S.level++;S.nextXp=Math.floor(S.nextXp*1.31+10);if(S.level%4===0)S.science+=1+Math.floor(S.level/20);toast('SURVIVOR LEVEL '+S.level);sfx('up')}}
function spawn(){let hp=eHp();E={x:365,y:338,hp,max:hp,reward:eReward(),name:NAMES[tier()],scale:eScale(),dead:false,flash:0,boss:boss()};dirty=true}spawn();
function kill(){E.dead=true;S.kills++;if(E.boss){S.stats.bosses++;S.science+=2+Math.floor(tier()/2);toast('BOSS DOWN + SCIENCE');sfx('boss')}else sfx('coin');let r=E.reward;addCoins(r);S.scrap+=Math.max(1,Math.floor(r*.055));gainXp(4+Math.floor(S.kills/5));F.push({t:'+'+fmt(r)+' COINS',x:E.x,y:E.y-76,l:.9,c:'#f6d15a'});for(let i=0;i<18;i++)P.push({x:E.x,y:E.y-25,vx:(Math.random()-.5)*170,vy:-Math.random()*160,l:.7,c:i%3?'#8c3a30':'#e6b742'});setTimeout(spawn,E.boss?800:330);dirty=true}
function attack(auto=false){if(!E||E.dead)return;if(!auto){initAudio();S.stats.clicks++;addCoins(tap()*.35)}let d=auto?Math.max(1,S.rooms.turret*(1.7+S.research.automation*.45)):tap();E.hp-=d;E.flash=.11;shot=.11;hitPulse=.12;F.push({t:'-'+fmt(d),x:E.x+(Math.random()-.5)*12,y:E.y-60-Math.random()*9,l:.62,c:auto?'#ffd064':'#ffffff'});for(let i=0;i<7;i++)P.push({x:E.x,y:E.y-24,vx:(Math.random()-.5)*125,vy:(Math.random()-.5)*95,l:.34,c:i%2?'#9c4034':'#efb24b'});sfx('hit');if(E.hp<=0)kill();hud()}
function recalc(){S.bunker=1+Math.floor(Object.values(S.rooms).reduce((a,b)=>a+b,0)/4)}
window.buyRoom=k=>{let r=ROOMS[k],c=roomCost(k);if(S.bunker<r.unlock)return toast('BUNKER LV '+r.unlock+' REQUIRED');if(S.coins<c)return toast('NEED '+fmt(c)+' COINS');S.coins-=c;S.rooms[k]++;recalc();sfx('up');toast(r.name+' LV '+S.rooms[k]);dirty=true;renderRooms();renderDrawer()};window.research=k=>{let def=RESEARCH.find(a=>a[0]===k),cost=def[4]+S.research[k]*Math.ceil(def[4]*.7);if(S.science<cost)return toast('NEED '+cost+' SCIENCE');S.science-=cost;S.research[k]++;sfx('up');toast(def[2]+' LV '+S.research[k]);renderDrawer();dirty=true};window.plant=(slot,id)=>{let c=CROPS.find(x=>x.id===id);if(S.bunker<c.unlock)return toast('BUNKER LV '+c.unlock+' REQUIRED');if(S.plots[slot])return;S.plots[slot]={id,start:Date.now(),end:Date.now()+c.time*1000};renderDrawer()};window.harvest=i=>{let p=S.plots[i];if(!p||Date.now()<p.end)return;let c=CROPS.find(x=>x.id===p.id),g=c.yield*(1+S.research.botany*.25);S.food+=g;S.plots[i]=null;S.stats.harvests++;sfx('coin');toast('HARVEST +'+fmt(g)+' FOOD');renderDrawer()};
function renderRooms(){let html='';Object.entries(ROOMS).forEach(([k,r])=>{let lv=S.rooms[k],locked=S.bunker<r.unlock,rs=[];Object.keys(r.prod).forEach(q=>{let v=roomRate(k,q);if(v)rs.push('+'+fmt(v)+'/s '+q)});html+=`<article class="room ${locked?'locked':''}"><div class=roomHead><b>${r.name}</b><span>LV ${lv}</span></div><div class="roomArt ${r.art}"></div><div class=roomFoot><span>${locked?'BUNKER '+r.unlock:lv?rs.join(' · '):'EMPTY'}</span><button ${locked?'disabled':''} onclick="buyRoom('${k}')">${lv?'UP '+fmt(roomCost(k)):'BUILD '+fmt(roomCost(k))}</button></div></article>`});$('rooms').innerHTML=html}
function gardenHTML(){let plots=S.plots.map((p,i)=>{if(!p)return `<div class=plot><b>EMPTY PLOT ${i+1}</b><span class=crop>🪴</span><small>Plant something below.</small></div>`;let c=CROPS.find(x=>x.id===p.id),left=Math.max(0,Math.ceil((p.end-Date.now())/1000)),pct=Math.min(100,100*(Date.now()-p.start)/(p.end-p.start));return `<div class=plot><b>${c.name}</b><span class=crop>${c.icon}</span><small>${left?left+'s remaining':'READY'}</small><div class=growbar><i style="width:${pct}%"></i></div><button ${left?'disabled':''} onclick="harvest(${i})">${left?'GROWING':'HARVEST'}</button></div>`}).join('');let empty=S.plots.findIndex(x=>!x);let crops=CROPS.map(c=>`<div class=shopCard><i>${c.icon}</i><div><b>${c.name}</b><small>${c.time}s grow time · +${c.yield} food · bunker ${c.unlock}</small></div><button ${empty<0||S.bunker<c.unlock?'disabled':''} onclick="plant(${Math.max(0,empty)},'${c.id}')">PLANT</button></div>`).join('');return `<div class=gardenGrid>${plots}</div>${crops}`}
function renderDrawer(){let tab=document.querySelector('#tabs .active')?.dataset.tab||'base';$('drawerTitle').textContent=tab.toUpperCase();let b=$('drawerBody');if(tab==='build')b.innerHTML=Object.entries(ROOMS).map(([k,r])=>`<div class="shopCard ${S.bunker<r.unlock?'locked':''}"><i>${r.icon}</i><div><b>${r.name} LV ${S.rooms[k]}</b><small>${r.desc}<br>${S.bunker<r.unlock?'Requires bunker '+r.unlock:'Cost scales ×1.68 each level'}</small></div><button onclick="buyRoom('${k}')" ${S.bunker<r.unlock||S.coins<roomCost(k)?'disabled':''}>${fmt(roomCost(k))} ◉</button></div>`).join('');else if(tab==='research')b.innerHTML=RESEARCH.map(([k,ic,n,d,p])=>{let cost=p+S.research[k]*Math.ceil(p*.7);return `<div class=shopCard><i>${ic}</i><div><b>${n} LV ${S.research[k]}</b><small>${d}</small></div><button onclick="research('${k}')" ${S.science<cost?'disabled':''}>${cost} ✦</button></div>`}).join('');else if(tab==='garden')b.innerHTML=gardenHTML();else if(tab==='stats'){let r=rates();b.innerHTML=`<div class=shopCard><i>☠</i><div><b>${S.kills} INFECTED KILLED</b><small>${S.stats.bosses} bosses · ${NAMES[tier()]} tier · ${fmt(S.total)} lifetime coins</small></div></div><div class=shopCard><i>⌂</i><div><b>BUNKER LEVEL ${S.bunker}</b><small>${fmt(r.coins)}/s coins · ${fmt(r.food)}/s food · ${fmt(r.water)}/s water · ${fmt(r.power)}/s power</small></div></div><div class=shopCard><i>🌱</i><div><b>${S.stats.harvests} HARVESTS</b><small>${S.stats.clicks} manual taps · survivor Lv ${S.level}</small></div></div>`}else b.innerHTML=`<div class=shopCard><i>☢</i><div><b>AFTERLIGHT PROTOCOL</b><small>Tap infected for immediate loot. Build rooms below ground for automation. Grow food, research permanent upgrades and survive larger mutations every 10 kills.</small></div></div>`}
function hud(){let r=rates();$('coins').textContent=fmt(S.coins);$('cps').textContent='+'+fmt(r.coins)+'/s';$('food').textContent=fmt(S.food);$('foodps').textContent='+'+fmt(r.food)+'/s';$('water').textContent=fmt(S.water);$('waterps').textContent='+'+fmt(r.water)+'/s';$('power').textContent=fmt(S.power);$('powerps').textContent='+'+fmt(r.power)+'/s';$('scrap').textContent=fmt(S.scrap);$('science').textContent=fmt(S.science);$('scienceps').textContent='+'+fmt(r.science)+'/s';$('bunkerLevel').textContent='LEVEL '+S.bunker;$('enemyType').textContent=(E?.boss?'BOSS ':'')+(E?.name||NAMES[tier()]);$('enemyLevel').textContent='MUTATION '+(tier()+1);$('enemyReward').textContent='REWARD '+fmt(E?.reward||0);$('enemyHp').style.width=((E&&!E.dead?Math.max(0,E.hp/E.max):0)*100)+'%';$('clickValue').textContent='+'+fmt(tap())+' DAMAGE';$('enemyCard').classList.toggle('bossGlow',!!E?.boss)}
function px(a,b,w,h,c){G.fillStyle=c;G.fillRect(Math.round(a),Math.round(b),Math.round(w),Math.round(h))}
function survivor(t){let y=339+Math.sin(t*9)*1.2;px(70,y-45,8,20,'#41523d');px(77,y-49,17,26,'#222a23');px(80,y-63,14,15,'#b98a68');px(76,y-68,20,8,'#30221d');px(67,y-38,9,23,'#4b6548');px(78,y-17,7,17,'#202824');px(90,y-17,7,17,'#202824');px(78,y-39,5,5,'#d7c5a3');G.save();G.translate(92,y-35);G.rotate(shot>0?-.11:.01);px(0,-2,34,5,'#303934');px(24,-4,18,3,'#858778');px(6,2,7,3,'#6a5a43');G.restore();if(shot>0){px(132,y-39,10,3,'#ffd25b');px(141,y-41,6,6,'#ef7a2e')}}
function zombie(t){if(!E||E.dead)return;let z=tier(),s=E.scale,y=342+Math.sin(t*4)*2;G.save();G.translate(E.x,y);G.scale(s,s);let skin=E.flash>0?'#e3dcc3':['#657044','#6b7448','#72604a','#684a43','#5b403e','#493532'][z],coat=['#46513b','#48533b','#4d4938','#503b34','#49322f','#3b2a2a'][z];let bw=30+z*2,hw=22+(z>3?4:0);px(-hw/2,-43,hw,22,skin);px(-bw/2,-21,bw,29,coat);px(-10,8,8,22,'#30342c');px(3,8,8,22,'#30342c');px(-7,-36,4,4,z>=4?'#ff3b31':'#d85a3d');px(4,-36,4,4,z>=4?'#ff3b31':'#d85a3d');px(-bw/2-6,-12,7,25,'#4c563c');px(bw/2-1,-11,7,25,'#4c563c');if(z>=1)px(-4,-27,11,4,'#71352d');if(z>=2){px(-19,-25,7,9,'#80402f');px(12,-30,8,10,'#73362e')}if(z>=3){px(-22,-35,8,10,'#8d4e31');px(16,-40,9,10,'#8d4e31');px(-5,-52,10,7,'#694330')}if(E.boss){px(-26,-5,8,8,'#b13b30');px(19,-28,9,9,'#a6322b');G.strokeStyle='#d75636';G.lineWidth=2;G.strokeRect(-28,-56,56,86)}G.restore()}
function draw(t){let phase=(S.kills%30)/30,sky=G.createLinearGradient(0,0,0,360);sky.addColorStop(0,phase>.72?'#232b38':'#ae5738');sky.addColorStop(.48,phase>.72?'#504552':'#684634');sky.addColorStop(1,'#1c211c');G.fillStyle=sky;G.fillRect(0,0,480,520);if(phase<.72){G.fillStyle='#e7ad55';G.beginPath();G.arc(335,105,22,0,7);G.fill()}for(let i=0;i<14;i++){let h=42+(i%5)*18,w=24+(i%3)*8,xx=i*39-8;px(xx,210-h,w,h,'#292723');for(let yy=216-h;yy<202;yy+=14)px(xx+6,yy,3,4,phase>.72?'#4c4e45':'#9d6438')}G.fillStyle='#42443a';G.beginPath();G.moveTo(0,288);for(let i=0;i<10;i++){G.lineTo(i*55,226+(i%3)*23);G.lineTo(i*55+43,288)}G.lineTo(480,288);G.fill();px(0,338,480,8,'#564832');px(0,346,480,174,'#22251e');for(let i=0;i<16;i++)px((i*37)%480,355+(i%4)*7,15,3,'#30342a');px(20,281,46,57,'#3a3024');px(25,269,35,14,'#4b3a2a');if(hitPulse>0){G.fillStyle='rgba(255,172,65,'+Math.min(.17,hitPulse)+')';G.fillRect(0,0,480,520)}survivor(t);zombie(t);for(let p of P){G.globalAlpha=Math.max(0,p.l/.7);px(p.x,p.y,3,3,p.c)}G.globalAlpha=1;G.textAlign='center';G.font='900 9px monospace';for(let f of F){G.globalAlpha=Math.max(0,f.l/.9);G.fillStyle=f.c;G.fillText(f.t,f.x,f.y)}G.globalAlpha=1;G.textAlign='left'}
function save(){S.last=Date.now();localStorage.afterlight_v3=JSON.stringify(S)}function offline(){let sec=Math.min(8*3600,Math.max(0,(Date.now()-S.last)/1000));if(sec<45)return;let r=rates(),m=.7;addCoins(r.coins*sec*m);S.food+=r.food*sec*m;S.water+=r.water*sec*m;S.power+=r.power*sec*m;S.scrap+=r.scrap*sec*m;S.science+=r.science*sec*m;$('offlineText').textContent='Your bunker worked for '+Math.floor(sec/60)+' minutes.';$('offlineGain').textContent='+'+fmt(r.coins*sec*m)+' COINS + RESOURCES';$('offline').classList.remove('hidden')}
let lastTouch=0;function pressAttack(e){if(e){if(e.type==='pointerdown'&&Date.now()-lastTouch<350)return;if(e.type==='touchstart')lastTouch=Date.now();e.preventDefault();e.stopPropagation()}attack(false);$('clickCore').classList.add('pressed');setTimeout(()=>$('clickCore').classList.remove('pressed'),90)}
$('clickCore').addEventListener('pointerdown',pressAttack,{passive:false});$('clickCore').addEventListener('touchstart',pressAttack,{passive:false});C.addEventListener('pointerdown',pressAttack,{passive:false});C.addEventListener('touchstart',pressAttack,{passive:false});$('closeDrawer').onclick=()=>$('drawer').classList.add('hidden');document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(q=>q.classList.remove('active'));b.classList.add('active');if(b.dataset.tab==='base')$('drawer').classList.add('hidden');else{$('drawer').classList.remove('hidden');renderDrawer()}});$('offlineCollect').onclick=()=>{$('offline').classList.add('hidden');sfx('coin')};
function loop(n){let dt=Math.min(.05,(n-last)/1000);last=n,r=rates();addCoins(r.coins*dt);S.food+=r.food*dt;S.water+=r.water*dt;S.power+=r.power*dt;S.scrap+=r.scrap*dt;S.science+=r.science*dt;shot=Math.max(0,shot-dt);hitPulse=Math.max(0,hitPulse-dt);if(E&&E.flash>0)E.flash-=dt;autoT-=dt;if(S.rooms.turret&&autoT<=0){attack(true);autoT=Math.max(.22,1.15/(1+S.rooms.turret*.08+S.research.automation*.12))}for(let p of P){p.l-=dt;p.vy+=185*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}P=P.filter(p=>p.l>0);for(let f of F){f.l-=dt;f.y-=19*dt}F=F.filter(f=>f.l>0);gardenT+=dt;if(gardenT>.5){if(document.querySelector('#tabs .active')?.dataset.tab==='garden'&&!$('drawer').classList.contains('hidden'))renderDrawer();gardenT=0}draw(n/1000);hud();if(dirty){renderRooms();dirty=false}requestAnimationFrame(loop)}
recalc();renderRooms();renderDrawer();hud();offline();setInterval(save,4000);requestAnimationFrame(loop);
})();