(()=>{'use strict';
const Q=[
['k5','Kill 5 infected','kills',5,'coins',75,1],['g2','Generator Level 2','generator',2,'coins',120,1],['w1','Build the Workshop','workshop',1,'scrap',15,1],['b2','Reach Bunker Level 2','bunker',2,'coinMult',1.15,1],['k15','Kill 15 infected','kills',15,'coins',300,2],['g5','Generator Level 5','generator',5,'powerMult',1.25,2],['w5','Workshop Level 5','workshop',5,'scrapMult',1.25,2],['gh1','Build the Greenhouse','greenhouse',1,'food',100,2],['b3','Reach Bunker Level 3','bunker',3,'prodMult',1.15,2],['k50','Kill 50 infected','kills',50,'zombieMult',2,3],
['g10','Generator Level 10','generator',10,'powerMult',2,3],['w10','Workshop Level 10','workshop',10,'scrapMult',2,3],['gh5','Greenhouse Level 5','greenhouse',5,'foodMult',1.25,3],['p5','Water Purifier Level 5','purifier',5,'waterMult',1.25,3],['b5','Reach Bunker Level 5','bunker',5,'prodMult',1.25,3],['k100','Kill 100 infected','kills',100,'damageMult',1.25,4],['lab5','Research Lab Level 5','lab',5,'scienceMult',1.5,4],['g25','Generator Level 25','generator',25,'prodMult',1.25,4],['w25','Workshop Level 25','workshop',25,'costMult',.9,4],['b7','Reach Bunker Level 7','bunker',7,'offlineMult',1.25,4],
['k250','Kill 250 infected','kills',250,'zombieMult',1.5,5],['gh10','Greenhouse Level 10','greenhouse',10,'foodMult',2,5],['p10','Water Purifier Level 10','purifier',10,'waterMult',2,5],['l10','Living Quarters Level 10','living',10,'coinMult',1.5,5],['b10','Reach Bunker Level 10','bunker',10,'prodMult',1.5,5],['boss10','Defeat 10 Brutes','bosses',10,'damageMult',1.5,6],['lab10','Research Lab Level 10','lab',10,'scienceMult',2,6],['s10','Storage Level 10','storage',10,'prodMult',1.25,6],['t10','Auto Turret Level 10','turret',10,'damageMult',1.5,6],['b15','Reach Bunker Level 15','bunker',15,'zombieMult',2,6],
['k500','Kill 500 infected','kills',500,'damageMult',1.5,7],['g50','Generator Level 50','generator',50,'powerMult',3,7],['w50','Workshop Level 50','workshop',50,'prodMult',1.5,7],['gh25','Greenhouse Level 25','greenhouse',25,'foodMult',2,7],['p25','Water Purifier Level 25','purifier',25,'waterMult',2,7],['b20','Reach Bunker Level 20','bunker',20,'prodMult',2,7],['k1000','Kill 1,000 infected','kills',1000,'zombieMult',2,8],['lab25','Research Lab Level 25','lab',25,'scienceMult',2,8],['s25','Storage Level 25','storage',25,'costMult',.85,8],['t25','Auto Turret Level 25','turret',25,'damageMult',2,8],
['b25','Reach Bunker Level 25','bunker',25,'offlineMult',2,8],['boss50','Defeat 50 Brutes','bosses',50,'zombieMult',2,9],['l25','Living Quarters Level 25','living',25,'coinMult',2,9],['rooms250','Reach 250 combined room levels','roomtotal',250,'prodMult',2,9],['k5000','Kill 5,000 infected','kills',5000,'damageMult',2,9],['b50','Reach Bunker Level 50','bunker',50,'prodMult',3,10],['rooms500','Reach 500 combined room levels','roomtotal',500,'costMult',.75,10],['boss100','Defeat 100 Brutes','bosses',100,'zombieMult',3,10],['k25000','Kill 25,000 infected','kills',25000,'zombieMult',3,10],['master','Reach Bunker Level 100','bunker',100,'prodMult',5,10]];
const key='afterlight_missions_v1';let M;try{M=JSON.parse(localStorage[key])||{claimed:[],bon:{}}}catch{M={claimed:[],bon:{}}}M.claimed=M.claimed||[];M.bon=M.bon||{};
const S=()=>{try{return JSON.parse(localStorage.afterlight_v4||'{}')}catch{return{}}};
const val=(q,s)=>q[2]==='kills'?(s.kills||0):q[2]==='bosses'?(s.stats?.bosses||0):q[2]==='bunker'?(s.bunker||1):q[2]==='roomtotal'?Object.values(s.rooms||{}).reduce((a,b)=>a+b,0):(s.rooms?.[q[2]]||0);
const fmt=n=>n>=1000?(n/1000).toFixed(n>=10000?0:1)+'K':Math.floor(n)+'';
const reward=q=>({coins:`${fmt(q[5])} COINS`,scrap:`${q[5]} SCRAP`,food:`${q[5]} FOOD`,coinMult:`x${q[5]} ALL COINS`,zombieMult:`x${q[5]} ZOMBIE BOUNTY`,prodMult:`x${q[5]} ALL PRODUCTION`,powerMult:`x${q[5]} POWER`,scrapMult:`x${q[5]} SCRAP`,foodMult:`x${q[5]} FOOD`,waterMult:`x${q[5]} WATER`,scienceMult:`x${q[5]} SCIENCE`,damageMult:`x${q[5]} DAMAGE`,costMult:`${Math.round((1-q[5])*100)}% CHEAPER UPGRADES`,offlineMult:`x${q[5]} OFFLINE GAINS`}[q[4]]||q[4]);
function save(){localStorage[key]=JSON.stringify(M)}
function eligible(q,s){return (s.bunker||1)>=q[6]&&!M.claimed.includes(q[0])}
function claim(q){const s=S();if(val(q,s)<q[3])return;M.claimed.push(q[0]);if(['coins','scrap','food'].includes(q[4])){s[q[4]]=(s[q[4]]||0)+q[5];localStorage.afterlight_v4=JSON.stringify(s)}else M.bon[q[4]]=(M.bon[q[4]]||1)*q[5];save();celebrate(q);render()}
window.AfterlightBonuses=()=>({...M.bon});
function celebrate(q){let e=document.createElement('div');e.className='missionWin';e.innerHTML=`<small>MISSION COMPLETE</small><b>${q[1]}</b><span>PERMANENT REWARD</span><strong>${reward(q)}</strong>`;document.body.append(e);setTimeout(()=>e.classList.add('show'),20);setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),400)},2600)}
function render(){const s=S(),qs=Q.filter(q=>eligible(q,s)).slice(0,3);const n=qs.filter(q=>val(q,s)>=q[3]).length;let box=document.getElementById('missionBox');if(!box){box=document.createElement('aside');box.id='missionBox';document.body.append(box)}box.innerHTML=`<button id="missionToggle"><i>✦</i><span>MISSIONS</span><b>${n?'<em>'+n+'</em>':''}</b></button><div class="missionPanel"><header><b>MISSION LOG</b><small>${M.claimed.length}/50 COMPLETE</small></header>${qs.map(q=>{let v=Math.min(q[3],val(q,s)),done=v>=q[3];return `<article class="${done?'done':''}"><b>${q[1]}</b><small>${fmt(v)} / ${fmt(q[3])}</small><div><i style="width:${Math.min(100,v/q[3]*100)}%"></i></div><span>${reward(q)}</span>${done?`<button data-q="${q[0]}">CLAIM</button>`:''}</article>`}).join('')||'<p>Raise your Bunker Level to discover new missions.</p>'}</div>`;box.querySelector('#missionToggle').onclick=()=>box.classList.toggle('open');box.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>claim(Q.find(q=>q[0]===b.dataset.q)))}
setInterval(render,900);render();
})();