(()=>{'use strict';
const scene=document.getElementById('scene'),tap=document.getElementById('clickCore');if(!scene)return;
const ASSETS=['survivor2','walker2','runner2','brute2','spitter2','tank2','boss2'];
const urls={};
function stripConnectedBackground(dataUrl){return new Promise(resolve=>{const im=new Image();im.onload=()=>{try{const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});c.width=im.naturalWidth;c.height=im.naturalHeight;x.drawImage(im,0,0);const img=x.getImageData(0,0,c.width,c.height),d=img.data,w=c.width,h=c.height;const samples=[[0,0],[w-1,0],[0,h-1],[w-1,h-1]].map(([px,py])=>{const i=(py*w+px)*4;return[d[i],d[i+1],d[i+2],d[i+3]]});const bg=samples.reduce((a,p)=>[a[0]+p[0]/4,a[1]+p[1]/4,a[2]+p[2]/4,a[3]+p[3]/4],[0,0,0,0]);const seen=new Uint8Array(w*h),q=[];for(let xx=0;xx<w;xx++){q.push(xx,(h-1)*w+xx)}for(let yy=0;yy<h;yy++){q.push(yy*w,yy*w+w-1)}let head=0;const close=n=>{const p=n*4,dr=d[p]-bg[0],dg=d[p+1]-bg[1],db=d[p+2]-bg[2],dist=Math.sqrt(dr*dr+dg*dg+db*db);return d[p+3]<220||dist<100};while(head<q.length){const n=q[head++];if(n<0||n>=w*h||seen[n]||!close(n))continue;seen[n]=1;d[n*4+3]=0;const xx=n%w,yy=(n/w)|0;if(xx>0)q.push(n-1);if(xx<w-1)q.push(n+1);if(yy>0)q.push(n-w);if(yy<h-1)q.push(n+w)}x.putImageData(img,0,0);resolve(c.toDataURL('image/png'))}catch(e){console.warn('sprite cleanup failed',e);resolve(dataUrl)}};im.onerror=()=>resolve(dataUrl);im.src=dataUrl})}
async function load(name){try{const t=await fetch(`assets/${name}.b64?v=10`).then(r=>{if(!r.ok)throw Error(r.status);return r.text()});const raw=`data:image/webp;base64,${t.trim()}`;urls[name]=await stripConnectedBackground(raw)}catch(e){console.warn('sprite load failed',name,e)}}
const stage=document.createElement('div');stage.id='spriteStage';stage.innerHTML='<div class="worldSky"></div><div class="worldRuins far"></div><div class="worldRuins near"></div><div class="road"></div><div class="bunkerSilhouette"></div>';
const survivor=document.createElement('img');survivor.className='survivorSprite';survivor.alt='Survivor';
const enemy=document.createElement('img');enemy.className='enemySprite';enemy.alt='Infected';
const muzzle=document.createElement('i');muzzle.className='muzzleFx';
const impact=document.createElement('i');impact.className='impactFx';
stage.append(survivor,enemy,muzzle,impact);scene.prepend(stage);
let current='';
function getVisual(){const type=(document.getElementById('enemyType')?.textContent||'').toUpperCase();const lvl=(document.getElementById('enemyLevel')?.textContent||'').toUpperCase();if(type==='BRUTE'&&!/MUTATION\s+\d/.test(lvl))return['boss2',5,'MUTATION BOSS'];const m=parseInt((lvl.match(/(\d+)/)||[])[1]||'1',10);const cycle=['walker2','runner2','brute2','spitter2','tank2'];const labels=['WALKER','RUNNER','BRUTE','SPITTER','TANK'];const i=(Math.max(1,m)-1)%cycle.length;return[cycle[i],i+1,labels[i]]}
function sync(){const[name,tier,label]=getVisual();if(name===current)return;current=name;enemy.dataset.tier=tier;enemy.classList.remove('spawn');void enemy.offsetWidth;enemy.classList.add('spawn');if(urls[name])enemy.src=urls[name];const et=document.getElementById('enemyType');if(et&&name!=='boss2')et.textContent=label}
function feedback(){survivor.classList.remove('shoot');enemy.classList.remove('hit');muzzle.classList.remove('fire');impact.classList.remove('pop');void stage.offsetWidth;survivor.classList.add('shoot');enemy.classList.add('hit');muzzle.classList.add('fire');impact.classList.add('pop');setTimeout(()=>{survivor.classList.remove('shoot');enemy.classList.remove('hit')},180)}
tap?.addEventListener('pointerdown',feedback);scene.addEventListener('pointerdown',e=>{if(e.target===scene||e.target.id==='game')feedback()});
Promise.all(ASSETS.map(load)).then(()=>{survivor.src=urls.survivor2||'';sync();setInterval(sync,160)});
})();