(()=>{'use strict';
const CFG=window.BunkrConfig,ST=window.BunkrState,GAME=window.BunkrGame,NUM=window.BunkrNumbers;if(!CFG||!ST||!GAME||!NUM)throw new Error('Infected Codex dependencies missing');
const S=ST.get(),ENEMIES=CFG.ENEMIES||[],NOTES={common:'Baseline infected. No rarity aura and one of the most common perimeter threats.',zouki:'A relentless former ward patient whose long dress hides an unnervingly quick stride. Common, but never harmless.',uncommon:'Heat-scarred infected with tougher tissue and improved salvage.',rare:'Armored responder carrying a valuable blue-tier combat bounty.',epic:'Massive contaminated carrier with high health and premium salvage.',legendary:'Extremely scarce elite infected with the richest normal encounter bounty.',brute:'Boss-class target. Never forms a horde and always drops one Brute Core plus one Uranium Crystal.'};let opened=false;
const known=id=>Array.isArray(S.stats.discovered)&&S.stats.discovered.includes(id);
function card(type,current){const unlocked=known(type.id),kills=Number(S.stats.rarityKills?.[type.id])||0;return `<article class="codexEntry ${unlocked?'unlocked':'locked'} ${current===type.id?'current':''}" style="--codex-accent:${type.accent}" data-codex-id="${type.id}" data-codex-known="${unlocked}"><div class="codexPortrait">${unlocked?`<img src="${type.asset}" alt="${type.name}" draggable="false">`:'<i>?</i>'}<em>${current===type.id?'CURRENT TARGET':unlocked?'ARCHIVED':'UNKNOWN SIGNAL'}</em></div><header><span><small>${unlocked?type.rarity:'UNIDENTIFIED'}</small><b>${unlocked?type.name:'LOCKED SPECIMEN'}</b></span><strong>${unlocked?NUM.format(kills)+' KILLS':'--'}</strong></header><div class="codexStats"><span><small>SPAWN</small><b>${type.chance}%</b></span><span><small>HEALTH</small><b>${unlocked?'×'+type.hpMultiplier:'???'}</b></span><span><small>COINS</small><b>${unlocked?'×'+type.bountyMultiplier:'???'}</b></span><span><small>SCRAP</small><b>${unlocked?'×'+type.scrapMultiplier:'???'}</b></span></div><p>${unlocked?NOTES[type.id]:'Encounter this infected in combat to decrypt its complete archive.'}</p></article>`}
function render(){if(!opened)return false;const discovered=ENEMIES.filter(type=>known(type.id)).length,current=GAME.enemy()?.id||'',progress=ENEMIES.length?discovered/ENEMIES.length*100:0;let root=document.getElementById('enemyCodex');if(!root){root=document.createElement('section');root.id='enemyCodex';root.className='codexModal';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','Infected Codex');document.getElementById('app').append(root);root.addEventListener('pointerdown',event=>{if(event.target===root)close()})}root.innerHTML=`<div class="codexShell"><header><div><small>BUNKR THREAT ARCHIVE</small><h2>☷ INFECTED CODEX</h2><p>Every observed infected is permanently decrypted for this device.</p></div><button type="button" data-codex-close aria-label="Close Infected Codex">×</button></header><section class="codexProgress"><span><b>${discovered} / ${ENEMIES.length} DISCOVERED</b><small>${ENEMIES.length-discovered} SIGNAL${ENEMIES.length-discovered===1?'':'S'} REMAIN</small></span><div><i style="width:${progress}%"></i></div></section><div class="codexGrid">${ENEMIES.map(type=>card(type,current)).join('')}</div></div>`;root.querySelector('[data-codex-close]').onclick=close;requestAnimationFrame(()=>root.classList.add('open'));return true}
function open(){opened=true;render();return true}
function close(){opened=false;const root=document.getElementById('enemyCodex');root?.classList.remove('open');setTimeout(()=>{if(!opened)root?.remove()},220);return true}
const trigger=document.getElementById('enemyCard');if(trigger){trigger.addEventListener('click',open);trigger.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}})}
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&opened)close()});window.addEventListener('bunkr:enemy',()=>{if(opened)render()});window.addEventListener('bunkr:state',event=>{if(opened&&event.detail?.reason==='enemy-discovered')render()});
document.body.dataset.codexSystem='ready';window.BunkrCodex={open,close,render,isOpen:()=>opened,discovered:()=>ENEMIES.filter(type=>known(type.id)).map(type=>type.id)};
})();

