(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState;if(!CFG||!ST)throw new Error('Expedition dependencies missing');
const S=ST.get(),X=S.expeditions,Z=CFG.EXPEDITIONS,P=CFG.SPECIALISTS;
const pick=a=>Math.floor(a[0]+Math.random()*(a[1]-a[0]+1));
const fmt=n=>n<1000?Math.floor(n)+'':n<1e6?(n/1000).toFixed(1)+'K':(n/1e6).toFixed(1)+'M';
const time=n=>{n=Math.max(0,Math.ceil(n));const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
const duration=sec=>sec>=3600?(sec/3600)+' HOUR':sec>=60?(sec/60)+' MIN':'1 MIN';
const specialist=id=>P.find(p=>p.id===id)||null;
function survivors(){return [...X.survivors]}
function start(id){const zone=Z[id];if(!zone||X.active||S.bunker<zone.unlock)return false;ST.update('expedition',()=>{X.active={id,start:Date.now(),end:Date.now()+zone.seconds*1000}});render();return true}
function finish(){if(!X.active)return;const zone=Z[X.active.id];if(!zone){X.active=null;ST.save();return}const available=P.filter(p=>!X.survivors.includes(p.id)),found=available.length&&Math.random()<zone.specialistChance?available[Math.floor(Math.random()*available.length)].id:null;X.pending={zone:zone.id,name:zone.name,coins:pick(zone.coins),scrap:pick(zone.scrap),found};X.active=null;ST.save();ST.notify('expedition');reveal()}
function collect(){const r=X.pending;if(!r)return;ST.update('expedition',s=>{s.coins=(s.coins||0)+r.coins;s.total=(s.total||0)+r.coins;s.scrap=(s.scrap||0)+r.scrap;if(r.found&&!X.survivors.includes(r.found))X.survivors.push(r.found);X.pending=null});window.dispatchEvent(new CustomEvent('afterlight:survivors'));document.querySelector('.expReveal')?.remove();render();window.AfterlightGame?.hud?.();window.AfterlightSpecialRooms?.renderAll?.()}
function reveal(){const r=X.pending;if(!r||document.querySelector('.expReveal'))return;const found=specialist(r.found),e=document.createElement('div');e.className='expReveal';e.innerHTML=`<div class="flare">✦</div><small>EXPEDITION COMPLETE</small><h2>${r.name}</h2><div class="loot"><b>◉ +${fmt(r.coins)}</b><b>⚙ +${fmt(r.scrap)}</b></div>${found?`<div class="survivorFound"><span>★★ SPECIALIST FOUND ★★</span><i>${found.icon}</i><strong>${found.name}</strong><em>${found.role}</em><small>UNLOCKS ${found.unlocks}</small></div>`:'<p>No specialist found this time.</p>'}<button>COLLECT & RETURN</button>`;document.body.append(e);requestAnimationFrame(()=>e.classList.add('show'));e.querySelector('button').onclick=collect}
function roster(){if(!X.survivors.length)return '<p class="emptyCrew">No specialists found yet. Every expedition has a chance to locate one.</p>';return X.survivors.map(id=>{const p=specialist(id);return p?`<div><i>${p.icon}</i><p><b>${p.name}</b><small>${p.role} · UNLOCKS ${p.unlocks}</small></p></div>`:''}).join('')}
function render(container=document.getElementById('drawerBody')){if(!container)return;if(X.active){const zone=Z[X.active.id];if(!zone)return;const left=(X.active.end-Date.now())/1000,pct=Math.min(100,Math.max(0,(Date.now()-X.active.start)/(X.active.end-X.active.start)*100));container.innerHTML=`<section class="expHero"><small>EXPEDITION IN PROGRESS</small><h2>${zone.icon} ${zone.name}</h2><div class="expTimer"><span>TEAM RETURNS IN</span><b>${time(left)}</b></div><div class="expBar"><i style="width:${pct}%"></i></div><p>${Math.floor(pct)}% SEARCHED · YOU CAN LEAVE THIS SCREEN</p></section><section class="crew"><header><b>SPECIALIST ROSTER</b><span>${X.survivors.length}/5 FOUND</span></header>${roster()}</section>`;if(left<=0)finish();return}container.innerHTML=`<div class="expIntro"><b>EXPEDITIONS</b><span>Send a scavenger team into the dead city. Recover salvage and locate specialists for classified bunker rooms.</span></div>${Object.values(Z).map(zone=>{const locked=S.bunker<zone.unlock;return `<article class="expZone ${locked?'locked':''}"><i>${zone.icon}</i><div><b>${zone.name}</b><small>${locked?'🔒 BUNKER LEVEL '+zone.unlock+' REQUIRED':duration(zone.seconds)+' · '+fmt(zone.coins[0])+'–'+fmt(zone.coins[1])+' COINS · '+Math.round(zone.specialistChance*100)+'% SPECIALIST CHANCE'}</small></div><button ${locked?'disabled':''} onclick="startAfterlightExpedition('${zone.id}')">${locked?'LOCKED':'DEPLOY'}</button></article>`}).join('')}<section class="crew"><header><b>SPECIALIST ROSTER</b><span>${X.survivors.length}/5 FOUND</span></header>${roster()}</section>`}
window.startAfterlightExpedition=start;window.AfterlightSurvivors=survivors;window.AfterlightExpeditions={start,render,survivors,reveal};
setInterval(()=>{if(X.active&&Date.now()>=X.active.end)finish();const active=document.querySelector('[data-tab="expeditions"].active');if(active&&X.active)render()},250);if(X.pending)setTimeout(reveal,250);
})();