(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState,NUM=window.AfterlightNumbers;if(!CFG||!ST||!NUM)throw new Error('Expedition dependencies missing');
const S=ST.get(),X=S.expeditions,Z=CFG.EXPEDITIONS,P=CFG.SPECIALISTS;
const pick=a=>Math.floor(a[0]+Math.random()*(a[1]-a[0]+1));
const fmt=NUM.format;
const time=n=>{n=Math.max(0,Math.ceil(n));const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
const duration=sec=>sec>=3600?(sec/3600)+' HOUR':sec>=60?(sec/60)+' MIN':'1 MIN';
const specialist=id=>P.find(p=>p.id===id)||null;
const localTest=location.hostname==='localhost'||location.hostname==='127.0.0.1';
const testParams=localTest?new URLSearchParams(location.search):null;
const expeditionSeconds=zone=>{const seconds=Number(testParams?.get('expeditionSeconds')),base=seconds>0?Math.min(zone.seconds,seconds):zone.seconds;return Math.max(1,Math.round(base*(window.AfterlightPrestige?.expeditionTimeMultiplier?.()||1)))};
const findsUranium=zone=>testParams?.get('forceExpeditionUranium')==='1'||Math.random()<zone.uraniumChance;
function permanentRate(resource){const live=Number(window.AfterlightGame?.rates?.({useReserves:false,cache:false})?.[resource]||0),dealer=Math.max(1,Number(window.AfterlightMerchant?.multiplier?.(resource)||1));return Math.max(0,live/dealer)}
function deploymentCost(zone){const result={};for(const resource of ['food','water'])result[resource]=Math.max(Number(zone.supplies?.[resource])||0,Math.ceil(permanentRate(resource)*zone.supplySeconds));return result}
function canDeploy(cost){return Object.entries(cost).every(([resource,amount])=>(Number(S[resource])||0)>=amount)}
function scaledReward(floorRange,secondsRange,rate){return Math.max(pick(floorRange),Math.floor(Math.max(0,Number(rate)||0)*pick(secondsRange)))}
function rewardRange(zone,resource){const floors=zone[resource],seconds=resource==='coins'?zone.coinSeconds:zone.scrapSeconds,rate=permanentRate(resource);return [Math.max(floors[0],Math.floor(rate*seconds[0])),Math.max(floors[1],Math.floor(rate*seconds[1]))]}
function survivors(){return [...X.survivors]}
function start(id){const zone=Z[id];if(!zone||X.active||S.bunker<zone.unlock)return false;const supplies=deploymentCost(zone);if(!canDeploy(supplies))return false;const now=Date.now(),rewardMultiplier=window.AfterlightPrestige?.expeditionRewardMultiplier?.()||1,scrapMultiplier=window.AfterlightPrestige?.activePerk?.()==='salvage-discipline'?1.4:1,rewardRates={coins:permanentRate('coins'),scrap:permanentRate('scrap')};let deployed=false;ST.update('expedition',state=>{if(X.active||!Object.entries(supplies).every(([resource,amount])=>(Number(state[resource])||0)>=amount))return;for(const [resource,amount] of Object.entries(supplies))state[resource]-=amount;X.active={id,start:now,end:now+expeditionSeconds(zone)*1000,rewardMultiplier,scrapMultiplier,supplies,rewardRates};deployed=true});if(!deployed)return false;window.dispatchEvent(new CustomEvent('afterlight:expedition-started',{detail:{id,zone:zone.name,supplies}}));render();window.AfterlightGame?.hud?.();return true}
function finish(){if(!X.active)return;const active={...X.active},zone=Z[active.id];if(!zone){X.active=null;ST.save();return}const available=P.filter(p=>!X.survivors.includes(p.id)),found=available.length&&Math.random()<zone.specialistChance?available[Math.floor(Math.random()*available.length)].id:null,uranium=findsUranium(zone)?pick(zone.uranium):0,rewardMultiplier=Math.max(1,Number(active.rewardMultiplier)||1),scrapMultiplier=Math.max(1,Number(active.scrapMultiplier)||1),coinBase=scaledReward(zone.coins,zone.coinSeconds,active.rewardRates?.coins),scrapBase=scaledReward(zone.scrap,zone.scrapSeconds,active.rewardRates?.scrap);X.pending={zone:zone.id,name:zone.name,coins:Math.max(1,Math.floor(coinBase*rewardMultiplier)),scrap:Math.max(1,Math.floor(scrapBase*rewardMultiplier*scrapMultiplier)),uranium,found,supplies:active.supplies||null};X.active=null;ST.save();ST.notify('expedition');reveal()}
function collect(){const r=X.pending;if(!r)return;ST.update('expedition',s=>{s.coins=(s.coins||0)+r.coins;s.total=(s.total||0)+r.coins;s.scrap=(s.scrap||0)+r.scrap;s.uranium=(s.uranium||0)+(r.uranium||0);s.stats.uraniumEarned=(s.stats.uraniumEarned||0)+(r.uranium||0);if(r.found&&!X.survivors.includes(r.found))X.survivors.push(r.found);X.pending=null});window.dispatchEvent(new CustomEvent('afterlight:survivors'));document.querySelector('.expReveal')?.remove();render();window.AfterlightGame?.hud?.();window.AfterlightSpecialRooms?.renderAll?.()}
function reveal(){const r=X.pending;if(!r||document.querySelector('.expReveal'))return;const found=specialist(r.found),e=document.createElement('div');e.className='expReveal';e.innerHTML=`<div class="flare">✦</div><small>EXPEDITION COMPLETE</small><h2>${r.name}</h2><div class="loot"><b>◉ +${fmt(r.coins)}</b><b>⚙ +${fmt(r.scrap)}</b>${r.uranium?`<b class="uraniumLoot">◆ +${r.uranium}</b>`:'<b class="uraniumMiss">◇ NO CRYSTAL</b>'}</div>${found?`<div class="survivorFound"><span>★★ SPECIALIST FOUND ★★</span><i>${found.icon}</i><strong>${found.name}</strong><em>${found.role}</em><small>UNLOCKS ${found.unlocks}</small></div>`:'<p>No specialist found this time.</p>'}<button>COLLECT & RETURN</button>`;document.body.append(e);window.dispatchEvent(new CustomEvent('afterlight:expedition-complete',{detail:{zone:r.zone,name:r.name,coins:r.coins,scrap:r.scrap,uranium:r.uranium||0,found:r.found}}));requestAnimationFrame(()=>e.classList.add('show'));e.querySelector('button').onclick=collect}
function roster(){if(!X.survivors.length)return '<p class="emptyCrew">No specialists found yet. Every expedition has a chance to locate one.</p>';return X.survivors.map(id=>{const p=specialist(id);return p?`<div><i>${p.icon}</i><p><b>${p.name}</b><small>${p.role} · UNLOCKS ${p.unlocks}</small></p></div>`:''}).join('')}
function render(container=document.getElementById('drawerBody')){if(!container)return;if(X.active){const zone=Z[X.active.id];if(!zone)return;const left=(X.active.end-Date.now())/1000,pct=Math.min(100,Math.max(0,(Date.now()-X.active.start)/(X.active.end-X.active.start)*100)),spent=X.active.supplies||{};container.innerHTML=`<section class="expHero"><small>EXPEDITION IN PROGRESS</small><h2>${zone.icon} ${zone.name}</h2><div class="expTimer"><span>TEAM RETURNS IN</span><b>${time(left)}</b></div><div class="expBar"><i style="width:${pct}%"></i></div><p>${Math.floor(pct)}% SEARCHED · RATIONS COMMITTED 🌿 ${fmt(spent.food||0)} · 💧 ${fmt(spent.water||0)}</p></section><section class="crew"><header><b>SPECIALIST ROSTER</b><span>${X.survivors.length}/5 FOUND</span></header>${roster()}</section>`;if(left<=0)finish();return}container.innerHTML=`<div class="expIntro"><b>EXPEDITIONS</b><span>Deployments spend Food and Water immediately. Loot scales from your sustained bunker economy; temporary Dealer boosts never inflate it.</span></div>${Object.values(Z).map(zone=>{const locked=S.bunker<zone.unlock,boost=window.AfterlightPrestige?.expeditionRewardMultiplier?.()||1,cost=deploymentCost(zone),ready=canDeploy(cost),coins=rewardRange(zone,'coins'),scrap=rewardRange(zone,'scrap');return `<article class="expZone ${locked?'locked':ready?'':'supplyLocked'}"><i>${zone.icon}</i><div><b>${zone.name}</b><small>${locked?'🔒 BUNKER LEVEL '+zone.unlock+' REQUIRED':duration(expeditionSeconds(zone))+' · COST 🌿 '+fmt(cost.food)+' + 💧 '+fmt(cost.water)+' · '+fmt(coins[0]*boost)+'–'+fmt(coins[1]*boost)+' COINS · ⚙ '+fmt(scrap[0])+'–'+fmt(scrap[1])+' · '+Math.round(zone.uraniumChance*100)+'% CRYSTAL'}</small></div><button ${locked||!ready?'disabled':''} onclick="startAfterlightExpedition('${zone.id}')">${locked?'LOCKED':ready?'DEPLOY':'NEED SUPPLIES'}</button></article>`}).join('')}<section class="crew"><header><b>SPECIALIST ROSTER</b><span>${X.survivors.length}/5 FOUND</span></header>${roster()}</section>`}
window.startAfterlightExpedition=start;window.AfterlightSurvivors=survivors;window.AfterlightExpeditions={start,render,survivors,reveal,deploymentCost,rewardRange};
setInterval(()=>{if(X.active&&Date.now()>=X.active.end)finish();const active=document.querySelector('[data-tab="expeditions"].active');if(active&&X.active)render()},250);if(X.pending)setTimeout(reveal,250);
})();
