(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState,NUM=window.AfterlightNumbers;if(!CFG||!ST||!NUM)throw new Error('Expedition dependencies missing');
const S=ST.get(),X=S.expeditions,Z=CFG.EXPEDITIONS,P=CFG.SPECIALISTS,C=CFG.EXPEDITION_COMPANIONS||[];
const BUNKER_POINT=[7,51],OUTBOUND_END=.42,RETURN_START=.58;
const COMPANION_WEIGHTS=Object.freeze({common:55,uncommon:26,rare:14,epic:5});
X.survivors=Array.isArray(X.survivors)?X.survivors:[];X.companions=Array.isArray(X.companions)?X.companions:[];X.selectedCompanion=X.companions.includes(X.selectedCompanion)?X.selectedCompanion:X.companions.at(-1)||null;X.visited=Array.isArray(X.visited)?X.visited:[];X.completed=X.completed&&typeof X.completed==='object'&&!Array.isArray(X.completed)?X.completed:{};
const pick=a=>Math.floor(a[0]+Math.random()*(a[1]-a[0]+1));
const fmt=NUM.format;
const time=n=>{n=Math.max(0,Math.ceil(n));const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
const duration=sec=>sec>=3600?`${Math.round(sec/360)/10} HR`:sec>=60?`${Math.round(sec/60)} MIN`:'1 MIN';
const specialist=id=>P.find(person=>person.id===id)||null;
const companion=id=>C.find(pet=>pet.id===id)||null;
const prestigeLevel=()=>Math.max(0,Number(S.prestige?.level)||0);
const selectedSurvivor=()=>CFG.SURVIVOR_SKINS.find(skin=>skin.id===S.survivorSkins?.selected&&skin.asset)||CFG.SURVIVOR_SKINS.find(skin=>skin.asset);
const localTest=location.hostname==='localhost'||location.hostname==='127.0.0.1';
const testParams=localTest?new URLSearchParams(location.search):null;
let selectedId=X.active?.id||Object.values(Z).sort((a,b)=>a.order-b.order)[0]?.id||null;
const expeditionSeconds=zone=>{const seconds=Number(testParams?.get('expeditionSeconds')),base=seconds>0?Math.min(zone.seconds,seconds):zone.seconds;return Math.max(1,Math.round(base*(window.AfterlightPrestige?.expeditionTimeMultiplier?.()||1)))};
const findsUranium=zone=>testParams?.get('forceExpeditionUranium')==='1'||Math.random()<zone.uraniumChance;
function permanentRate(resource){const live=Number(window.AfterlightGame?.rates?.({useReserves:false,cache:false})?.[resource]||0),dealer=Math.max(1,Number(window.AfterlightMerchant?.multiplier?.(resource)||1));return Math.max(0,live/dealer)}
function deploymentCost(zone){const result={};for(const resource of ['food','water'])result[resource]=Math.max(Number(zone.supplies?.[resource])||0,Math.ceil(permanentRate(resource)*zone.supplySeconds));return result}
function canDeploy(cost){return Object.entries(cost).every(([resource,amount])=>(Number(S[resource])||0)>=amount)}
function scaledReward(floorRange,secondsRange,rate){return Math.max(pick(floorRange),Math.floor(Math.max(0,Number(rate)||0)*pick(secondsRange)))}
function rewardRange(zone,resource){const floors=zone[resource],seconds=resource==='coins'?zone.coinSeconds:zone.scrapSeconds,rate=permanentRate(resource);return [Math.max(floors[0],Math.floor(rate*seconds[0])),Math.max(floors[1],Math.floor(rate*seconds[1]))]}
function survivors(){return [...X.survivors]}
function companions(){return [...X.companions]}
function selectedCompanion(){return companion(X.selectedCompanion)}
function selectCompanion(id){const pet=companion(id);if(!pet||!X.companions.includes(id))return false;ST.update('companion-selected',()=>{X.selectedCompanion=id});window.dispatchEvent(new CustomEvent('afterlight:companion-selected',{detail:{id,companion:pet}}));render();return true}
function lockReason(zone){if(prestigeLevel()<zone.prestige)return`PRESTIGE ${roman(zone.prestige)} REQUIRED`;if(zone.prestige===0&&S.bunker<zone.unlock)return`BUNKER LEVEL ${zone.unlock} REQUIRED`;return''}
function roman(number){return['0','I','II','III','IV','V'][number]||String(number)}
function nodePoint(id){return id==='bunker'?BUNKER_POINT:(Z[id]?.position||BUNKER_POINT)}
function edgePoints(zone){const from=nodePoint(zone.parent),to=zone.position,curve=(zone.order%2?1:-1)*Math.min(3.5,Math.abs(to[0]-from[0])*.18),middle=[(from[0]+to[0])/2,(from[1]+to[1])/2+curve];return[from,middle,to]}
function routePoints(zone){if(!zone)return[BUNKER_POINT];const chain=[],seen=new Set();let current=zone;while(current&&current.id&&!seen.has(current.id)){chain.unshift(current);seen.add(current.id);current=current.parent&&current.parent!=='bunker'?Z[current.parent]:null}const points=[BUNKER_POINT];for(const item of chain){const edge=edgePoints(item);if(points.at(-1)[0]!==edge[0][0]||points.at(-1)[1]!==edge[0][1])points.push(edge[0]);points.push(...edge.slice(1))}return points}
function mapPoint(points,progress){progress=Math.max(0,Math.min(1,progress));let total=0;const lengths=[];for(let index=1;index<points.length;index++){const dx=points[index][0]-points[index-1][0],dy=points[index][1]-points[index-1][1],length=Math.hypot(dx,dy);lengths.push(length);total+=length}let target=progress*total;for(let index=0;index<lengths.length;index++){if(target<=lengths[index]||index===lengths.length-1){const ratio=lengths[index]?target/lengths[index]:0;return[points[index][0]+(points[index+1][0]-points[index][0])*ratio,points[index][1]+(points[index+1][1]-points[index][1])*ratio]}target-=lengths[index]}return points.at(-1)}
function journey(active=X.active,now=Date.now()){if(!active)return null;const start=Number(active.start)||now,end=Math.max(start+1000,Number(active.end)||start+1000),overall=Math.max(0,Math.min(1,(now-start)/(end-start)));if(overall<OUTBOUND_END)return{phase:'OUTBOUND',label:'SCOUT MOVING TO TARGET',routeProgress:overall/OUTBOUND_END,overall,remaining:(end-now)/1000,returning:false};if(overall<RETURN_START)return{phase:'SEARCH',label:'SEARCHING LOCATION',routeProgress:1,overall,remaining:(end-now)/1000,returning:false};return{phase:'RETURN',label:'SCOUT RETURNING TO BUNKER',routeProgress:1-(overall-RETURN_START)/(1-RETURN_START),overall,remaining:(end-now)/1000,returning:true}}
function start(id){const zone=Z[id];if(!zone||X.active||lockReason(zone))return false;const supplies=deploymentCost(zone);if(!canDeploy(supplies))return false;const now=Date.now(),seconds=expeditionSeconds(zone),rewardMultiplier=window.AfterlightPrestige?.expeditionRewardMultiplier?.()||1,scrapMultiplier=window.AfterlightPrestige?.activePerk?.()==='salvage-discipline'?1.4:1,rewardRates={coins:permanentRate('coins'),scrap:permanentRate('scrap')};let deployed=false;ST.update('expedition',state=>{if(X.active||!Object.entries(supplies).every(([resource,amount])=>(Number(state[resource])||0)>=amount))return;for(const [resource,amount] of Object.entries(supplies))state[resource]-=amount;X.active={id,start:now,end:now+seconds*1000,arriveAt:now+seconds*OUTBOUND_END*1000,returnAt:now+seconds*RETURN_START*1000,rewardMultiplier,scrapMultiplier,supplies,rewardRates};if(!X.visited.includes(id))X.visited.push(id);deployed=true});if(!deployed)return false;selectedId=id;window.dispatchEvent(new CustomEvent('afterlight:expedition-started',{detail:{id,zone:zone.name,supplies,route:routePoints(zone)}}));render();window.AfterlightGame?.hud?.();return true}
function rollCompanion(zone){const available=C.filter(pet=>!X.companions.includes(pet.id));if(!available.length||Math.random()>=(Number(zone.companionChance)||0))return null;const total=available.reduce((sum,pet)=>sum+(COMPANION_WEIGHTS[pet.rarity]||1),0);let roll=Math.random()*total;for(const pet of available){roll-=COMPANION_WEIGHTS[pet.rarity]||1;if(roll<=0)return pet.id}return available.at(-1).id}
function finish(){if(!X.active)return;const active={...X.active},zone=Z[active.id];if(!zone){X.active=null;ST.save();return}const available=P.filter(person=>!X.survivors.includes(person.id)),found=available.length&&Math.random()<zone.specialistChance?available[Math.floor(Math.random()*available.length)].id:null,pet=rollCompanion(zone),uranium=findsUranium(zone)?pick(zone.uranium):0,rewardMultiplier=Math.max(1,Number(active.rewardMultiplier)||1),scrapMultiplier=Math.max(1,Number(active.scrapMultiplier)||1),coinBase=scaledReward(zone.coins,zone.coinSeconds,active.rewardRates?.coins),scrapBase=scaledReward(zone.scrap,zone.scrapSeconds,active.rewardRates?.scrap);X.pending={zone:zone.id,name:zone.name,coins:Math.max(1,Math.floor(coinBase*rewardMultiplier)),scrap:Math.max(1,Math.floor(scrapBase*rewardMultiplier*scrapMultiplier)),uranium,found,companion:pet,supplies:active.supplies||null};X.completed[zone.id]=Math.max(0,Number(X.completed[zone.id])||0)+1;X.active=null;ST.save();ST.notify('expedition');reveal()}
function collect(){const reward=X.pending;if(!reward)return;ST.update('expedition',state=>{state.coins=(state.coins||0)+reward.coins;state.total=(state.total||0)+reward.coins;state.scrap=(state.scrap||0)+reward.scrap;state.uranium=(state.uranium||0)+(reward.uranium||0);state.stats.uraniumEarned=(state.stats.uraniumEarned||0)+(reward.uranium||0);if(reward.found&&!X.survivors.includes(reward.found))X.survivors.push(reward.found);if(reward.companion){if(!X.companions.includes(reward.companion))X.companions.push(reward.companion);X.selectedCompanion=reward.companion}X.pending=null});window.dispatchEvent(new CustomEvent('afterlight:survivors'));window.dispatchEvent(new CustomEvent('afterlight:expedition-roster'));if(reward.companion)window.dispatchEvent(new CustomEvent('afterlight:companion-selected',{detail:{id:reward.companion,companion:companion(reward.companion)}}));document.querySelector('.expReveal')?.remove();render();window.AfterlightGame?.hud?.();window.AfterlightSpecialRooms?.renderAll?.()}
function reveal(){const reward=X.pending;if(!reward||document.querySelector('.expReveal'))return;const found=specialist(reward.found),pet=companion(reward.companion),element=document.createElement('div');element.className='expReveal';element.innerHTML=`<div class="expReturnSignal"><i></i><span>SCOUT SIGNAL ACQUIRED</span><i></i></div><div class="flare">✦</div><small>ROUND TRIP COMPLETE</small><h2>${reward.name}</h2><p class="expReturned">THE SCOUT RETURNED SAFELY TO AFTERLIGHT</p><div class="loot"><b>◉ +${fmt(reward.coins)}</b><b>⚙ +${fmt(reward.scrap)}</b>${reward.uranium?`<b class="uraniumLoot">◆ +${reward.uranium}</b>`:'<b class="uraniumMiss">◇ NO CRYSTAL</b>'}</div>${found?`<div class="survivorFound"><span>★★ SPECIALIST RECOVERED ★★</span><i>${found.icon}</i><strong>${found.name}</strong><em>${found.role}</em><small>UNLOCKS ${found.unlocks}</small></div>`:''}${pet?`<div class="companionFound"><span>${pet.rarity.toUpperCase()} COMPANION FOUND</span><i>${pet.icon}</i><strong>${pet.name}</strong><small>${pet.description}</small></div>`:''}${!found&&!pet?'<p>All signals searched. The recovered supplies are secure.</p>':''}<button>SECURE HAUL</button>`;document.body.append(element);window.dispatchEvent(new CustomEvent('afterlight:expedition-complete',{detail:{zone:reward.zone,name:reward.name,coins:reward.coins,scrap:reward.scrap,uranium:reward.uranium||0,found:reward.found,companion:reward.companion}}));requestAnimationFrame(()=>element.classList.add('show'));element.querySelector('button').onclick=collect}
function roster(){const people=X.survivors.map(id=>specialist(id)).filter(Boolean),pets=X.companions.map(id=>companion(id)).filter(Boolean);if(!people.length&&!pets.length)return'<p class="emptyCrew">No specialists or companions recovered yet. Stronger signals appear deeper in the atlas.</p>';return`${people.map(person=>`<div><i>${person.icon}</i><p><b>${person.name}</b><small>${person.role} · UNLOCKS ${person.unlocks}</small></p></div>`).join('')}${pets.map(pet=>`<button type="button" class="expPet ${X.selectedCompanion===pet.id?'selected':''}" data-companion-select="${pet.id}" style="--pet-accent:${pet.accent}"><i class="expPetPortrait" style="background-image:url('${pet.asset}')"></i><p><b>${pet.name}</b><small>${pet.role} · ${X.selectedCompanion===pet.id?'DEPLOYED BESIDE SURVIVOR':'TAP TO DEPLOY'}</small></p></button>`).join('')}`}
function pathMarkup(){const activeRoute=new Set();let current=Z[X.active?.id];while(current){activeRoute.add(current.id);current=current.parent&&current.parent!=='bunker'?Z[current.parent]:null}return Object.values(Z).sort((a,b)=>a.order-b.order).map(zone=>{const points=edgePoints(zone).map(point=>`${point[0]*10},${point[1]*6}`).join(' '),locked=!!lockReason(zone),active=activeRoute.has(zone.id),complete=(Number(X.completed[zone.id])||0)>0;return`<polyline class="atlasRoute ${locked?'locked':complete?'complete':''} ${active?'active':''}" data-route-id="${zone.id}" points="${points}"/>`}).join('')}
function nodeMarkup(){return Object.values(Z).sort((a,b)=>a.order-b.order).map(zone=>{const reason=lockReason(zone),active=X.active?.id===zone.id,complete=Number(X.completed[zone.id])||0,selected=selectedId===zone.id,mapArt=zone.art.replace('assets/expedition-','assets/expedition-map-');return`<button class="atlasNode ${reason?'locked':complete?'complete':'available'} ${active?'active':''} ${selected?'selected':''}" data-expedition-node="${zone.id}" style="--node-x:${zone.position[0]}%;--node-y:${zone.position[1]}%;--node-accent:${zone.prestige===5?'#ec6241':zone.prestige>=3?'#9d78c9':zone.prestige>=1?'#65a6bb':'#d3ae55'};--node-art-position:${zone.artPosition||'50% 50%'}" aria-label="${zone.name}${reason?' locked':''}"><i><img src="${mapArt}" alt="" loading="lazy" decoding="async"><em aria-hidden="true">${reason?'◇':active?'➤':complete?'✓':zone.icon}</em></i><span>${zone.name}</span><small>${reason?`P${zone.prestige}`:active?'TEAM DEPLOYED':complete?`${complete} RUN${complete===1?'':'S'}`:`P${zone.prestige}`}</small></button>`}).join('')}
function dossier(zone){if(!zone)return'<aside class="atlasDossier"><div class="dossierEmpty">SELECT A LOCATION</div></aside>';const reason=lockReason(zone),cost=deploymentCost(zone),ready=canDeploy(cost),coins=rewardRange(zone,'coins'),scrap=rewardRange(zone,'scrap'),boost=window.AfterlightPrestige?.expeditionRewardMultiplier?.()||1,active=X.active?.id===zone.id,runs=Number(X.completed[zone.id])||0,total=expeditionSeconds(zone),outbound=Math.round(total*OUTBOUND_END),search=Math.round(total*(RETURN_START-OUTBOUND_END)),returnTrip=total-outbound-search;return`<aside class="atlasDossier" data-dossier-id="${zone.id}"><div class="dossierImage" data-location-art="${zone.id}" style="--dossier-position:${zone.artPosition||'50% 50%'}"><img src="${zone.art}" alt="${zone.name} expedition location" decoding="async"><span>PRESTIGE ${roman(zone.prestige)} SECTOR</span><i aria-hidden="true">${zone.icon}</i><b>${zone.landmark}</b><em>${zone.threat} THREAT</em></div><header><div><small>LOCATION ${String(zone.order).padStart(2,'0')} · ${runs} COMPLETED</small><h2>${zone.name}</h2></div><span class="threat threat${zone.prestige}">${zone.threat}</span></header><p class="dossierLore">${zone.lore}</p><p class="dossierIntel">⌁ FIELD INTEL · ${zone.intel}</p><section class="journeyPlan"><h3>ROUND-TRIP ROUTE</h3><div><span><i>➤</i><b>OUTBOUND</b><small>${duration(outbound)}</small></span><span><i>⌖</i><b>SEARCH</b><small>${duration(search)}</small></span><span><i>↩</i><b>RETURN</b><small>${duration(returnTrip)}</small></span></div><p>Rewards unlock only after the scout follows this same route back to the bunker.</p></section><section class="dossierSupplies"><h3>DEPLOYMENT RATIONS</h3><div><b>🌿 ${fmt(cost.food)} FOOD</b><b>💧 ${fmt(cost.water)} WATER</b></div></section><section class="dossierRewards"><h3>ESTIMATED RECOVERY</h3><div><span><i>◉</i><b>${fmt(coins[0]*boost)}–${fmt(coins[1]*boost)}</b><small>COINS</small></span><span><i>⚙</i><b>${fmt(scrap[0])}–${fmt(scrap[1])}</b><small>SCRAP</small></span><span><i>◆</i><b>${Math.round(zone.uraniumChance*100)}%</b><small>${zone.uranium[0]}–${zone.uranium[1]} CRYSTALS</small></span><span><i>⌁</i><b>${Math.round(zone.specialistChance*100)}%</b><small>SPECIALIST</small></span>${zone.companionChance?`<span class="petChance"><i>✦</i><b>${(zone.companionChance*100).toFixed(1)}%</b><small>COMPANION</small></span>`:''}</div></section><div class="dossierLock ${reason?'show':''}">${reason||''}</div><button class="deployExpedition" data-expedition-deploy="${zone.id}" ${reason||!ready||X.active?'disabled':''}>${active?'SCOUT ALREADY DEPLOYED':X.active?'ANOTHER ROUTE IS ACTIVE':reason?'SECTOR LOCKED':ready?'BEGIN ROUND TRIP':'INSUFFICIENT RATIONS'}</button></aside>`}
function activeStatus(){if(!X.active)return'<div class="atlasIdle"><i></i><span>SELECT A LOCATION · PLAN THE ROUTE · BRING THE SCOUT HOME</span><i></i></div>';const zone=Z[X.active.id],state=journey();return`<div class="atlasJourney" data-journey-panel><span><small data-journey-phase>${state.label}</small><b>${zone.name}</b></span><div><i data-journey-bar style="width:${state.overall*100}%"></i></div><strong data-journey-time>${time(state.remaining)}</strong></div>`}
function atlasTabs(){return`<div class="atlasChapters">${[0,1,2,3,4,5].map(level=>`<button class="${prestigeLevel()>=level?'unlocked':'locked'}" data-atlas-prestige="${level}"><small>${level?'PRESTIGE '+roman(level):'ASHLANDS'}</small><b>P${level}</b><span>${level?2:4} LOCATIONS</span></button>`).join('')}<button class="future" disabled><small>FUTURE ATLAS</small><b>P6–100+</b><span>EXPANSION READY</span></button></div>`}
function render(container=document.getElementById('drawerBody')){if(!container)return;const zone=Z[selectedId]||Z[X.active?.id]||Object.values(Z)[0],skin=selectedSurvivor();container.dataset.expeditionAtlas='ready';container.innerHTML=`<main class="expeditionAtlas"><header class="atlasHeader"><div><small>AFTERLIGHT EXPEDITION COMMAND</small><h1>WORLD ATLAS</h1><p>Every marked road is persistent. Outbound and return travel always use the same secured route.</p></div><div class="atlasSummary"><span><small>ATLAS DEPTH</small><b>PRESTIGE ${roman(prestigeLevel())}</b></span><span><small>RECOVERED</small><b>${X.survivors.length} CREW · ${X.companions.length} PETS</b></span></div></header>${activeStatus()}<section class="atlasWorkspace"><div class="atlasViewport"><div class="atlasWorld" data-atlas-world><svg viewBox="0 0 1000 600" preserveAspectRatio="none" aria-hidden="true"><g class="atlasRoutes">${pathMarkup()}</g></svg><div class="atlasBunker" style="--node-x:${BUNKER_POINT[0]}%;--node-y:${BUNKER_POINT[1]}%"><i>⌂</i><b>AFTERLIGHT</b><small>ROUTE ORIGIN</small></div>${nodeMarkup()}${X.active?`<div class="expScout" data-expedition-scout style="--scout-x:${BUNKER_POINT[0]}%;--scout-y:${BUNKER_POINT[1]}%"><img src="${skin?.asset||''}" alt="Expedition scout"><span></span></div>`:''}<div class="atlasFog atlasFogA"></div><div class="atlasFog atlasFogB"></div></div><div class="atlasLegend"><span><i class="legendAvailable"></i>AVAILABLE</span><span><i class="legendComplete"></i>EXPLORED</span><span><i class="legendLocked"></i>PRESTIGE LOCKED</span><span><i class="legendActive"></i>ACTIVE ROUTE</span></div></div>${dossier(zone)}</section>${atlasTabs()}<section class="crew atlasCrew"><header><b>RECOVERED EXPEDITION ROSTER</b><span>${X.survivors.length}/${P.length} SPECIALISTS · ${X.companions.length}/${C.length} COMPANIONS</span></header>${roster()}</section></main>`;bind(container);requestAnimationFrame(()=>{focusSelected(container,false);updateJourney()})}
function bind(container){container.querySelectorAll('[data-expedition-node]').forEach(button=>button.addEventListener('click',()=>{selectedId=button.dataset.expeditionNode;render(container);focusSelected(container,true)}));container.querySelector('[data-expedition-deploy]')?.addEventListener('click',event=>start(event.currentTarget.dataset.expeditionDeploy));container.querySelectorAll('[data-companion-select]').forEach(button=>button.addEventListener('click',()=>selectCompanion(button.dataset.companionSelect)));container.querySelectorAll('[data-atlas-prestige]').forEach(button=>button.addEventListener('click',()=>{const first=Object.values(Z).sort((a,b)=>a.order-b.order).find(zone=>zone.prestige===Number(button.dataset.atlasPrestige));if(first){selectedId=first.id;render(container);focusSelected(container,true)}}))}
function focusSelected(container=document.getElementById('drawerBody'),smooth=false){const viewport=container?.querySelector('.atlasViewport'),node=container?.querySelector(`[data-expedition-node="${selectedId}"]`);if(!viewport||!node)return;const target=Math.max(0,node.offsetLeft-viewport.clientWidth*.5);viewport.scrollTo?.({left:target,behavior:smooth?'smooth':'auto'})}
function updateJourney(){if(!X.active)return;if(Date.now()>=Number(X.active.end)){finish();return}const zone=Z[X.active.id],state=journey(),points=routePoints(zone),point=mapPoint(points,state.routeProgress),scout=document.querySelector('[data-expedition-scout]');if(scout){scout.style.setProperty('--scout-x',point[0]+'%');scout.style.setProperty('--scout-y',point[1]+'%');scout.classList.toggle('returning',state.returning);scout.dataset.phase=state.phase}const phase=document.querySelector('[data-journey-phase]'),bar=document.querySelector('[data-journey-bar]'),clock=document.querySelector('[data-journey-time]');if(phase)phase.textContent=state.label;if(bar)bar.style.width=state.overall*100+'%';if(clock)clock.textContent=time(state.remaining);document.querySelector('[data-atlas-world]')?.setAttribute('data-phase',state.phase)}
window.startAfterlightExpedition=start;window.AfterlightSurvivors=survivors;window.AfterlightExpeditions={start,render,survivors,companions,selectedCompanion,selectCompanion,reveal,deploymentCost,rewardRange,routePoints,journey,lockReason,finish};
setInterval(updateJourney,250);if(X.pending)setTimeout(reveal,250);
})();
