(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState;if(!CFG||!ST)throw new Error('Merchant dependencies missing');
const S=ST.get(),OFFERS=CFG.MERCHANT_OFFERS||[];
const byId=id=>OFFERS.find(offer=>offer.id===id)||null;
const now=()=>Date.now();
const time=ms=>{const seconds=Math.max(0,Math.ceil(ms/1000)),minutes=Math.floor(seconds/60);return `${String(minutes).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};
const remaining=id=>Math.max(0,Number(S.merchant?.active?.[id]||0)-now());
const active=id=>remaining(id)>0;
const activeOffers=()=>OFFERS.filter(offer=>active(offer.id));
function multiplier(key){let value=1;for(const offer of activeOffers()){if(Number(offer.effect?.all)>0)value*=offer.effect.all;if(Number(offer.effect?.[key])>0)value*=offer.effect[key]}return value}
function rarityWeights(){return active('lure')?{common:30,uncommon:30,rare:20,epic:10,legendary:6,brute:4}:null}
function testDuration(offer){if(!['localhost','127.0.0.1'].includes(location.hostname))return offer.seconds*1000;const requested=Number(new URLSearchParams(location.search).get('merchantSeconds'));return Number.isFinite(requested)&&requested>0?Math.min(offer.seconds,requested)*1000:offer.seconds*1000}
function conflict(offer){return OFFERS.find(other=>other.group===offer.group&&other.id!==offer.id&&active(other.id))||null}
function award(amount,source='unknown'){amount=Math.max(0,Math.floor(Number(amount)||0));if(!amount)return 0;ST.update('uranium-'+source,state=>{state.uranium=(state.uranium||0)+amount;state.stats.uraniumEarned=(state.stats.uraniumEarned||0)+amount});window.dispatchEvent(new CustomEvent('afterlight:uranium',{detail:{amount,source,total:S.uranium}}));updateUi();window.AfterlightGame?.hud?.();return amount}
function celebrate(offer){document.querySelector('.dealerPurchaseBurst')?.remove();const burst=document.createElement('div');burst.className='dealerPurchaseBurst';burst.innerHTML=`<div class="dealerBurstCore"><small>DEAL ACCEPTED</small><i>${offer.icon}</i><b>${offer.value}</b><span>ONLINE · ${time(testDuration(offer))}</span></div>${'<em></em>'.repeat(12)}`;document.body.append(burst);requestAnimationFrame(()=>burst.classList.add('show'));setTimeout(()=>{burst.classList.remove('show');setTimeout(()=>burst.remove(),350)},1900)}
function buy(id){const offer=byId(id);if(!offer)return false;pruneExpired();const blocked=conflict(offer);if(blocked)return false;if((S.uranium||0)<offer.cost)return false;const duration=testDuration(offer),start=Math.max(now(),Number(S.merchant.active[offer.id]||0));ST.update('merchant-purchase',state=>{state.uranium-=offer.cost;state.merchant.active[offer.id]=start+duration;state.merchant.purchases[offer.id]=(state.merchant.purchases[offer.id]||0)+1;state.merchant.spent=(state.merchant.spent||0)+offer.cost;state.stats.uraniumSpent=(state.stats.uraniumSpent||0)+offer.cost});window.dispatchEvent(new CustomEvent('afterlight:merchant-purchase',{detail:{id:offer.id,name:offer.name,value:offer.value,cost:offer.cost,end:S.merchant.active[offer.id]}}));celebrate(offer);render();window.AfterlightGame?.hud?.();return true}
function pruneExpired(){const expired=Object.entries(S.merchant?.active||{}).filter(([,end])=>Number(end)>0&&Number(end)<=now()).map(([id])=>id);if(!expired.length)return expired;ST.update('merchant-expired',state=>expired.forEach(id=>delete state.merchant.active[id]));window.dispatchEvent(new CustomEvent('afterlight:merchant-expired',{detail:{ids:expired}}));return expired}
function offerCard(offer){const left=remaining(offer.id),running=left>0,blocked=conflict(offer),afford=(S.uranium||0)>=offer.cost;let action=`BUY · ${offer.cost} ◆`;if(running)action=`EXTEND +${time(offer.seconds*1000)} · ${offer.cost} ◆`;else if(blocked)action='CHANNEL BUSY';else if(!afford)action=`NEED ${offer.cost} ◆`;return `<article class="dealerOffer tier${offer.tier.toLowerCase()} ${running?'activeBoost':''}" style="--offer-accent:${offer.accent}" data-offer="${offer.id}"><div class="dealerOfferTop"><i>${offer.icon}</i><span><small>${offer.tier} CONTRABAND</small><b>${offer.name}</b></span>${running?`<em data-boost-time="${offer.id}">${time(left)}</em>`:''}</div><strong>${offer.value}</strong><p>${offer.tagline}</p><div class="dealerDuration"><span>⚡ ACTIVATES IMMEDIATELY</span><b>05:00</b></div><button data-buy="${offer.id}" ${blocked||!afford?'disabled':''}>${action}</button></article>`}
function activeMarkup(){const running=activeOffers();if(!running.length)return '<div class="dealerNoBoost"><i>◇</i><span><b>NO ACTIVE CONTRACTS</b><small>Purchased stock activates immediately.</small></span></div>';return running.map(offer=>`<div class="dealerActiveChip" style="--offer-accent:${offer.accent}"><i>${offer.icon}</i><span><b>${offer.value}</b><small>${offer.name}</small></span><em data-boost-time="${offer.id}">${time(remaining(offer.id))}</em></div>`).join('')}
function render(container=document.getElementById('drawerBody')){if(!container)return;pruneExpired();container.dataset.merchantScreen='ready';container.innerHTML=`<section class="dealerHero"><div class="dealerPortrait"><span>☢</span><i></i></div><div class="dealerIdentity"><small>ENCRYPTED BLACK-MARKET CHANNEL</small><h2>THE DEALER</h2><p>“Crystal talks. Everything else wastes my time.”</p></div><div class="dealerWallet"><small>URANIUM CRYSTALS</small><b>◆ <span data-dealer-balance>${Math.floor(S.uranium||0)}</span></b><em>MISSIONS · EXPEDITIONS · BRUTES</em></div></section><section class="dealerLive"><header><b>ACTIVE CONTRACTS</b><span>${activeOffers().length} ONLINE</span></header><div data-active-boosts>${activeMarkup()}</div></section><section class="dealerStock"><header><div><small>LIMITED BLACK-MARKET STOCK</small><b>BOOSTS ACTIVATE ON PURCHASE</b></div><span>NO REFUNDS</span></header><div class="dealerGrid">${OFFERS.map(offerCard).join('')}</div></section>`;container.querySelectorAll('[data-buy]').forEach(button=>button.onclick=()=>buy(button.dataset.buy));updateBadge()}
function updateBadge(){const badge=document.getElementById('merchantBadge'),count=activeOffers().length;if(!badge)return;badge.textContent=count||'';badge.classList.toggle('visible',count>0)}
function updateUi(){const balance=document.querySelector('[data-dealer-balance]');if(balance)balance.textContent=Math.floor(S.uranium||0);document.querySelectorAll('[data-boost-time]').forEach(node=>{const left=remaining(node.dataset.boostTime);node.textContent=time(left)});updateBadge()}
if(['localhost','127.0.0.1'].includes(location.hostname)){const dev=Number(new URLSearchParams(location.search).get('uranium'));if(Number.isFinite(dev)&&dev>0&&S.uranium<dev){S.uranium=Math.floor(dev);ST.save()}}
document.body.dataset.merchantSystem='ready';setInterval(()=>{const expired=pruneExpired();if(expired.length&&document.querySelector('[data-tab="merchant"].active'))render();else updateUi()},500);updateBadge();
window.buyMerchantOffer=buy;window.AfterlightMerchant={render,buy,award,multiplier,rarityWeights,remaining,activeOffers:()=>activeOffers().map(offer=>({...offer,remaining:remaining(offer.id)})),offers:()=>OFFERS.map(offer=>({...offer}))};
})();
