(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState,NUM=window.AfterlightNumbers,GAME=window.AfterlightGame;if(!CFG||!ST||!NUM||!GAME)throw new Error('Offline earnings dependencies missing');
const S=ST.get(),RULES=CFG.OFFLINE,RESOURCES=['coins','food','water','power','scrap','science'];
const elapsedForLoad=()=>{if(['localhost','127.0.0.1'].includes(location.hostname)){const test=Number(new URLSearchParams(location.search).get('offlineSeconds'));if(Number.isFinite(test)&&test>0)return test*1000}return ST.offlineElapsedMs};
const duration=seconds=>{seconds=Math.max(0,Math.floor(seconds));const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return hours?`${hours}H ${minutes}M`:minutes?`${minutes}M`:`${seconds}S`};
function permanentRates(){const live=GAME.rates(),out={};for(const resource of RESOURCES){const dealer=Math.max(1,Number(window.AfterlightMerchant?.multiplier?.(resource)||1));out[resource]=Math.max(0,Number(live[resource])||0)/dealer}return out}
function calculate(elapsedMs=elapsedForLoad()){elapsedMs=Math.max(0,Number(elapsedMs)||0);if(elapsedMs<RULES.minimumAwayMs)return null;const usedMs=Math.min(elapsedMs,RULES.maximumAwayMs),seconds=usedMs/1000,efficiency=Math.min(RULES.maximumEfficiency,RULES.baseEfficiency*ST.bonus('offlineMult')),rates=permanentRates(),gains={};for(const resource of RESOURCES)gains[resource]=rates[resource]*seconds*efficiency;return{seconds,elapsedSeconds:elapsedMs/1000,efficiency,gains,capped:elapsedMs>RULES.maximumAwayMs,createdAt:Date.now()}}
function mergePending(fresh){if(!fresh)return S.offline.pending;ST.update('offline-pending',state=>{const old=state.offline.pending||{seconds:0,elapsedSeconds:0,gains:{},createdAt:fresh.createdAt};const gains={};for(const resource of RESOURCES)gains[resource]=(Number(old.gains?.[resource])||0)+(Number(fresh.gains[resource])||0);state.offline.pending={seconds:(Number(old.seconds)||0)+fresh.seconds,elapsedSeconds:(Number(old.elapsedSeconds)||0)+fresh.elapsedSeconds,efficiency:fresh.efficiency,gains,capped:!!old.capped||fresh.capped,createdAt:old.createdAt||fresh.createdAt}});return S.offline.pending}
function render(){const modal=document.getElementById('offline'),pending=S.offline?.pending;if(!modal||!pending)return false;const text=document.getElementById('offlineText'),gain=document.getElementById('offlineGain'),button=document.getElementById('offlineCollect');text.textContent=`${duration(pending.seconds)} PRODUCTION · ${Math.round(pending.efficiency*100)}% EFFICIENCY${pending.capped?' · 12H CAP REACHED':''}`;gain.innerHTML=RESOURCES.filter(resource=>(pending.gains?.[resource]||0)>0).map(resource=>`<span>+${NUM.format(pending.gains[resource])} ${resource.toUpperCase()}</span>`).join('');button.onclick=collect;modal.classList.remove('hidden');document.body.dataset.offlinePending='true';return true}
function collect(){const pending=S.offline?.pending;if(!pending)return false;ST.update('offline-collect',state=>{for(const resource of RESOURCES)state[resource]=(state[resource]||0)+(Number(pending.gains?.[resource])||0);state.total=(state.total||0)+(Number(pending.gains?.coins)||0);state.offline.totalClaims=(state.offline.totalClaims||0)+1;state.offline.totalSeconds=(state.offline.totalSeconds||0)+(Number(pending.seconds)||0);state.offline.pending=null});document.getElementById('offline')?.classList.add('hidden');document.body.dataset.offlinePending='false';GAME.hud();window.dispatchEvent(new CustomEvent('afterlight:offline-collected',{detail:{...pending}}));return true}
document.body.dataset.offlineSystem='ready';mergePending(calculate());render();
window.AfterlightOffline={calculate,collect,render,permanentRates,rules:()=>({...RULES}),pending:()=>S.offline?.pending?JSON.parse(JSON.stringify(S.offline.pending)):null};
})();

