(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState;if(!CFG||!ST)throw new Error('Room operations dependencies missing');
const S=ST.get(),ROOMS=CFG.ROOMS,RULES=CFG.OPERATIONS||{},ECONOMY=CFG.ROOM_ECONOMY||{},MILESTONES=CFG.ROOM_MILESTONES||[],RESOURCES=['power','water','food','scrap','science','workforce'],OUTPUTS=['coins','food','water','power','scrap','science'];
const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,Number(value)||0));
function mastery(level){const size=Math.max(1,Number(ECONOMY.masterySize)||100),value=Math.max(0,Math.floor(Number(level)||0));if(!value)return{rank:1,local:0,size};return{rank:1+Math.floor((value-1)/size),local:1+(value-1)%size,size}}
function milestoneMultiplier(level){const local=mastery(level).local;let value=1;for(const item of MILESTONES)if(local>=item.level)value=item.multiplier;return value}
function loadFactor(level){const data=mastery(level);if(!data.local)return 0;const final=MILESTONES[MILESTONES.length-1],rankScale=data.size*Math.pow(Number(ECONOMY.rateGrowth)||1.07,data.size-1)*(Number(final?.multiplier)||1);return Math.pow(rankScale,data.rank-1)*data.local*Math.pow(Number(ECONOMY.rateGrowth)||1.07,Math.max(0,data.local-1))*milestoneMultiplier(level)}
function priority(id){const value=S.operations?.priorities?.[id];return RULES.priorities?.[value]?value:(RULES.defaultPriority?.[id]||'normal')}
function paused(id){return S.operations?.paused?.[id]===true}
function roomDemands(id){const level=Number(S.rooms?.[id])||0,factor=loadFactor(level),definition=RULES.roomNeeds?.[id]||{},out={};for(const [resource,coefficient] of Object.entries(definition))out[resource]=Math.max(0,Number(coefficient)||0)*factor;return out}
function supplyFor(resource,roomRates,specialRates,efficiencies){let value=Math.max(0,Number(specialRates?.[resource])||0);for(const id of Object.keys(ROOMS)){const efficiency=clamp(efficiencies[id]);value+=Math.max(0,Number(roomRates?.[id]?.[resource])||0)*efficiency}if(resource==='workforce'){const livingLevel=Number(S.rooms?.living)||0;value=(Number(RULES.workforceBase)||0)+loadFactor(livingLevel)*(Number(RULES.workforcePerLoad)||0)*clamp(efficiencies.living)}return value}
function allocate(roomRates,specialRates,efficiencies){const ratios={},allocations={},supply={},available={};for(const id of Object.keys(ROOMS)){ratios[id]={};allocations[id]={}}
  for(const resource of RESOURCES){supply[resource]=supplyFor(resource,roomRates,specialRates,efficiencies);const stock=resource==='workforce'?0:Math.max(0,Number(S[resource])||0),reserve=stock/Math.max(1,Number(RULES.reserveSeconds)||300);available[resource]=supply[resource]+reserve;let remaining=available[resource];const consumers=Object.keys(ROOMS).filter(id=>(Number(S.rooms?.[id])||0)>0&&!paused(id)&&(roomDemands(id)[resource]||0)>0).sort((a,b)=>(RULES.priorities?.[priority(b)]||0)-(RULES.priorities?.[priority(a)]||0));for(const id of consumers){const demand=roomDemands(id)[resource],granted=Math.min(demand,Math.max(0,remaining));remaining-=granted;allocations[id][resource]=granted;ratios[id][resource]=demand?clamp(granted/demand):1}}
  return{ratios,allocations,supply,available}
}
function evaluate(roomRates={},specialRates={}){let efficiencies={};for(const id of Object.keys(ROOMS))efficiencies[id]=(Number(S.rooms?.[id])||0)>0&&!paused(id)?1:0;let allocation=null;for(let pass=0;pass<4;pass++){allocation=allocate(roomRates,specialRates,efficiencies);const next={};for(const id of Object.keys(ROOMS)){const built=(Number(S.rooms?.[id])||0)>0;if(!built||paused(id)){next[id]=0;continue}const values=Object.values(allocation.ratios[id]);const supplied=values.length?Math.min(...values):1,nextValue=Math.max(Number(RULES.recoveryFloor?.[id])||0,supplied);next[id]=clamp(nextValue)}efficiencies=next}
  allocation=allocate(roomRates,specialRates,efficiencies);const rooms={},consumption={power:0,water:0,food:0,scrap:0,science:0},rates={coins:0,food:0,water:0,power:0,scrap:0,science:0};for(const output of OUTPUTS)rates[output]=Math.max(0,Number(specialRates?.[output])||0);
  for(const id of Object.keys(ROOMS)){const built=(Number(S.rooms?.[id])||0)>0,demand=roomDemands(id),ratios=allocation.ratios[id],efficiency=clamp(efficiencies[id]);for(const output of OUTPUTS)rates[output]+=Math.max(0,Number(roomRates?.[id]?.[output])||0)*efficiency;const needs=Object.entries(demand).map(([resource,required])=>{const ratio=clamp(ratios[resource]??1),supplied=required*Math.min(efficiency,ratio);if(resource!=='workforce')consumption[resource]=(consumption[resource]||0)+supplied;return{resource,required,supplied,ratio}}),shortages=needs.filter(need=>need.ratio<(Number(RULES.warningEfficiency)||.9)).sort((a,b)=>a.ratio-b.ratio),state=!built?'unbuilt':paused(id)?'paused':efficiency<(Number(RULES.criticalEfficiency)||.5)?'critical':efficiency<(Number(RULES.warningEfficiency)||.9)?'strained':'optimal',bottleneck=shortages[0]?.resource||null;rooms[id]={id,built,paused:paused(id),priority:priority(id),efficiency,state,needs,bottleneck,recommendation:bottleneck?RULES.recommendations?.[bottleneck]||'Rebalance room priorities.':'All required bunker systems are supplied.'}}
  for(const resource of Object.keys(consumption))rates[resource]-=consumption[resource]||0;const active=Object.values(rooms).filter(room=>room.built),alerts=active.filter(room=>!['optimal'].includes(room.state));return{rates,rooms,consumption,supply:allocation.supply,workforce:{available:allocation.supply.workforce,demand:Object.values(rooms).reduce((sum,room)=>sum+(room.needs.find(need=>need.resource==='workforce')?.required||0),0)},summary:{active:active.length,alerts:alerts.length,critical:alerts.filter(room=>['critical','paused'].includes(room.state)).length,efficiency:active.length?active.reduce((sum,room)=>sum+room.efficiency,0)/active.length:1}}
}
function setPriority(id,value){if(!ROOMS[id]||!RULES.priorities?.[value])return false;ST.update('operations-priority',state=>{state.operations.priorities[id]=value});window.dispatchEvent(new CustomEvent('afterlight:operations-changed',{detail:{id,priority:value,paused:paused(id)}}));return true}
function togglePaused(id){if(!ROOMS[id]||(Number(S.rooms?.[id])||0)<1)return false;ST.update('operations-pause',state=>{state.operations.paused[id]=!state.operations.paused[id]});window.dispatchEvent(new CustomEvent('afterlight:operations-changed',{detail:{id,priority:priority(id),paused:paused(id)}}));return true}
window.AfterlightOperations={evaluate,loadFactor,roomDemands,priority,paused,setPriority,togglePaused,resources:[...RESOURCES]};
document.body.dataset.operationsSystem='ready';
})();
