(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState,NUM=window.AfterlightNumbers;if(!CFG||!ST||!NUM||!CFG.PRESTIGE)throw new Error('Prestige dependencies missing');
const S=ST.get(),C=CFG.PRESTIGE,BACKUP_KEY='afterlight_prestige_backup_v1',fmt=NUM.format,escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const data=()=>S.prestige,level=()=>Math.max(0,Math.min(C.maximumLevel,Math.floor(Number(data().level)||0))),definition=value=>C.levels.find(item=>item.level===value)||null,skin=id=>CFG.SURVIVOR_SKINS.find(item=>item.id===id)||null,room=id=>C.rooms.find(item=>item.id===id)||null;
const next=()=>definition(level()+1),target=()=>next()?C.targets[level()]:null,eligible=()=>!!next()&&S.bunker>=target();
function coreReward(){const required=target();if(!required)return 0;return Math.min(C.maximumCoreReward,1+Math.floor(Math.max(0,S.bunker-required)/C.extraCoreEvery))}
function activeSkin(){const selected=skin(S.survivorSkins?.selected);return selected&&S.survivorSkins?.unlocked?.includes(selected.id)?selected:null}
const activePerk=()=>activeSkin()?.perk?.type==='prestige'?activeSkin().perk.id:'';
const active=id=>activePerk()===id;
const permanentEconomyMultiplier=()=>Math.pow(C.economyPerLevel,level())*(1+level()*C.rosterBonusPerLevel);
const economyMultiplier=()=>permanentEconomyMultiplier();
const resourceMultiplier=resource=>economyMultiplier()*(resource==='scrap'&&active('salvage-discipline')?1.4:1);
const roomCostMultiplier=()=>active('master-builder') ? .88 : 1;
const warMultiplier=()=>1+Math.max(0,Number(data().rooms['war-room'])||0)*.08;
const damageMultiplier=()=>Math.pow(C.damagePerLevel,level())*(active('hordebreaker')?1.5:1)*warMultiplier();
const zombieMultiplier=()=> (active('hordebreaker')?1.5:1)*warMultiplier();
const expeditionTimeMultiplier=()=>Math.max(.45,(active('field-command') ? .75 : 1)*(1-Math.max(0,Number(data().rooms['command-relay'])||0)*.1));
const expeditionRewardMultiplier=()=> (active('field-command')?1.3:1)*(1+Math.max(0,Number(data().rooms['command-relay'])||0)*.1);
const researchCostMultiplier=()=>active('last-light') ? .75 : 1;
const researchTimeMultiplier=()=>active('last-light') ? .75 : 1;
const criticalMultiplier=()=>active('last-light')?1.5:1;
const scrapRetention=()=>Math.min(.24,Math.max(0,Number(data().rooms['legacy-vault'])||0)*.08);
function multiplierSummary(atLevel=level()){return{economy:Math.pow(C.economyPerLevel,atLevel)*(1+atLevel*C.rosterBonusPerLevel),damage:Math.pow(C.damagePerLevel,atLevel),roster:1+atLevel*C.rosterBonusPerLevel}}
function runTargets(atLevel=level()){return{roomUpgrades:20+atLevel*10,kills:30+atLevel*20,researchClaims:2+atLevel,hordes:1+Math.ceil(atLevel/2),bunker:18+atLevel*8}}
function contractProgress(){const targets=runTargets(),run=data().run;return C.contracts.map(contract=>{const value=contract.metric==='bunker'?S.bunker:Math.max(0,Number(run[contract.metric])||0),goal=targets[contract.metric];return{...contract,value,goal,complete:value>=goal,ratio:Math.min(1,value/goal)}})}
const contractsComplete=()=>level()>0&&contractProgress().every(item=>item.complete);
function claimContracts(){if(data().run.contractClaimed||!contractsComplete())return false;ST.update('prestige-contract',state=>{state.prestige.cores+=1;state.prestige.run.contractClaimed=true});window.dispatchEvent(new CustomEvent('afterlight:prestige-contract',{detail:{cores:1}}));refresh();return true}
function resetPreview(){const nextLevel=next(),retain=Math.floor(S.scrap*scrapRetention()),reward=coreReward(),preserved=data().archive.filter(id=>Number(S.research[id])>0).slice(0,data().rooms['archive-core']);return{nextLevel,target:target(),reward,retain,preserved,kept:['Uranium Crystals','Missions and permanent mission bonuses','Specialists and discovered infected','Dealer boosts and active expeditions','Lifetime statistics and every unlocked survivor','Prestige Cores and Prestige Rooms'],lost:['Coins, Food, Water, Power and Science','Normal and specialist room levels','Current-run infected kills','Unarchived research levels','Active research and unclaimed offline income']}}
function performReset(){if(!eligible())return false;const preview=resetPreview(),unlock=skin(preview.nextLevel.survivor),now=Date.now(),snapshot=ST.snapshot();localStorage.setItem(BACKUP_KEY,JSON.stringify({savedAt:now,state:snapshot}));try{ST.update('prestige-reset',state=>{const p=state.prestige,archived={};for(const id of preview.preserved)archived[id]=Math.max(0,Number(state.research[id])||0);p.bestBunker=Math.max(Number(p.bestBunker)||1,state.bunker);p.level=preview.nextLevel.level;p.cores+=preview.reward;p.totalResets+=1;p.lastAt=now;p.lastReward=preview.reward;p.run={startedAt:now,roomUpgrades:0,researchClaims:0,hordes:0,brutes:0,expeditions:0,contractClaimed:false};state.stats.prestigeResets=Math.max(Number(state.stats.prestigeResets)||0,p.totalResets);state.coins=0;state.food=0;state.water=0;state.power=0;state.scrap=preview.retain;state.science=0;state.kills=0;for(const id of Object.keys(state.rooms))state.rooms[id]=id==='generator'?1:0;for(const id of Object.keys(state.specialRooms||{}))state.specialRooms[id]=0;for(const id of Object.keys(state.research))state.research[id]=archived[id]||0;state.researchRuntime.active=null;state.researchRuntime.ready=null;state.offline.pending=null;state.carePackage.active=null;state.carePackage.nextAt=now+(CFG.CARE_PACKAGE?.minimumIntervalMs||90000);state.survivorSkins.unlocked=[...new Set([...state.survivorSkins.unlocked,unlock.id])];state.survivorSkins.selected=unlock.id;state.command.lastTab='prestige'});if(level()!==preview.nextLevel.level)throw new Error('Prestige save verification failed')}catch(error){localStorage.setItem(ST.KEY,JSON.stringify(snapshot));throw error}window.dispatchEvent(new CustomEvent('afterlight:prestige-complete',{detail:{level:level(),reward:preview.reward,survivor:unlock,room:room(preview.nextLevel.room),multipliers:multiplierSummary()}}));window.AfterlightGame?.recalc?.();window.AfterlightGame?.spawn?.();window.AfterlightGame?.renderRooms?.();window.AfterlightGame?.hud?.();window.AfterlightCommandCenter?.render?.();reveal(unlock,preview.nextLevel);return true}
function upgradeRoom(id){const entry=room(id),current=Math.max(0,Number(data().rooms[id])||0),cost=C.roomCosts[current];if(!entry||level()<entry.level||current>=C.roomMaximumLevel||data().cores<cost)return false;ST.update('prestige-room',state=>{state.prestige.cores-=cost;state.prestige.rooms[id]=current+1});window.dispatchEvent(new CustomEvent('afterlight:prestige-room',{detail:{id,level:current+1,cost}}));refresh();return true}
function toggleAutomation(id){const capacity=data().rooms['automation-bay'];if(!capacity||!CFG.ROOMS[id])return false;const targets=[...data().automation.targets],index=targets.indexOf(id);if(index>=0)targets.splice(index,1);else if(targets.length<capacity)targets.push(id);else return false;ST.update('prestige-automation',state=>{state.prestige.automation.targets=targets;state.prestige.automation.enabled=targets.length>0});refresh();return true}
function toggleArchive(id){const capacity=data().rooms['archive-core'];if(!capacity||!CFG.RESEARCH.some(item=>item.id===id)||!Number(S.research[id]))return false;const ids=[...data().archive],index=ids.indexOf(id);if(index>=0)ids.splice(index,1);else if(ids.length<capacity)ids.push(id);else return false;ST.update('prestige-archive',state=>{state.prestige.archive=ids});refresh();return true}
function roomEffect(entry,current){if(entry.id==='legacy-vault')return current?`${current*8}% SCRAP KEPT ON RESET`:'8% SCRAP RETENTION AT LEVEL 1';if(entry.id==='automation-bay')return current?`${current} AUTO-UPGRADE TARGET${current===1?'':'S'}`:'1 AUTOMATION TARGET AT LEVEL 1';if(entry.id==='command-relay')return current?`${current*10}% FASTER · +${current*10}% EXPEDITION LOOT`:'10% FASTER · +10% LOOT AT LEVEL 1';if(entry.id==='war-room')return current?`+${current*8}% DAMAGE & INFECTED LOOT`:'+8% DAMAGE & LOOT AT LEVEL 1';return current?`${current} RESEARCH PROJECT${current===1?'':'S'} PRESERVED`:'PRESERVE 1 RESEARCH PROJECT AT LEVEL 1'}
function roomsMarkup(){return `<section class="prestigeWing"><header><div><small>PERMANENT BUNKER WING</small><h3>PRESTIGE ROOMS</h3></div><b>◆ ${data().cores} CORES</b></header><div class="prestigeRoomGrid">${C.rooms.map(entry=>{const current=data().rooms[entry.id],locked=level()<entry.level,max=current>=C.roomMaximumLevel,cost=C.roomCosts[current];return `<article class="prestigeRoom ${locked?'locked':''}"><i>${entry.icon}</i><small>PRESTIGE ${entry.level}</small><h4>${entry.name}</h4><p>${entry.effect}</p><strong>${roomEffect(entry,current)}</strong><footer><span>LV ${current} / ${C.roomMaximumLevel}</span><button type="button" data-prestige-room="${entry.id}" ${locked||max||data().cores<cost?'disabled':''}>${locked?'LOCKED':max?'MAXED':'UPGRADE · '+cost+' ◆'}</button></footer></article>`}).join('')}</div>${automationMarkup()}${archiveMarkup()}</section>`}
function automationMarkup(){const capacity=data().rooms['automation-bay'];if(!capacity)return'';return `<section class="prestigeConfigurator"><header><b>⚙ AUTOMATION TARGETS</b><span>${data().automation.targets.length} / ${capacity} ASSIGNED</span></header><p>The bay buys one affordable level every four seconds. It never spends resources other than Coins.</p><div>${Object.entries(CFG.ROOMS).map(([id,item])=>`<button type="button" data-prestige-auto="${id}" class="${data().automation.targets.includes(id)?'selected':''}">${item.icon} ${item.name}</button>`).join('')}</div></section>`}
function archiveMarkup(){const capacity=data().rooms['archive-core'];if(!capacity)return'';return `<section class="prestigeConfigurator"><header><b>✦ ARCHIVE SLOTS</b><span>${data().archive.length} / ${capacity} STORED</span></header><p>Selected completed projects keep their full level after the next Prestige reset.</p><div>${CFG.RESEARCH.map(item=>`<button type="button" data-prestige-archive="${item.id}" class="${data().archive.includes(item.id)?'selected':''}" ${!Number(S.research[item.id])?'disabled':''}>${item.icon} ${item.name} · LV ${Number(S.research[item.id])||0}</button>`).join('')}</div></section>`}
function contractsMarkup(){if(!level())return'';const progress=contractProgress(),claimed=data().run.contractClaimed;return `<section class="cycleContracts"><header><div><small>CURRENT CYCLE</small><h3>CYCLE CONTRACTS</h3></div><b>${claimed?'CORE SECURED':progress.filter(item=>item.complete).length+' / '+progress.length+' COMPLETE'}</b></header><p>Finish all five before the next reset to recover one bonus Prestige Core.</p><div>${progress.map(item=>`<article class="${item.complete?'complete':''}"><i>${item.complete?'✓':item.icon}</i><span><b>${item.name}</b><small>${fmt(item.value)} / ${fmt(item.goal)}</small></span><em><u style="width:${item.ratio*100}%"></u></em></article>`).join('')}</div><button type="button" class="contractClaim" data-prestige-contract ${!contractsComplete()||claimed?'disabled':''}>${claimed?'BONUS CORE CLAIMED':contractsComplete()?'CLAIM BONUS PRESTIGE CORE':'COMPLETE ALL CONTRACTS'}</button></section>`}
function panel(){const current=level(),nextLevel=next(),required=target(),progress=nextLevel?Math.min(100,S.bunker/required*100):100,now=multiplierSummary(),future=multiplierSummary(Math.min(C.maximumLevel,current+1));return `<section class="prestigePanel" data-prestige-system="ready"><header class="prestigeHero"><div><small>AFTERLIGHT LEGACY PROGRAM</small><h2>PRESTIGE ${current} / ${C.maximumLevel}</h2><p>Restart the bunker, keep your legacy and make every future cycle permanently stronger.</p></div><span>◆ ${data().cores} PRESTIGE CORES</span></header><section class="prestigeMultipliers"><article><small>ALL PRODUCTION</small><b>×${now.economy.toFixed(2)}</b><em>${nextLevel?'NEXT ×'+future.economy.toFixed(2):'MAXIMUM LEGACY'}</em></article><article><small>MANUAL DAMAGE</small><b>×${now.damage.toFixed(2)}</b><em>${nextLevel?'NEXT ×'+future.damage.toFixed(2):'MAXIMUM LEGACY'}</em></article><article><small>ROSTER LEGACY</small><b>+${Math.round((now.roster-1)*100)}%</b><em>+5% PER PRESTIGE SURVIVOR</em></article></section>${nextLevel?`<section class="prestigeAscend" style="--prestige-accent:${nextLevel.accent}"><div class="prestigeTarget"><small>NEXT CYCLE · ${nextLevel.title}</small><h3>BUNKER LEVEL ${required}</h3><div><i style="width:${progress}%"></i></div><span>${Math.min(S.bunker,required)} / ${required} · ${coreReward()} CORE${coreReward()===1?'':'S'} ON RESET</span></div><div class="prestigeUnlockPreview"><img src="${skin(nextLevel.survivor).asset}" alt="Next Prestige survivor"><span><small>PERMANENT SURVIVOR</small><b>${escape(skin(nextLevel.survivor).name)}</b><em>${escape(skin(nextLevel.survivor).perk.label)}</em></span></div><button type="button" data-prestige-open ${eligible()?'':'disabled'}>${eligible()?'BEGIN PRESTIGE '+nextLevel.level:'REACH BUNKER '+required}</button></section>`:`<section class="prestigeMaximum"><i>✦</i><small>FINAL PROTOCOL COMPLETE</small><h3>THE AFTERLIGHT LEGACY IS SECURE</h3><p>All five survivors and every Prestige Wing room are now permanently available.</p></section>`}${contractsMarkup()}${roomsMarkup()}</section>`}
function confirmation(){const preview=resetPreview(),nextSkin=skin(preview.nextLevel.survivor),overlay=document.createElement('section');overlay.className='prestigeConfirm';overlay.dataset.prestigeConfirmation='ready';overlay.innerHTML=`<div class="prestigeConfirmCard"><button type="button" data-prestige-cancel aria-label="Cancel Prestige">×</button><small>POINT OF NO RETURN · PRESTIGE ${preview.nextLevel.level}</small><h2>BEGIN A NEW CYCLE?</h2><div class="prestigeConfirmSurvivor"><img src="${nextSkin.asset}" alt="${escape(nextSkin.name)}"><span><b>${escape(nextSkin.name)} JOINS PERMANENTLY</b><em>${escape(nextSkin.perk.label)}</em></span></div><div class="prestigeKeepLose"><article><b>YOU KEEP</b>${preview.kept.map(item=>`<span>✓ ${item}</span>`).join('')}</article><article><b>THIS CYCLE RESETS</b>${preview.lost.map(item=>`<span>× ${item}</span>`).join('')}</article></div><p>Legacy Vault keeps <b>${fmt(preview.retain)} Scrap</b>. Archive Core keeps <b>${preview.preserved.length} research project${preview.preserved.length===1?'':'s'}</b>. You receive <b>${preview.reward} Prestige Core${preview.reward===1?'':'s'}</b>.</p><button type="button" class="prestigeHold" data-prestige-hold><i></i><span>HOLD TO RESTART · 1.5 SECONDS</span></button><em>Release early to cancel. A recovery backup is written before anything changes.</em></div>`;document.body.append(overlay);requestAnimationFrame(()=>overlay.classList.add('show'));overlay.querySelector('[data-prestige-cancel]').onclick=()=>overlay.remove();bindHold(overlay.querySelector('[data-prestige-hold]'));return overlay}
function bindHold(button){let timer=0,start=()=>{if(timer)return;button.classList.add('holding');timer=setTimeout(()=>{timer=0;button.disabled=true;performReset();button.closest('.prestigeConfirm')?.remove()},1500)},cancel=()=>{if(!timer)return;clearTimeout(timer);timer=0;button.classList.remove('holding')};button.addEventListener('pointerdown',event=>{event.preventDefault();start()});for(const name of ['pointerup','pointercancel','pointerleave'])button.addEventListener(name,cancel);button.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&!event.repeat){event.preventDefault();start()}});button.addEventListener('keyup',cancel)}
function reveal(unlocked,levelDef){document.querySelector('.prestigeReveal')?.remove();const mult=multiplierSummary(),element=document.createElement('section');element.className='prestigeReveal';element.style.setProperty('--prestige-accent',levelDef.accent);element.innerHTML=`<div class="prestigeRevealCard"><div class="prestigeBurst"></div><small>PRESTIGE ${levelDef.level} COMPLETE</small><h2>${levelDef.title}</h2><img src="${unlocked.asset}" alt="${escape(unlocked.name)} unlocked"><h3>${escape(unlocked.name)}</h3><b>${escape(unlocked.tier)} · ${escape(unlocked.callsign)}</b><p>${escape(unlocked.description)}</p><strong>${escape(unlocked.perk.label)}</strong><div><span>×${mult.economy.toFixed(2)} ALL PRODUCTION</span><span>×${mult.damage.toFixed(2)} MANUAL DAMAGE</span></div><button type="button">ENTER THE NEW CYCLE</button></div>`;document.body.append(element);requestAnimationFrame(()=>element.classList.add('show'));element.querySelector('button').onclick=()=>element.remove()}
function bind(root=document.getElementById('drawerBody')){root?.querySelector('[data-prestige-open]')?.addEventListener('click',confirmation);root?.querySelectorAll('[data-prestige-room]').forEach(button=>button.addEventListener('click',()=>upgradeRoom(button.dataset.prestigeRoom)));root?.querySelectorAll('[data-prestige-auto]').forEach(button=>button.addEventListener('click',()=>toggleAutomation(button.dataset.prestigeAuto)));root?.querySelectorAll('[data-prestige-archive]').forEach(button=>button.addEventListener('click',()=>toggleArchive(button.dataset.prestigeArchive)));root?.querySelector('[data-prestige-contract]')?.addEventListener('click',claimContracts)}
function refresh(){if(S.command?.lastTab==='prestige'&&document.querySelector('[data-command-panel]'))window.AfterlightCommandCenter?.render?.();window.AfterlightGame?.hud?.()}
function addRun(metric,amount=1){if(!level())return;ST.update('prestige-progress',state=>{state.prestige.run[metric]=Math.max(0,(Number(state.prestige.run[metric])||0)+Math.max(0,Number(amount)||0))},{notifyNow:false})}
window.addEventListener('afterlight:room-upgraded',event=>addRun('roomUpgrades',event.detail?.count||1));
window.addEventListener('afterlight:research-claimed',()=>addRun('researchClaims',1));
window.addEventListener('afterlight:enemy-killed',event=>{addRun('kills',event.detail?.killsAdded||1);if(event.detail?.horde)addRun('hordes',1);if(event.detail?.brute)addRun('brutes',1)});
window.addEventListener('afterlight:expedition-complete',()=>addRun('expeditions',1));
setInterval(()=>{if(!data().automation.enabled||!data().automation.targets.length||!window.AfterlightGame)return;for(const id of data().automation.targets){const cost=window.AfterlightGame.roomCost(id),entry=CFG.ROOMS[id];if(entry&&S.bunker>=entry.unlock&&Number.isFinite(cost)&&S.coins>=cost){window.AfterlightGame.buyRoom(id,1);break}}},4000);
document.body.dataset.prestigeSystem='ready';
window.AfterlightPrestige={level,next,target,eligible,coreReward,activeSkin,activePerk,economyMultiplier,permanentEconomyMultiplier,resourceMultiplier,roomCostMultiplier,damageMultiplier,zombieMultiplier,expeditionTimeMultiplier,expeditionRewardMultiplier,researchCostMultiplier,researchTimeMultiplier,criticalMultiplier,scrapRetention,multiplierSummary,runTargets,contractProgress,contractsComplete,claimContracts,resetPreview,performReset,upgradeRoom,toggleAutomation,toggleArchive,panel,bind,confirmation,refresh};
})();
