(()=>{'use strict';
const CFG=window.BunkrConfig,ST=window.BunkrState,NUM=window.BunkrNumbers;if(!CFG||!ST||!NUM)throw new Error('Research dependencies missing');
const S=ST.get(),R=S.researchRuntime,DEFS=CFG.RESEARCH||[],BRANCHES=CFG.RESEARCH_BRANCHES||[];
const fmt=NUM.format,def=id=>DEFS.find(item=>item.id===id)||null,branch=id=>BRANCHES.find(item=>item.id===id)||null;
let selectedId=R.ready?.id||R.active?.id||DEFS[0]?.id||null,activeBranch=def(selectedId)?.branch||BRANCHES[0]?.id||'survival';
const level=id=>Math.max(0,Math.floor(Number(S.research?.[id])||0));
const maximum=item=>Math.max(1,Math.floor(Number(item?.maxLevel)||1));
const prestigeLevel=()=>Math.max(0,Math.floor(Number(S.prestige?.level)||0));
const multiplier=id=>{const item=def(id);return item?Math.pow(Number(item.effect)||1,level(id)):1};
const cost=item=>Math.max(1,Math.round(item.baseCost*Math.pow(item.costGrowth,level(item.id))*(window.BunkrPrestige?.researchCostMultiplier?.()||1)));
const scienceCost=item=>Math.max(1,Math.round(item.scienceCost*Math.pow(item.scienceGrowth,level(item.id))*(window.BunkrPrestige?.researchCostMultiplier?.()||1)));
const researchTimeMultiplier=()=>Math.pow(.92,level('archiveProtocol'));
const seconds=item=>Math.max(1,Math.min(21600,Math.round(item.baseSeconds*Math.pow(item.timeGrowth,level(item.id))*(window.BunkrPrestige?.researchTimeMultiplier?.()||1)*researchTimeMultiplier())));
const duration=value=>{value=Math.max(0,Math.ceil(value));const h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=value%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:m?`${m}m ${String(s).padStart(2,'0')}s`:`${s}s`};
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function requirements(item){return(item?.requires||[]).map(requirement=>({...requirement,item:def(requirement.id),current:level(requirement.id)}))}
function unmetRequirements(item){return requirements(item).filter(requirement=>requirement.current<requirement.level)}
function labReason(){return S.rooms&&Object.prototype.hasOwnProperty.call(S.rooms,'lab')&&!Number(S.rooms.lab)?'BUILD THE RESEARCH LAB':''}
function lockReason(item){if(!item)return'UNKNOWN PROJECT';if(level(item.id)>=maximum(item))return'MAXIMUM LEVEL REACHED';if(prestigeLevel()<Number(item.prestige||0))return`PRESTIGE ${item.prestige} REQUIRED`;const unmet=unmetRequirements(item);if(unmet.length)return`${unmet[0].item?.name||unmet[0].id} LEVEL ${unmet[0].level} REQUIRED`;return labReason()}
function nodeState(item){if(R.ready?.id===item.id)return'ready';if(R.active?.id===item.id)return'researching';if(level(item.id)>=maximum(item))return'completed';if(lockReason(item))return'locked';if(R.active||R.ready)return'busy';return'available'}
function canAfford(item){return S.scrap>=cost(item)&&S.science>=scienceCost(item)}
function effectSummary(item,lv=level(item.id)){const current=Math.min(lv,maximum(item)),next=Math.min(maximum(item),current+1);return{current:`LEVEL ${current} / ${maximum(item)}`,next:current>=maximum(item)?'FULLY MASTERED':`${item.benefit} · NEXT LEVEL ${next}`}}
function start(id){const item=def(id);if(!item||R.active||R.ready||lockReason(item))return false;const scrapPrice=cost(item),sciencePrice=scienceCost(item);if(S.scrap<scrapPrice||S.science<sciencePrice)return false;const now=Date.now(),time=seconds(item);let started=false;ST.update('research-start',state=>{if(R.active||R.ready||state.scrap<scrapPrice||state.science<sciencePrice)return;state.scrap-=scrapPrice;state.science-=sciencePrice;R.active={id,start:now,end:now+time*1000,cost:scrapPrice,scrapCost:scrapPrice,scienceCost:sciencePrice};started=true});if(!started)return false;selectedId=id;activeBranch=item.branch;render();window.BunkrGame?.hud?.();return true}
function finish(){if(!R.active||Date.now()<R.active.end)return false;const active={...R.active};ST.update('research-complete',()=>{R.active=null;R.ready={id:active.id,finishedAt:Date.now(),cost:active.scrapCost||active.cost,scienceCost:active.scienceCost||0}});selectedId=active.id;activeBranch=def(active.id)?.branch||activeBranch;window.dispatchEvent(new CustomEvent('bunkr:research-complete',{detail:{id:active.id,level:level(active.id)+1}}));render();return true}
function claim(){const ready=R.ready,item=def(ready?.id);if(!ready||!item)return false;ST.update('research-claim',()=>{S.research[item.id]=Math.min(maximum(item),level(item.id)+1);R.ready=null});window.dispatchEvent(new CustomEvent('bunkr:research-claimed',{detail:{id:item.id,level:level(item.id)}}));render();window.BunkrGame?.hud?.();window.BunkrGame?.renderRooms?.();return true}
function badge(){const element=document.getElementById('researchBadge');if(!element)return;element.textContent=R.ready?'!':'';element.classList.toggle('visible',!!R.ready)}
function activeProgress(now=Date.now()){if(!R.active)return null;const total=Math.max(1,R.active.end-R.active.start),left=Math.max(0,R.active.end-now),ratio=Math.max(0,Math.min(1,(now-R.active.start)/total));return{left,ratio,percent:Math.floor(ratio*100)}}
function activityMarkup(){if(R.ready){const item=def(R.ready.id);return`<section class="researchActivity ready"><span><small>BREAKTHROUGH READY</small><b>${escape(item?.name)}</b></span><div class="researchActivityTrack"><i style="width:100%"></i></div><strong>100%</strong><button type="button" data-research-claim>INSTALL</button></section>`}if(R.active){const item=def(R.active.id),progress=activeProgress();return`<section class="researchActivity active"><span><small>ACTIVE RESEARCH</small><b>${escape(item?.name)}</b></span><div class="researchActivityTrack"><i data-research-progress style="width:${progress.percent}%"></i></div><strong data-research-percent>${progress.percent}%</strong><em data-research-time>${duration(progress.left/1000)}</em></section>`}return`<section class="researchActivity idle"><span><small>LAB STATUS</small><b>AWAITING PROJECT</b></span><div class="researchActivityTrack"><i></i></div><strong>READY</strong><em>SELECT A NODE</em></section>`}
function nodeMarkup(item){const state=nodeState(item),lv=level(item.id),reason=lockReason(item),selected=selectedId===item.id,progress=R.active?.id===item.id?activeProgress():null;return`<button type="button" class="researchNode ${state} ${selected?'selected':''}" data-research-node="${item.id}" data-research-tier="${item.tier}" aria-pressed="${selected}" aria-label="${escape(item.name)}. ${reason||state}"><i>${item.icon}</i><span><b>${escape(item.name)}</b><small>${state==='locked'?escape(reason):state==='researching'?`${progress.percent}% · ${duration(progress.left/1000)}`:state==='ready'?'INSTALL READY':`LEVEL ${lv} / ${maximum(item)}`}</small></span><em>${state==='completed'?'✓':state==='locked'?'◇':state==='ready'?'!':item.prestige?`P${item.prestige}`:'›'}</em></button>`}
function branchMarkup(group){const items=DEFS.filter(item=>item.branch===group.id).sort((a,b)=>a.tier-b.tier),mobileActive=activeBranch===group.id;return`<section class="researchBranch branch-${group.id} ${mobileActive?'mobileActive':''}" data-research-branch-row="${group.id}"><header><i>${group.icon}</i><span><b>${group.name}</b><small>${group.description}</small></span></header><div class="researchBranchPath"><span class="researchCoreLink" aria-hidden="true"></span>${items.map(nodeMarkup).join('')}<div class="researchFuture"><i>•••</i><b>FUTURE TECH</b><small>EXPANSION READY</small></div></div></section>`}
function researchTotals(){return DEFS.reduce((totals,item)=>{totals.current+=Math.min(level(item.id),maximum(item));totals.maximum+=maximum(item);return totals},{current:0,maximum:0})}
function requirementMarkup(item){const rows=requirements(item);if(!rows.length)return'<span class="met">✓ BUNKR CORE ACCESS</span>';return rows.map(requirement=>`<span class="${requirement.current>=requirement.level?'met':'unmet'}">${requirement.current>=requirement.level?'✓':'◇'} ${escape(requirement.item?.name||requirement.id)} · ${requirement.current}/${requirement.level}</span>`).join('')}
function inspectorMarkup(item){if(!item)return'<aside class="researchInspector"><div class="researchInspectorEmpty">SELECT A RESEARCH NODE</div></aside>';const lv=level(item.id),state=nodeState(item),reason=lockReason(item),summary=effectSummary(item),scrap=cost(item),science=scienceCost(item),time=seconds(item),missingScrap=Math.max(0,scrap-S.scrap),missingScience=Math.max(0,science-S.science),busy=!!(R.active||R.ready),buttonText=state==='ready'?'INSTALL BREAKTHROUGH':state==='researching'?'RESEARCH IN PROGRESS':state==='completed'?'FULLY MASTERED':state==='locked'?reason:busy?'RESEARCH SLOT BUSY':canAfford(item)?'START RESEARCH':missingScrap&&missingScience?'NEED SCRAP & SCIENCE':missingScrap?'NEED SCRAP':'NEED SCIENCE',next=DEFS.filter(candidate=>(candidate.requires||[]).some(requirement=>requirement.id===item.id)).map(candidate=>candidate.name);return`<aside class="researchInspector" data-research-inspector="${item.id}"><header><div><small>${escape(branch(item.branch)?.name)} · TIER ${item.tier}</small><h2>${escape(item.name)}</h2></div><span>LV ${lv}/${maximum(item)}</span></header><div class="researchInspectorIntro"><i>${item.icon}</i><p>${escape(item.desc)}</p></div><strong class="researchBenefit">${escape(item.benefit)}</strong><section class="researchEffect"><span><small>CURRENT STATUS</small><b>${summary.current}</b></span><span><small>NEXT BREAKTHROUGH</small><b>${escape(summary.next)}</b></span></section><section class="researchRequirements"><h3>PREREQUISITES</h3>${item.prestige?`<span class="${prestigeLevel()>=item.prestige?'met':'unmet'}">${prestigeLevel()>=item.prestige?'✓':'◇'} PRESTIGE ${prestigeLevel()} / ${item.prestige}</span>`:''}${requirementMarkup(item)}</section><section class="researchFunding"><h3>PROJECT FUNDING</h3><div><span><i>⚙</i><small>SCRAP</small><b>${fmt(scrap)}</b><em>${missingScrap?'MISSING '+fmt(missingScrap):'FUNDED'}</em></span><span><i>✦</i><small>SCIENCE</small><b>${fmt(science)}</b><em>${missingScience?'MISSING '+fmt(missingScience):'FUNDED'}</em></span><span><i>◷</i><small>TIME</small><b>${duration(time)}</b><em>OFFLINE SAFE</em></span></div></section><section class="researchUnlocks"><h3>UNLOCKS</h3>${next.length?next.map(name=>`<span>› ${escape(name)}</span>`).join(''):'<span>› FUTURE BRANCH EXPANSION</span>'}</section><button type="button" class="researchStart ${state}" data-research-action="${item.id}" ${!['available','ready'].includes(state)||state==='available'&&!canAfford(item)?'disabled':''}>${escape(buttonText)}</button>${reason&&state==='locked'?`<p class="researchLockReason">◇ ${escape(reason)}</p>`:''}</aside>`}
function branchNavigation(totals){return`<nav class="researchBranchNav"><button type="button" data-research-branch="overview"><i>☷</i><span><small>NETWORK</small><b>OVERVIEW</b></span></button>${BRANCHES.map(group=>{const items=DEFS.filter(item=>item.branch===group.id),done=items.reduce((sum,item)=>sum+Math.min(level(item.id),maximum(item)),0),max=items.reduce((sum,item)=>sum+maximum(item),0);return`<button type="button" data-research-branch="${group.id}" class="${activeBranch===group.id?'active':''}"><i>${group.icon}</i><span><small>${done} / ${max}</small><b>${group.short}</b></span></button>`}).join('')}<div><b>${totals.current} / ${totals.maximum} RESEARCHED</b><small>${DEFS.filter(item=>item.prestige&&prestigeLevel()<item.prestige).length} PRESTIGE NODES LOCKED</small></div></nav>`}
function render(container=document.getElementById('drawerBody')){badge();if(!container||!document.querySelector('[data-tab="research"].active'))return;delete container.dataset.expeditionAtlas;delete container.dataset.commandCenter;container.dataset.researchCommand='ready';const selected=def(selectedId)||DEFS[0],totals=researchTotals(),labOnline=!labReason();container.innerHTML=`<main class="researchCommand"><header class="researchCommandHeader"><div><small>BUNKR SCIENCE DIVISION</small><h1>RESEARCH NETWORK</h1><p>Every breakthrough strengthens the shelter. Research paths reset unless protected by the Archive Core.</p></div><section><span><small>LAB STATUS</small><b class="${labOnline?'online':'offline'}">${labOnline?'ONLINE':'OFFLINE'}</b></span><span><small>RESEARCH SLOT</small><b>${R.active||R.ready?'0 / 1':'1 / 1'}</b></span><span><small>SCIENCE</small><b>✦ ${fmt(S.science)}</b></span><span><small>SCRAP</small><b>⚙ ${fmt(S.scrap)}</b></span></section></header>${activityMarkup()}<section class="researchWorkspace"><div class="researchTreeViewport"><div class="researchTree"><div class="researchCore"><i>⌂</i><b>BUNKR CORE</b><small>SCIENCE NETWORK</small></div><div class="researchBranches">${BRANCHES.map(branchMarkup).join('')}</div></div><div class="researchLegend"><span><i class="completed"></i>COMPLETED</span><span><i class="available"></i>AVAILABLE</span><span><i class="researching"></i>RESEARCHING</span><span><i class="locked"></i>LOCKED</span><span><i class="prestige"></i>PRESTIGE LOCKED</span></div></div>${inspectorMarkup(selected)}</section>${branchNavigation(totals)}</main>`;bind(container);updateLive()}
function select(id,container=document.getElementById('drawerBody')){const item=def(id);if(!item)return false;selectedId=id;activeBranch=item.branch;render(container);container?.querySelector(`[data-research-node="${id}"]`)?.focus({preventScroll:true});return true}
function bind(container){container.querySelectorAll('[data-research-node]').forEach(button=>button.addEventListener('click',()=>select(button.dataset.researchNode,container)));container.querySelectorAll('[data-research-branch]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.researchBranch;if(id==='overview'){container.querySelector('.researchTreeViewport')?.scrollTo?.({left:0,top:0,behavior:'smooth'});return}const first=DEFS.find(item=>item.branch===id);activeBranch=id;if(first)select(first.id,container)}));container.querySelector('[data-research-claim]')?.addEventListener('click',claim);container.querySelector('[data-research-action]')?.addEventListener('click',event=>{const id=event.currentTarget.dataset.researchAction;if(R.ready?.id===id)claim();else start(id)})}
function updateLive(){if(R.active&&Date.now()>=R.active.end){finish();return}if(!R.active)return;const progress=activeProgress(),root=document.querySelector('#drawerBody[data-research-command="ready"]');if(!root)return;root.querySelectorAll('[data-research-progress]').forEach(element=>element.style.width=progress.percent+'%');root.querySelectorAll('[data-research-percent]').forEach(element=>element.textContent=progress.percent+'%');root.querySelectorAll('[data-research-time]').forEach(element=>element.textContent=duration(progress.left/1000));const node=root.querySelector(`[data-research-node="${R.active.id}"] small`);if(node)node.textContent=`${progress.percent}% · ${duration(progress.left/1000)}`}
function tick(){if(R.active&&Date.now()>=R.active.end)finish();else updateLive()}
const productionBonus=resource=>resource==='scrap'?multiplier('circuit'):['food','water'].includes(resource)?multiplier('closedLoop'):1;
const criticalChanceAdd=()=>level('armorPiercing')*.015;
const hordeDamageMultiplier=()=>1+level('hordeControl')*.25;
const bruteDamageMultiplier=()=>1+level('walls')*.15;
const roomCostMultiplier=()=>Math.pow(.94,level('fortressGrid'));
const expeditionTimeMultiplier=()=>Math.pow(.94,level('rapidDeployment'));
const expeditionCoinMultiplier=()=>multiplier('routeMapping');
const expeditionScrapMultiplier=()=>multiplier('advancedRecovery');
const companionChanceAdd=()=>level('companionRescue')*.015+level('geneticArchive')*.02;
const specialistChanceAdd=()=>level('geneticArchive')*.04;
window.BunkrResearch={start,finish,claim,render,select,cost:id=>{const item=def(id);return item?cost(item):0},scienceCost:id=>{const item=def(id);return item?scienceCost(item):0},seconds:id=>{const item=def(id);return item?seconds(item):0},level,lockReason,nodeState,researchTotals,productionBonus,criticalChanceAdd,hordeDamageMultiplier,bruteDamageMultiplier,roomCostMultiplier,expeditionTimeMultiplier,expeditionCoinMultiplier,expeditionScrapMultiplier,companionChanceAdd,specialistChanceAdd,researchTimeMultiplier};
document.body.dataset.researchSystem='ready';
window.addEventListener('bunkr:state',event=>{if(['research-start','research-complete','research-claim'].includes(event.detail?.reason))badge()});
setInterval(tick,500);badge();if(R.active&&Date.now()>=R.active.end)setTimeout(finish,0);
})();
