(()=>{'use strict';
const CFG=window.AfterlightConfig,ST=window.AfterlightState,NUM=window.AfterlightNumbers;if(!CFG||!ST||!NUM)throw new Error('Research dependencies missing');
const S=ST.get(),R=S.researchRuntime,DEFS=CFG.RESEARCH;
const def=id=>DEFS.find(item=>item.id===id)||null;
const level=id=>Math.max(0,Number(S.research[id]||0));
const cost=item=>Math.max(1,Math.round(item.baseCost*Math.pow(item.costGrowth,level(item.id))));
const seconds=item=>Math.min(21600,Math.round(item.baseSeconds*Math.pow(item.timeGrowth,level(item.id))));
const fmt=NUM.format;
function duration(value){value=Math.max(0,Math.ceil(value));const h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=value%60;return h?`${h}h ${String(m).padStart(2,'0')}m`:m?`${m}m ${String(s).padStart(2,'0')}s`:`${s}s`}
function effect(item,lv=level(item.id)){const total=(Math.pow(item.effect,lv)-1)*100,next=(item.effect-1)*100;return lv?`CURRENT +${total.toFixed(total<10?1:0)}% · NEXT +${next.toFixed(0)}%`:`NEXT LEVEL +${next.toFixed(0)}%`}
function start(id){const item=def(id);if(!item||R.active||R.ready)return false;const price=cost(item);if(S.scrap<price)return false;const now=Date.now(),time=seconds(item);ST.update('research-start',state=>{state.scrap-=price;R.active={id,start:now,end:now+time*1000,cost:price}});render();window.AfterlightGame?.hud?.();return true}
function finish(){if(!R.active||Date.now()<R.active.end)return false;const active={...R.active};ST.update('research-complete',()=>{R.active=null;R.ready={id:active.id,finishedAt:Date.now(),cost:active.cost}});window.dispatchEvent(new CustomEvent('afterlight:research-complete',{detail:{id:active.id,level:level(active.id)+1}}));render();return true}
function claim(){const ready=R.ready,item=def(ready?.id);if(!ready||!item)return false;ST.update('research-claim',()=>{S.research[item.id]=level(item.id)+1;R.ready=null});window.dispatchEvent(new CustomEvent('afterlight:research-claimed',{detail:{id:item.id,level:level(item.id)}}));render();window.AfterlightGame?.hud?.();window.AfterlightGame?.renderRooms?.();return true}
function badge(){const el=document.getElementById('researchBadge');if(!el)return;el.textContent=R.ready?'!':'';el.classList.toggle('visible',!!R.ready)}
function activeCard(){const item=def(R.active?.id);if(!item)return'';const total=R.active.end-R.active.start,left=Math.max(0,R.active.end-Date.now()),pct=Math.max(0,Math.min(100,(Date.now()-R.active.start)/total*100));return `<section class="researchActive"><header><span>RESEARCH IN PROGRESS</span><b>${duration(left/1000)}</b></header><div class="researchActiveTitle"><i>${item.icon}</i><div><b>${item.name}</b><small>LEVEL ${level(item.id)+1} · ${effect(item)}</small></div></div><div class="researchBar"><i style="width:${pct}%"></i><span>${Math.floor(pct)}%</span></div><small>THE BUNKER KEEPS RESEARCHING WHILE YOU ARE AWAY</small></section>`}
function readyCard(){const item=def(R.ready?.id);if(!item)return'';return `<section class="researchReady"><div class="researchReadyGlow">✦</div><small>BREAKTHROUGH COMPLETE</small><h2>${item.icon} ${item.name}</h2><p>LEVEL ${level(item.id)+1} READY · ${effect(item,level(item.id)+1)}</p><button type="button" data-research-claim>INSTALL RESEARCH</button></section>`}
function cards(){return DEFS.map(item=>{const lv=level(item.id),price=cost(item),time=seconds(item),locked=!!R.active||!!R.ready,afford=S.scrap>=price;return `<article class="researchCard ${locked?'researchBusy':''}"><i>${item.icon}</i><div><header><b>${item.name}</b><span>LV ${lv}</span></header><p>${item.desc}</p><small>${effect(item)}</small><footer><em>⚙ ${fmt(price)} SCRAP</em><em>◷ ${duration(time)}</em></footer></div><button type="button" data-research-start="${item.id}" ${locked||!afford?'disabled':''}>${locked?'BUSY':afford?'RESEARCH':'NEED SCRAP'}</button></article>`}).join('')}
function render(container=document.getElementById('drawerBody')){badge();if(document.querySelector('[data-tab="research"].active')&&container){container.innerHTML=`<div class="researchIntro"><b>RESEARCH DIVISION</b><span>Invest scrap into permanent, multiplicative bunker upgrades. One project can run at a time.</span><em>⚙ ${fmt(S.scrap)} AVAILABLE</em></div>${readyCard()}${activeCard()}<section class="researchGrid">${cards()}</section>`;container.querySelector('[data-research-claim]')?.addEventListener('click',claim);container.querySelectorAll('[data-research-start]').forEach(button=>button.addEventListener('click',()=>start(button.dataset.researchStart)))}}
function tick(){if(R.active&&Date.now()>=R.active.end)finish();else if(document.querySelector('[data-tab="research"].active')&&R.active)render()}
window.AfterlightResearch={start,finish,claim,render,cost:id=>{const item=def(id);return item?cost(item):0},seconds:id=>{const item=def(id);return item?seconds(item):0},level};
document.body.dataset.researchSystem='ready';
window.addEventListener('afterlight:state',event=>{if(['research-start','research-complete','research-claim'].includes(event.detail?.reason))badge()});
setInterval(tick,500);badge();if(R.active&&Date.now()>=R.active.end)setTimeout(finish,0);
})();
