(()=>{'use strict';
const scene=document.getElementById('scene'),CFG=window.BunkrConfig,ST=window.BunkrState,NUM=window.BunkrNumbers;if(!scene||!CFG||!ST||!NUM)return;
const SKINS=CFG.SURVIVOR_SKINS||[],COMPANIONS=CFG.EXPEDITION_COMPANIONS||[],COMPANION_COMBAT_SCALE=1.1,CASING_ASSET='assets/combat-brass-casing.webp',CASING_LIMIT=12,reducedMotion=window.matchMedia?window.matchMedia('(prefers-reduced-motion: reduce)'):null,selectedSkin=()=>SKINS.find(skin=>skin.id===ST.get().survivorSkins?.selected&&skin.asset)||SKINS.find(skin=>skin.id==='ranger-male'&&skin.asset)||SKINS.find(skin=>skin.asset),selectedCompanion=()=>{const state=ST.get().expeditions||{},owned=Array.isArray(state.companions)?state.companions:[];return owned.includes(state.selectedCompanion)?COMPANIONS.find(pet=>pet.id===state.selectedCompanion&&pet.asset):null};
const WORLD_LAYERS=[
  ['worldSky','assets/combat-sky.webp'],
  ['worldClouds','assets/combat-clouds.webp'],
  ['worldCity','assets/combat-city.webp'],
  ['worldBunker','assets/combat-bunker-clean.webp'],
  ['worldGround','assets/combat-ground.webp']
];
const stage=document.createElement('div');stage.id='spriteStage';stage.dataset.parallaxLayers=String(WORLD_LAYERS.length);stage.dataset.worldMotion='clouds-only';
const world=document.createElement('div');world.className='parallaxWorld';world.setAttribute('aria-hidden','true');
for(const [className,src] of WORLD_LAYERS){const layer=document.createElement('div');layer.className='parallaxLayer '+className;const image=document.createElement('img');image.src=src;image.alt='';image.decoding='async';image.draggable=false;layer.append(image);world.append(layer)}
stage.append(world);
const survivorUnit=document.createElement('div');survivorUnit.className='survivorUnit';
const survivor=document.createElement('img');survivor.className='survivorSprite';survivor.alt='Survivor';survivor.decoding='async';survivor.draggable=false;
const companionUnit=document.createElement('div');companionUnit.className='companionUnit hidden';companionUnit.setAttribute('aria-live','polite');
const companionSprite=document.createElement('i');companionSprite.className='companionSprite';companionSprite.setAttribute('role','img');companionUnit.append(companionSprite);
const enemyUnit=document.createElement('div');enemyUnit.className='enemyUnit';enemyUnit.setAttribute('aria-live','polite');
const enemyStack=document.createElement('div');enemyStack.className='enemyStack';enemyUnit.append(enemyStack);
const muzzle=document.createElement('i');muzzle.className='muzzleFx';muzzle.setAttribute('aria-hidden','true');survivorUnit.append(survivor,muzzle);const impact=document.createElement('i');impact.className='impactFx';const streakHud=document.createElement('aside');streakHud.id='combatStreak';streakHud.setAttribute('aria-live','polite');stage.append(survivorUnit,companionUnit,enemyUnit,impact,streakHud);scene.prepend(stage);
function applySurvivor(source=selectedSkin(),animate=true){const skin=typeof source==='string'?SKINS.find(candidate=>candidate.id===source):source?.detail?.skin||source?.detail?.survivor||source?.detail?.id&&SKINS.find(candidate=>candidate.id===source.detail.id)||source;if(!skin?.asset)return false;const x=Number(skin.muzzleAnchor?.x)||77.5,y=Number(skin.muzzleAnchor?.y)||20.5,ejectX=Math.max(8,x-18),ejectY=Math.min(92,y+2.5),anchor=`${x}% ${y}%`,ejectAnchor=`${ejectX}% ${ejectY}%`;survivor.src=skin.asset;survivor.alt=skin.name||'Survivor';survivor.dataset.survivorId=skin.id;survivorUnit.dataset.muzzleAnchor=anchor;survivorUnit.dataset.ejectAnchor=ejectAnchor;survivorUnit.dataset.rarity=skin.rarity||'standard';survivorUnit.style.setProperty('--muzzle-x',x+'%');survivorUnit.style.setProperty('--muzzle-y',y+'%');survivorUnit.style.setProperty('--eject-x',ejectX+'%');survivorUnit.style.setProperty('--eject-y',ejectY+'%');survivorUnit.style.setProperty('--survivor-accent',skin.accent||'transparent');stage.dataset.survivorAsset=skin.asset.split('/').pop();stage.dataset.survivorId=skin.id;stage.dataset.survivorRarity=skin.rarity||'standard';if(animate){restart(survivorUnit,'swap');setTimeout(()=>survivorUnit.classList.remove('swap'),360)}return true}
function applyCompanion(source=selectedCompanion(),animate=true){const state=ST.get().expeditions||{},owned=Array.isArray(state.companions)?state.companions:[],pet=typeof source==='string'?COMPANIONS.find(candidate=>candidate.id===source):source?.detail?.companion||source?.detail?.id&&COMPANIONS.find(candidate=>candidate.id===source.detail.id)||source;if(!pet?.asset||!owned.includes(pet.id)){companionUnit.classList.add('hidden');companionUnit.removeAttribute('data-companion-id');delete stage.dataset.companionId;return false}companionUnit.classList.remove('hidden');companionUnit.dataset.companionId=pet.id;companionUnit.dataset.rarity=pet.rarity||'common';companionUnit.style.setProperty('--companion-asset',`url('${pet.asset}')`);companionUnit.style.setProperty('--companion-scale',String((Number(pet.scale)||1)*COMPANION_COMBAT_SCALE));companionUnit.style.setProperty('--companion-accent',pet.accent||'#ccb96b');companionSprite.setAttribute('aria-label',`${pet.name} companion`);stage.dataset.companionId=pet.id;stage.dataset.companionAsset=pet.asset.split('/').pop();if(animate){restart(companionUnit,'swap');setTimeout(()=>companionUnit.classList.remove('swap'),420)}return true}
applySurvivor(selectedSkin(),false);
applyCompanion(selectedCompanion(),false);
const layerImages=[...world.querySelectorAll('img')];Promise.allSettled(layerImages.map(image=>image.decode?.()||Promise.resolve())).then(()=>stage.classList.add('worldReady'));
for(const asset of [CASING_ASSET,...(CFG.ENEMIES||[]).flatMap(item=>[item.asset,item.idleAsset,item.walkAsset,item.hitAsset,item.deathAsset]),...SKINS.map(item=>item.asset),...COMPANIONS.map(item=>item.asset)].filter(Boolean)){const preload=new Image();preload.src=asset}

function restart(el,cls){el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls)}
let spawnClearTimer=0;
let hitClearTimer=0;
function clearSpawn(){clearTimeout(spawnClearTimer);spawnClearTimer=0;enemyUnit.classList.remove('spawn')}
enemyUnit.addEventListener('animationend',event=>{if(event.target===enemyUnit&&event.animationName.startsWith('enemyEnter'))clearSpawn()});
const ENEMY_HIT_ANCHORS=Object.freeze({common:[.5,.36],zouki:[.48,.34],uncommon:[.5,.37],rare:[.49,.36],epic:[.53,.42],legendary:[.5,.36],brute:[.52,.38]});let shotTargetIndex=0;
function enemyImpactPoint(detail={}){const stageRect=stage.getBoundingClientRect(),sprites=[...enemyStack.querySelectorAll('.enemySprite')];if(!stageRect.width||!sprites.length)return null;const sprite=sprites[shotTargetIndex++%sprites.length],spriteRect=sprite.getBoundingClientRect(),id=detail.enemy?.id||enemyUnit.dataset.enemyId||'common',anchor=ENEMY_HIT_ANCHORS[id]||ENEMY_HIT_ANCHORS.common;if(!spriteRect.width||!spriteRect.height)return null;return{x:spriteRect.left-stageRect.left+spriteRect.width*anchor[0],y:spriteRect.top-stageRect.top+spriteRect.height*anchor[1]}}
function positionImpact(point){if(!point)return false;impact.style.left=(point.x-impact.offsetWidth/2)+'px';impact.style.top=(point.y-impact.offsetHeight/2)+'px';impact.style.right='auto';impact.style.bottom='auto';return true}
let damageFloatIndex=0;
function damageFloat(event,point=enemyImpactPoint(event.detail)){const detail=event.detail||{},damage=Math.max(0,Number(detail.damage)||0);if(!damage||!point)return;const float=document.createElement('b'),offsets=[-18,12,-6,20,-12,0];float.className='damageNumber'+(detail.critical?' critical':'');float.setAttribute('aria-hidden','true');float.textContent=(detail.critical?'CRIT -':'-')+NUM.format(damage);float.style.left=(point.x+offsets[damageFloatIndex%offsets.length])+'px';float.style.top=(point.y-18)+'px';damageFloatIndex+=1;stage.append(float);const active=stage.querySelectorAll('.damageNumber');if(active.length>8)active[0].remove();setTimeout(()=>float.remove(),760)}
const HIT_PIXEL_STYLES=Object.freeze({common:{blood:'#96251d',accent:'#d94a35',count:5,size:3},uncommon:{blood:'#8a1f18',accent:'#d74432',count:6,size:4},rare:{blood:'#98231d',accent:'#e04b38',count:6,size:3},epic:{blood:'#7f1916',accent:'#c9362b',count:8,size:5},legendary:{blood:'#922019',accent:'#dc4633',count:7,size:4},brute:{blood:'#6f120f',accent:'#bc2d24',count:10,size:6}});
const HIT_PIXEL_VECTORS=[[-26,-24,20],[-17,-36,12],[-8,-29,27],[3,-40,17],[12,-31,29],[22,-22,18],[29,-13,31],[-31,-10,34],[7,-19,38],[18,-37,24],[34,-26,19],[-21,-17,42]];let hitPixelIndex=0;
function hitPixels(event,point=enemyImpactPoint(event.detail)){if(reducedMotion?.matches||document.documentElement.classList.contains('reducedEffects')||!point)return 0;const detail=event.detail||{},id=detail.enemy?.id||enemyUnit.dataset.enemyId||'common',tier=detail.enemy?.tier||enemyUnit.dataset.rarity||id,style=HIT_PIXEL_STYLES[tier]||HIT_PIXEL_STYLES.common,count=style.count+(detail.critical?2:0),burst=hitPixelIndex++;for(let index=0;index<count;index++){const pixel=document.createElement('i'),vector=HIT_PIXEL_VECTORS[(index+burst)%HIT_PIXEL_VECTORS.length],size=style.size+(detail.critical&&index%3===0?2:0);pixel.className='hitPixel';pixel.setAttribute('aria-hidden','true');pixel.style.left=point.x+'px';pixel.style.top=point.y+'px';pixel.style.setProperty('--pixel-color',index%4===0?style.accent:style.blood);pixel.style.setProperty('--pixel-size',size+'px');pixel.style.setProperty('--pixel-x',vector[0]*(detail.critical?1.22:1)+'px');pixel.style.setProperty('--pixel-rise',vector[1]*(tier==='brute'?1.2:1)+'px');pixel.style.setProperty('--pixel-fall',vector[2]*(tier==='epic'||tier==='brute'?1.18:1)+'px');pixel.style.setProperty('--pixel-rotate',(index%2?-1:1)*(45+index*23)+'deg');stage.append(pixel);setTimeout(()=>pixel.remove(),520)}const active=[...stage.querySelectorAll('.hitPixel')];while(active.length>48)active.shift()?.remove();return count}
const CASING_ARCS=Object.freeze([[16,-29,-13,700],[23,-35,5,790],[11,-31,-20,650],[28,-27,15,860]]);let casingIndex=0;
function ejectCasing(){if(reducedMotion?.matches||document.documentElement.classList.contains('reducedEffects'))return null;const stageRect=stage.getBoundingClientRect(),survivorRect=survivorUnit.getBoundingClientRect();if(!stageRect.width||!survivorRect.width)return null;const anchor=(survivorUnit.dataset.ejectAnchor||'59.5% 23%').split(' ').map(value=>Number.parseFloat(value)||0),startX=survivorRect.left-stageRect.left+survivorRect.width*anchor[0]/100,startY=survivorRect.top-stageRect.top+survivorRect.height*anchor[1]/100,index=casingIndex++,arc=CASING_ARCS[index%CASING_ARCS.length],size=Math.max(16,Math.min(22,stageRect.width*.019)),groundY=Math.max(18,survivorRect.bottom-stageRect.top-startY-size*.7),duration=680+(index%3)*35,casing=document.createElement('i');casing.className='shellCasing';casing.dataset.casingId=String(index+1);casing.setAttribute('aria-hidden','true');casing.style.left=startX+'px';casing.style.top=startY+'px';casing.style.setProperty('--casing-apex-x',arc[0]+'px');casing.style.setProperty('--casing-apex-y',arc[1]+'px');casing.style.setProperty('--casing-land-x',arc[2]+'px');casing.style.setProperty('--casing-ground-y',groundY+'px');casing.style.setProperty('--casing-apex-spin',Math.round(arc[3]*.42)+'deg');casing.style.setProperty('--casing-land-spin',arc[3]+'deg');casing.style.setProperty('--casing-rebound-spin',arc[3]+125+'deg');casing.style.setProperty('--casing-final-spin',arc[3]+230+'deg');casing.style.setProperty('--casing-duration',duration+'ms');stage.append(casing);stage.dataset.lastCasingAnchor=`${Math.round(startX)} ${Math.round(startY)}`;const active=[...stage.querySelectorAll('.shellCasing')];while(active.length>CASING_LIMIT)active.shift()?.remove();setTimeout(()=>casing.remove(),duration+80);return casing}
function shotFeedback(event){clearSpawn();const critical=!!event.detail?.critical,id=event.detail?.enemy?.id||enemyUnit.dataset.enemyId||'common',brute=event.detail?.enemy?.brute===true||id==='brute',duration=brute?240:180,point=enemyImpactPoint(event.detail);positionImpact(point);impact.classList.toggle('critical',critical);impact.classList.toggle('brute',brute);stage.dataset.lastShotSurvivor=survivor.dataset.survivorId||'';stage.dataset.lastMuzzleAnchor=survivorUnit.dataset.muzzleAnchor||'';ejectCasing();restart(survivorUnit,'shoot');restart(enemyUnit,'hit');restart(muzzle,'fire');restart(impact,'pop');damageFloat(event,point);hitPixels(event,point);clearTimeout(hitClearTimer);hitClearTimer=setTimeout(()=>{survivorUnit.classList.remove('shoot');enemyUnit.classList.remove('hit');impact.classList.remove('critical','brute')},duration)}
const rewardFmt=NUM.format;
let deathSequenceId=0;
function createDeathSequence(detail){if(!detail.deathAsset)return null;const stageRect=stage.getBoundingClientRect(),unitRect=enemyUnit.getBoundingClientRect();if(!stageRect.width||!unitRect.width)return null;const count=Math.min(CFG.COMBAT?.hordeVisualCount||3,Math.max(1,Number(detail.visualCount)||1)),unit=document.createElement('div'),stack=document.createElement('div'),duration=Math.max(200,Number(CFG.COMBAT?.deathAnimationMs)||390),lifetime=Math.max(duration+300,Number(CFG.COMBAT?.corpseVisibleMs)||1500);unit.className='enemyDeathUnit'+(detail.horde?' horde':'');unit.dataset.deathSequence=detail.id||'common';unit.dataset.deathSequenceId=String(++deathSequenceId);unit.dataset.enemyCount=String(count);unit.setAttribute('aria-hidden','true');unit.style.left=(unitRect.left-stageRect.left)+'px';unit.style.top=(unitRect.top-stageRect.top)+'px';unit.style.width=unitRect.width+'px';unit.style.height=unitRect.height+'px';unit.style.setProperty('--death-duration',duration+'ms');stack.className='enemyDeathStack';for(let index=0;index<count;index++){const frame=document.createElement('i');frame.className='enemyDeathSprite';frame.style.backgroundImage=`url('${detail.deathAsset}')`;stack.append(frame)}unit.append(stack);if(detail.brute||detail.id==='brute')setTimeout(()=>{restart(stage,'bruteDeathImpact');setTimeout(()=>stage.classList.remove('bruteDeathImpact'),340)},Math.round(duration*.66));enemyUnit.classList.add('defeated');stage.append(unit);requestAnimationFrame(()=>unit.classList.add('play'));const limit=Math.max(1,Number(CFG.COMBAT?.corpseLimit)||3),corpses=[...stage.querySelectorAll('.enemyDeathUnit')];while(corpses.length>limit)corpses.shift()?.remove();setTimeout(()=>unit.classList.add('fade'),lifetime-260);setTimeout(()=>unit.remove(),lifetime);return{unit,rect:unitRect,stageRect}}
function killRewards(event){const detail=event.detail||{};stage.querySelector('.killRewards')?.remove();enemyUnit.classList.remove('hit');const death=createDeathSequence(detail);if(!death)restart(enemyUnit,'dead');const rewards=document.createElement('div');rewards.className='killRewards'+(death?' corpseRewards':'');rewards.innerHTML=`<b>+${rewardFmt(detail.coins||0)} COINS</b><span>+${rewardFmt(detail.scrap||0)} SCRAP</span>${detail.streakMultiplier>1?`<em class="streakDrop">CHAIN ×${Number(detail.streakMultiplier).toFixed(2)}</em>`:''}${detail.uranium?`<em class="uraniumDrop">+${detail.uranium} URANIUM CRYSTAL</em>`:''}${detail.core?'<em class="coreDrop">+1 BRUTE CORE</em>':''}`;if(death){rewards.style.left=(death.rect.left-death.stageRect.left+death.rect.width*.55)+'px';rewards.style.top=(death.rect.bottom-death.stageRect.top-8)+'px'}stage.append(rewards);setTimeout(()=>rewards.remove(),1700)}
let streakTimer=0,streakExpiry=0;
function renderStreak(event){const detail=event.detail||{},count=Math.max(1,Number(detail.count)||1),multiplier=Math.max(1,Number(detail.multiplier)||1),windowMs=Math.max(1000,Number(detail.windowMs)||12000);streakExpiry=Number(detail.expiresAt)||Date.now()+windowMs;clearTimeout(streakTimer);streakHud.style.setProperty('--streak-duration',windowMs+'ms');streakHud.innerHTML=`<small>${count===1?'CHAIN START':'KILL CHAIN · '+count}</small><b>×${multiplier.toFixed(2)}</b><div><i></i></div>`;restart(streakHud,'show');streakTimer=setTimeout(()=>{if(Date.now()>=streakExpiry)streakHud.classList.remove('show')},windowMs+80)}
function roomMilestoneCelebrate(event){const detail=event.detail||{},milestone=detail.milestone,room=CFG.ROOMS?.[detail.id];if(!milestone||!room)return false;document.querySelector('.roomMilestoneWin')?.remove();const colors={CALIBRATED:'#9fbd50',INDUSTRIAL:'#62a6dc',FORTIFIED:'#ab6bd6',MASTERWORK:'#e8bd47',OVERDRIVEN:'#e78d43',ASCENDANT:'#e8bd47'},element=document.createElement('section'),multiplier=milestone.multiplier>=1000?NUM.format(milestone.multiplier):Number(milestone.multiplier.toFixed(2));element.className='roomMilestoneWin';element.style.setProperty('--milestone-color',colors[milestone.tier]||'#d8b84d');element.innerHTML=`<div class="roomMilestoneCard"><div class="roomMilestoneArt" style="background-image:url('${room.art}')"></div><small>PERMANENT ROOM MILESTONE</small><b>${room.icon} ${room.name}</b><strong>LEVEL ${milestone.absoluteLevel||milestone.level}</strong><span>${milestone.label||milestone.tier} · TOTAL MILESTONE BONUS ×${multiplier}</span><div class="roomMilestoneParticles">${'<i></i>'.repeat(14)}</div></div>`;document.body.append(element);requestAnimationFrame(()=>element.classList.add('show'));setTimeout(()=>{element.classList.remove('show');setTimeout(()=>element.remove(),450)},3000);return true}
function createEnemySprite(detail,index){const configured=CFG.ENEMIES?.find(item=>item.id===(detail.id||'common'))||detail,label=index?'':detail.name||configured.name||'Infected',asset=detail.asset||configured.asset||'assets/enemy-common-drifter.webp',idleAsset=detail.idleAsset||configured.idleAsset,walkAsset=detail.walkAsset||configured.walkAsset,hitAsset=detail.hitAsset||configured.hitAsset;if(idleAsset){const sprite=document.createElement('i'),frames=document.createElement('i');sprite.className='enemySprite commonAnimatedSprite';sprite.dataset.enemyId=configured.id||detail.id||'';sprite.setAttribute('role','img');sprite.setAttribute('aria-label',label);sprite.style.setProperty('--enemy-idle',`url('${idleAsset}')`);sprite.style.setProperty('--enemy-walk',`url('${walkAsset||idleAsset}')`);sprite.style.setProperty('--enemy-hit',`url('${hitAsset||idleAsset}')`);frames.className='commonFrames';frames.setAttribute('aria-hidden','true');sprite.append(frames);return sprite}if(hitAsset){const sprite=document.createElement('i'),base=document.createElement('img'),frames=document.createElement('i');sprite.className='enemySprite infectedAnimatedSprite';sprite.dataset.enemyId=configured.id||detail.id||'';sprite.setAttribute('role','img');sprite.setAttribute('aria-label',label);base.className='infectedBaseSprite';base.src=asset;base.alt='';base.decoding='async';base.draggable=false;base.setAttribute('aria-hidden','true');frames.className='infectedHitFrames';frames.style.backgroundImage=`url('${hitAsset}')`;frames.setAttribute('aria-hidden','true');sprite.append(base,frames);return sprite}const image=document.createElement('img');image.className='enemySprite';image.src=asset;image.alt=label;image.decoding='async';image.draggable=false;return image}
function renderEnemy(event){const detail=event.detail||{},tier=detail.tier||detail.id||'common',maxHorde=CFG.COMBAT?.hordeVisualCount||3,count=Math.min(maxHorde,Math.max(1,Number(detail.visualCount)||1));enemyUnit.dataset.rarity=tier;enemyUnit.dataset.enemyId=detail.id||'common';enemyUnit.classList.toggle('horde',!!detail.horde);enemyUnit.classList.toggle('brute',!!detail.brute);enemyUnit.style.setProperty('--enemy-accent',detail.accent||'#b7b4a5');enemyStack.replaceChildren();for(let index=0;index<count;index++)enemyStack.append(createEnemySprite(detail,index));enemyUnit.dataset.enemyCount=String(count);enemyUnit.classList.remove('dead','hit','defeated');restart(enemyUnit,'spawn');clearTimeout(spawnClearTimer);spawnClearTimer=setTimeout(clearSpawn,500);stage.dataset.enemyId=detail.id||'common';stage.dataset.enemyRarity=tier;stage.dataset.enemyHorde=detail.horde?'true':'false';const card=document.getElementById('enemyCard');if(card){card.dataset.rarity=tier;card.style.setProperty('--enemy-accent',detail.accent||'#b7b4a5');card.classList.toggle('bossGlow',!!detail.brute)}}
window.addEventListener('bunkr:shot',shotFeedback);window.addEventListener('bunkr:enemy-killed',killRewards);window.addEventListener('bunkr:enemy',renderEnemy);window.addEventListener('bunkr:streak',renderStreak);window.addEventListener('bunkr:room-upgraded',roomMilestoneCelebrate);window.addEventListener('bunkr:survivor-selected',event=>applySurvivor(event));window.addEventListener('bunkr:prestige-complete',event=>{applySurvivor(event);applyCompanion(selectedCompanion())});window.addEventListener('bunkr:companion-selected',event=>applyCompanion(event));window.addEventListener('bunkr:expedition-roster',()=>applyCompanion(selectedCompanion()));

const pulsePairs=[['coins','cps'],['food','foodps'],['water','waterps'],['power','powerps'],['science','scienceps']];
function rateFrom(id){const el=document.getElementById(id);if(!el)return 0;const match=(el.textContent||'').replace(',','.').match(/\+([\d.]+)/);return match?parseFloat(match[1]):0}
function pulse(valueId,rateId){const value=document.getElementById(valueId),rate=rateFrom(rateId),card=value?.closest('.resource');if(!card||!(rate>0))return;restart(card,'resourcePulse');setTimeout(()=>card.classList.remove('resourcePulse'),160);const pop=document.createElement('span');pop.className='gainPop';pop.textContent='+'+(rate<10?rate.toFixed(1):Math.round(rate));card.append(pop);setTimeout(()=>pop.remove(),900)}
setInterval(()=>pulsePairs.forEach(pair=>pulse(...pair)),1000);

window.BunkrVisuals={applySurvivor,selectedSurvivor:selectedSkin,applyCompanion,selectedCompanion,ejectCasing,shotFeedback,damageFloat,hitPixels,createDeathSequence,killRewards,renderEnemy,renderStreak,roomMilestoneCelebrate,enemyUnit:()=>enemyUnit,survivorUnit:()=>survivorUnit,companionUnit:()=>companionUnit,parallaxLayers:()=>WORLD_LAYERS.map(([name,src])=>({name,src}))};
})();
