'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),fail=message=>{throw new Error(`Merchant balance: ${message}`)};
const sandbox={window:{}};vm.runInNewContext(read('js/core/config.js'),sandbox,{filename:'config.js'});
const {MERCHANT_OFFERS,EXPEDITIONS}=sandbox.window.AfterlightConfig||{};
if(!Array.isArray(MERCHANT_OFFERS)||MERCHANT_OFFERS.length!==6)fail('the Dealer must carry exactly six focused offers');
const expectedCosts={gold5:25,gold10:60,all3:75,scrap5:30,hunter:40,lure:50};
const ids=new Set(),groups={};
for(const offer of MERCHANT_OFFERS){if(ids.has(offer.id))fail(`duplicate offer ${offer.id}`);ids.add(offer.id);if(offer.seconds!==300)fail(`${offer.id} must last exactly five minutes`);if(offer.cost!==expectedCosts[offer.id])fail(`${offer.id} cost drifted from ${expectedCosts[offer.id]} crystals`);if(!offer.effect||!offer.value||!offer.tagline)fail(`${offer.id} needs effect and presentation metadata`);(groups[offer.group]||=[]).push(offer)}
if(groups.overdrive?.length!==3)fail('5x, 10x and everything contracts must share one exclusive overdrive channel');
if(MERCHANT_OFFERS.find(x=>x.id==='gold5').effect.coins!==5||MERCHANT_OFFERS.find(x=>x.id==='gold10').effect.coins!==10)fail('coin contracts must retain 5x and 10x values');
if(MERCHANT_OFFERS.find(x=>x.id==='all3').effect.all!==3)fail('the expensive everything contract must remain 3x');
if(Math.max(...groups.overdrive.map(offer=>offer.effect.coins||offer.effect.all||1))>10)fail('exclusive premium coin production exceeds the approved 10x ceiling');
const expectedCrystalRates={store:[.2,1,1],blocks:[.35,1,1],clinic:[.6,1,2],metro:[.8,2,3],checkpoint:[1,4,6]};
for(const [id,[chance,min,max]] of Object.entries(expectedCrystalRates)){const zone=EXPEDITIONS[id];if(zone.uraniumChance!==chance||zone.uranium[0]!==min||zone.uranium[1]!==max)fail(`${id} crystal reward table drifted`);const expectedPerHour=3600/zone.seconds*chance*((min+max)/2);if(expectedPerHour<3.5||expectedPerHour>12.1)fail(`${id} yields an unfair ${expectedPerHour.toFixed(2)} expected crystals/hour`)}
const state=read('js/core/state.js');for(const [pattern,message] of [[/schema:17/,'save schema must migrate to 17'],[/uranium:0/,'state requires Uranium Crystals'],[/merchant:\{active:\{\},purchases:\{\}/,'state requires persisted merchant runtime'],[/uraniumEarned:0,uraniumSpent:0/,'state must track crystal economy totals']])if(!pattern.test(state))fail(message);
const merchantHudSource=read('js/systems/merchant.js'),hudHtml=read('index.html'),hudCss=read('app.css');if(!/function renderBoostHud\(\)/.test(merchantHudSource)||!/data-boost-hud-time/.test(merchantHudSource))fail('active Dealer boosts require a live countdown HUD renderer');if(!/renderBoostHud\(\)/.test(merchantHudSource.split('function updateUi')[1]||''))fail('Dealer HUD countdowns must update with the existing 500ms timer');if(!/id="activeBoostHud"/.test(hudHtml)||!/#activeBoostHud/.test(hudCss))fail('Dealer boost HUD shell or styling is missing');
const merchant=read('js/systems/merchant.js');for(const [pattern,message] of [[/state\.uranium-=offer\.cost/,'purchases must spend only Uranium Crystals'],[/Math\.max\(now\(\),Number\(S\.merchant\.active/,'repurchases must extend an active contract'],[/other\.group===offer\.group/,'same-channel contracts must not stack'],[/Number\(offer\.effect\?\.all\)>0/,'the everything contract must reach production, damage and bounties through the shared multiplier API'],[/afterlight:merchant-purchase/,'purchases must emit dopamine feedback'],[/rarityWeights\(\).*common:30,uncommon:30,rare:20,epic:10,legendary:6,brute:4/s,'Blacklight Lure odds must total 100%'],[/Date\.now/,'boosts must use persisted wall-clock deadlines']])if(!pattern.test(merchant))fail(message);
const game=read('js/core/game.js');for(const [pattern,message] of [[/AfterlightMerchant\?\.multiplier\?\.\(q\)/,'passive production must consume Dealer multipliers'],[/AfterlightMerchant\?\.multiplier\?\.\('damage'\)/,'combat damage must consume Dealer multipliers'],[/AfterlightMerchant\?\.multiplier\?\.\('zombie'\)/,'bounties must consume Dealer multipliers'],[/AfterlightMerchant\?\.rarityWeights/,'enemy selection must consume lure odds'],[/uranium=1;S\.uranium=/,'Brutes must award exactly one crystal'],[/for\(const q of \['coins','food','water','power','scrap','science'\]\)/,'Uranium must never receive passive production']])if(!pattern.test(game))fail(message);
const missions=read('js/systems/missions.js'),expeditions=read('js/systems/expeditions.js'),html=read('index.html'),audio=read('js/audio.js');
if(!/uraniumReward=q=>Math\.max\(1,Math\.min\(6,1\+Math\.floor/.test(missions)||!/legacyMissionGrantDone/.test(missions))fail('missions must grant capped tier-scaled crystals and compensate existing saves');
if(!/findsUranium=zone=>.*Math\.random\(\)<zone\.uraniumChance/.test(expeditions)||!/uranium=findsUranium\(zone\)\?pick\(zone\.uranium\):0/.test(expeditions)||!/s\.uranium=\(s\.uranium\|\|0\)\+\(r\.uranium\|\|0\)/.test(expeditions))fail('expeditions must roll and collect configured crystals');
if(/data-tab="build"/.test(html)||!/data-tab="merchant"/.test(html)||!/id="uranium"/.test(html)||!/js\/systems\/merchant\.js/.test(html))fail('Build tab must be replaced by the Dealer and its currency HUD');
if(!/afterlight:merchant-purchase',merchantSound/.test(audio))fail('Dealer purchases require their own satisfying audio event');
console.log('Afterlight merchant balance passed: 6 five-minute offers, exclusive 10x maximum coin overdrive, fair crystal sources and no passive Uranium production.');
