'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');let errors=[];
const fail=m=>errors.push(m),exists=p=>fs.existsSync(path.join(root,p));
function walk(dir,ext,out=[]){if(!fs.existsSync(dir))return out;for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isDirectory())walk(p,ext,out);else if(!ext||p.endsWith(ext))out.push(p)}return out}
for(const file of walk(path.join(root,'js'),'.js')){try{new vm.Script(fs.readFileSync(file,'utf8'),{filename:path.relative(root,file)})}catch(e){fail(`JS syntax: ${path.relative(root,file)}: ${e.message}`)}}
const htmlPath=path.join(root,'index.html');if(!fs.existsSync(htmlPath))fail('Missing index.html');else{
  const html=fs.readFileSync(htmlPath,'utf8');
  const refs=[...html.matchAll(/<(?:script|link)\b[^>]*(?:src|href)=["']([^"']+)["']/gi)].map(m=>m[1]);
  for(const ref of refs){if(/^(?:https?:|data:|#)/i.test(ref))continue;const clean=ref.split(/[?#]/)[0].replace(/^\.\//,'');if(clean&&!exists(clean))fail(`Missing index reference: ${ref}`)}
  if(!/<title>Bunkr: Last Shelter<\/title>/.test(html))fail('Canonical BUNKR page title is missing');
  if(html.indexOf('js/core/brand.js')<0||html.indexOf('js/core/brand.js')>html.indexOf('js/core/config.js'))fail('Brand contract must load before every game module');
}
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));if(manifest.name!=='Bunkr: Last Shelter'||manifest.short_name!=='BUNKR')fail('PWA metadata is not canonically branded');for(const icon of ['assets/branding/bunkr-icon-192.png','assets/branding/bunkr-icon-512.png','assets/branding/bunkr-apple-touch-icon.png'])if(!exists(icon))fail(`Missing BUNKR brand asset: ${icon}`);
for(const file of ['index.html','manifest.webmanifest','app.css','js/platform.js','js/core/config.js','js/systems/command-center.js'])if(/afterlight/i.test(fs.readFileSync(path.join(root,file),'utf8')))fail(`Legacy brand leaked into player-facing file: ${file}`);
const brandSource=fs.readFileSync(path.join(root,'js','core','brand.js'),'utf8');for(const [pattern,message] of [[/fullName:'Bunkr: Last Shelter'/,'Central full brand name is missing'],[/legacyStorageKey:'afterlight_v4'/,'Legacy save compatibility key is missing'],[/canonical='Bunkr'\+name,legacy='Afterlight'\+name/,'Temporary API compatibility aliases are missing'],[/new CustomEvent\('afterlight:'\+name/,'Legacy event bridge is missing']])if(!pattern.test(brandSource))fail(message);
for(const file of walk(root,'.css')){const css=fs.readFileSync(file,'utf8');for(const m of css.matchAll(/url\(["']?([^"')]+)["']?\)/gi)){const ref=m[1];if(/^(?:https?:|data:|#)/i.test(ref))continue;const target=path.resolve(path.dirname(file),ref.split(/[?#]/)[0]);if(!fs.existsSync(target))fail(`Missing CSS asset: ${path.relative(root,file)} -> ${ref}`)}}
const audioPath=path.join(root,'js','audio.js');if(fs.existsSync(audioPath)){const source=fs.readFileSync(audioPath,'utf8');for(const [pattern,message] of [[/window\.AudioContext\|\|window\.webkitAudioContext/,'UI audio must support the iOS-prefixed AudioContext'],[/document\.addEventListener\('pointerdown',onUiPointer,true\)/,'UI audio must use one delegated user-gesture listener'],[/target\.closest\('#scene'\)/,'UI button audio must leave combat to bunkr:shot'],[/window\.addEventListener\('bunkr:shot',gunshot\)/,'Gun audio must use the existing bunkr:shot event'],[/const UI_VOLUME=1\.1/,'UI button volume must retain its requested 10% boost'],[/createDynamicsCompressor/,'Synthesized SFX must use a master compressor'],[/\['room','special-room'\]/,'UI audio must react to the existing state API for confirmations']])if(!pattern.test(source))fail(message)}
const gamePath=path.join(root,'js','core','game.js');if(fs.existsSync(gamePath)){const source=fs.readFileSync(gamePath,'utf8');for(const [pattern,message] of [[/function resourceBreakdown\(q\)/,'Resource stats must derive their source breakdown from the core economy'],[/data-stat-second/,'Resource stats must expose live per-second production'],[/total\*60/,'Resource stats must calculate per-minute production'],[/total\*3600/,'Resource stats must calculate per-hour production'],[/openResourceStats/,'Resource cards must open their statistics screen']])if(!pattern.test(source))fail(message)}
const eventChecks=[['js/core/game.js',/bunkr:enemy-killed/,'Enemy kills must emit their cash SFX event'],['js/systems/missions.js',/bunkr:mission-claimed/,'Claimed missions must emit their reward SFX event'],['js/systems/expeditions.js',/bunkr:expedition-complete/,'Expedition reveal must emit its completion SFX event'],['js/systems/merchant.js',/bunkr:merchant-purchase/,'Dealer purchases must emit their activation event'],['js/audio.js',/function cashSound\(\)/,'Audio must provide a cash reward sound'],['js/audio.js',/function rewardSound\(kind='mission'\)/,'Audio must provide long-form reward sounds'],['js/audio.js',/function merchantSound\(\)/,'Audio must provide a Dealer purchase sound']];for(const [file,pattern,message] of eventChecks)if(!pattern.test(fs.readFileSync(path.join(root,file),'utf8')))fail(message);
const researchSource=fs.readFileSync(path.join(root,'js','systems','research.js'),'utf8');for(const [pattern,message] of [[/state\.scrap-=scrapPrice/,'Research must spend scrap'],[/state\.science-=sciencePrice/,'Research must spend science atomically with scrap'],[/Math\.pow\(item\.costGrowth/,'Research cost must scale exponentially'],[/Math\.pow\(item\.scienceGrowth/,'Research science cost must scale exponentially'],[/Math\.pow\(item\.timeGrowth/,'Research duration must scale exponentially'],[/R\.ready=\{id:/,'Completed research must enter a claimable ready state'],[/bunkr:research-complete/,'Research completion must emit an audio event'],[/setInterval\(tick,500\)/,'Research timer must keep progressing']])if(!pattern.test(researchSource))fail(message);
const visualSource=fs.readFileSync(path.join(root,'js','ui','visuals.js'),'utf8');for(const [pattern,message] of [[/bunkr:enemy-killed',killRewards/,'Kill rewards must use the existing enemy-killed event'],[/detail\.coins/,'Kill rewards must display the exact awarded coins'],[/detail\.scrap/,'Kill rewards must display the exact awarded scrap'],[/className='killRewards'/,'Kill rewards must render above the corpse'],[/const WORLD_LAYERS=/,'Combat visuals must define one authoritative world layer list'],[/dataset\.parallaxLayers/,'Combat visuals must expose the rendered world layer count'],[/dataset\.worldMotion='clouds-only'/,'Combat world motion must be limited to clouds']])if(!pattern.test(visualSource))fail(message);if(/pointermove|--parallax-x|--parallax-y/.test(visualSource))fail('Combat background must not react to pointer movement');
const parallaxAssets=['combat-sky.webp','combat-clouds.webp','combat-city.webp','combat-bunker-clean.webp','combat-ground.webp'];for(const asset of parallaxAssets){if(!exists(path.join('assets',asset)))fail(`Missing combat parallax asset: ${asset}`);if(!visualSource.includes(`assets/${asset}`))fail(`Unused combat parallax asset: ${asset}`)}
const enemyAssets=['enemy-common-drifter.webp','enemy-uncommon-cinderback.webp','enemy-rare-blue-shield.webp','enemy-epic-bloater.webp','enemy-legendary-gilded-warden.webp','enemy-brute-breaker.webp'];const configSource=fs.readFileSync(path.join(root,'js','core','config.js'),'utf8');for(const asset of enemyAssets){if(!exists(path.join('assets',asset)))fail(`Missing enemy asset: ${asset}`);if(!configSource.includes(`assets/${asset}`))fail(`Enemy asset is not configured: ${asset}`)}
const rootNames=fs.readdirSync(root);const legacy=[/^game\d+\.js$/i,/^phase\d+\.css$/i,/^polish\d+\.(?:js|css)$/i,/^sprite\d+\.(?:js|css)$/i];for(const name of rootNames)if(legacy.some(r=>r.test(name)))fail(`Legacy numbered file still present: ${name}`);
if(errors.length){console.error(`Bunkr validation failed (${errors.length})`);for(const e of errors)console.error(' - '+e);process.exit(1)}
console.log(`Bunkr validation passed: ${walk(path.join(root,'js'),'.js').length} JS modules, all local references resolved.`);
